/**-------------------------------------------
 * 
 * STORE FOR MAGUS BARD SPELLS
 * 
 * -------------------------------------------
 */
 const state = {
    bardSpellDescription: [
        'A BÁRD MANA-PONTJAI',
        'A bárd mágiájának titkát hiába keresnénk Ynev beláthatatlan térségein: e kaszt képviselői Mana-pontjaikat-ellentétben az összes többi varászhasználó kaszttal-a Felsőbb Szférák, a csillagok energiájából meritik. Éjszakánként, mikor fények garmadája tündököl az égen, a bárdnak lehetősége nyillik arra, hogy ( maga választotta főhangszerén ) megszólaltassa a mitikus erők öszhangzatát. Az Öszhangzat megszólaltatása mindössze 18 kört vesz igénybe, ez idő alatt a bárd max Mp-jaira kerül. A bárd csak akkor képes az Öszhangzat segitségével Mana-pontokhoz jutni, ha a csillagfény szabad szemmel érzékelhető számára-borús ég alatt, zivatar sötétjében nem jutnak el hozzá az energiák.',
    ],
    bardSpells: {
        dalMagia: {
            name: 'Dalmágia',
            description: [
                'Ynev bárdjai jártassak az Asztrál- és Mentálvarázslatok használatában, ám azokat csak egy különleges módszer, a Dalmágia segitségével képessek alkalmazni. Ennek gyakorlásához énekelniük, vagy muzsikálniuk kell, hogy a dallamok formába öntség, és célba juttassák, a varázslat bennük felgyúlt energiáit.',
                'FIGYELEM! A bárd dalmágiája kizárólag élőlényekre hat! A varázslat eredményességének feltétele az is, hogy a kiszemelt alany hallja a dalt. Amenyiben a célpont süket, vagy - saját jól felfogott érdekében - fülének befogásával védekezik a mágia ellen, a dal hatástalan marad.',
                'A bárdok egyszerre több lényre is alkalmazhatják a Dalmágia varázslatait, s a dal hatókörén belül ők határozhatják meg, ki legyen az, akire a dal varázslatként hat. A dal többi hallgatója nem érzékeli a dallamba ágyazott mágiát: értetlenül állnak majd társaik megváltozott viselkedése előtt. A bárdnak, mint fentebb emlitettük, énekelnie sem feltétlenül szükséges, elég, ha hangszerén játszik, a Dalmágia ez esetben is megidézhető.',
                'Ritkán kerül sor arra, hogy egy bárd csatába használja a dalmágiát - ez alól talán csak a Bátorság dala jelent kivételt. A harcmező zaja ugyanis elnyomja a bárd énekét, s a Dalmágia varázslatainak hatótávolsága a felére csökken. A dalok mágiájának viszont kedvez a csend, melyben a dal messzire elhallatszik, s a hatótáv ennek hatására a kétszeresére nő.',
                'Fontos, hogy a Dalmágia varázslatai tökéletesen összekapcsolódnak a bárd énekmondó, szórakoztató képességeivel. Hisz varázslataik mindaddig észrevétlenek maradhatnak, mig a hatás nyilvánvalóvá nem válik - ám ekkora sokszor már minden hiába. A Dalmágia álldozatait a bárd választhatja meg, tehát a varázslat hatókörén belül tartózkodók közül csak azokra vonatkozik a hatás, akiket a bárd célpontnak szemelt ki. A varázslat megidézéséhez szükséges idő sokszor megegyezik az Időtartammal - ennek oka, hogy a mágia csak addig hat, mig a bárd énekel. Előfordulhat az is, hogy a bárd énekének hatása továbbra is fennmarad, ilyen esetben álldozatonként változik, hogy mennyi idő szükséges a dal emlékének elűtéséhez.',
            ],
            spells: [
                {
                    name: 'Nyugalom dala',
                    typ: 'Asztrális',
                    mana: 1,
                    manaText: '1/célpont',
                    strenght: '5',
                    castTime: '1 perc',
                    effectTime: 'k6 kör',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Asztrális',
                    description: [
                        'A bárd énekének hatására minden olyan lény, amely 10 láb sugarú körön belül tartózkodik, hallja a dalt, Mágiaellenállása pedig sikertelen, elveszti harci kedvét, megnyukszik. Ha ebben az állapotában megtámadják, újra a fegyveréhez kap, s harcolni kezd. Ekkor már nem nyugtatható meg a dallal, sőt az énekesre fog támadni, ha teheti. A bárdok ezzel a varázslattal igen óvatosan bánnak, hiszen a hatás könnyen ellenük forditható. A varázslat erőssége 4E-nként 1 Mana-pont felhasználásával növelhető, Időtartalma a bárd dalának ideje, illetve utánna még 1k6 kör.',
                    ],
                },
                {
                    name: 'Álom dala',
                    typ: 'Mentális',
                    mana: 12,
                    manaText: '12/célpont',
                    strenght: '6',
                    castTime: '3 kör',
                    effectTime: '15 kör utánna természetes alvás',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Mentális',
                    description: [
                        'Ennek az éneknek a hatására a bárd körül 10 lábnyi körzetben tartózkodó lények, ha Mágiaellenálásuk sikertelen, mély állomba merülnek. Az igazi alváshoz a bárd énekét legalább három körig kell hallaniuk, a hatás csak utánna jelentkezik. Ekkor a dalt halló lények elalszanak, s 15 körön át fel sem ébreszthetők, csak mágia segitségével. Utánna az alvás természetessé, az álldozatcsoport közönséges módon felrázhatóvá, fellocsolhatóvá válik. A varázslat erősitése 1E-nként 1 Mp-t igényel.',
                    ],
                },
                {
                    name: 'Zavarodottság dala',
                    typ: 'Asztrális',
                    mana: 35,
                    manaText: '35',
                    strenght: '25',
                    castTime: '1 perc',
                    effectTime: 'végleges',
                    effectRange: '10 láb',
                    resistance: 'Asztrális',
                    description: [
                        'Az egyik legerősebb érzelmekre ható dal, melyel a bárd rendelkezik. Minden érzelmet a visszájára fordithat az álldozatban, ha annak Mágiaellenállása sikertelen volt. Az eddigi szeretetből gyűlölet lesz, a félelemből bátorság, a barátságból ellenszenv és megforditva. Az álldozat 25%-ban beleőrül a hirtelen változásba, s ha nem, akkor is nehéz lesz uj önmagán kiigazodnia. Minden érzelme az ellentétére változott, de a semlegesek, vagy a közel semlegesek nem alakultak át. Egy társat tehát, akihez különösen erős indulatok, érzelmek nem fűzték, most sem fog szeretni vagy gyűlölni. A varázslat a leghétköznapibb érzelmekre is hat, ennek következménye a legkevésbé megfoghatók. Például az a Keleti Barbár harcos, aki eddig egy vagyont fizetett volna a vaddisznópörcért, most, most viszolyogva fogja a kocsmáros ölébe boritani azt. A varázslat 4 Mp-vel erősithető 1 E-nként, csak egy célpontra alkalmazható, a hatása pedig végleges. Megjegyezendő, hogy ha az álldozatra egy másik esetleg ugyanaz a bárd ezt a varázslatot még egyszer ráénekli, a célpont érzelmei eredeti állapotukba rendeződnek vissza.',
                    ],
                },
                {
                    name: 'Bénitás dala',
                    typ: 'Mentális',
                    mana: 8,
                    manaText: '8/célpont',
                    strenght: '7',
                    castTime: '2+k6 kör',
                    effectTime: 'k6 kör',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Mentális',
                    description: [
                        'A bárd dalának hatására minden 10 lábnyi körzetben tartózkodó lény gondolatainak középpontjába a mágikus zene kerül, s ettől teljesen mozdulatlanná válnak. Ehhez a dalt legalább két körig kell hallaniuk, s utánna Mágiaellenállást dobniuk - sikertelenség esetén k6 körig csak a bárd zenéjére figyelnek, s érzéketlenek lesznek minden más jelenség, benyomás iránt. Az igy elbájolt álldozatok, csak a mágia megszűnése után nyerik vissza uralmukat gondolataik felett, vagy abban az esetben, ha egy körben több mint 15 Sp-t sebeznek rajtuk. A dal erősitése 1E-nként 1 Mana-pontot igényel.',
                    ],
                },
                {
                    name: 'Félelem dala',
                    typ: 'Asztrális',
                    mana: 4,
                    manaText: '4/lény',
                    strenght: '6',
                    castTime: '1 perc',
                    effectTime: 'a dal hossza',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Asztrális',
                    description: [
                        'A dal félelmet ébreszt a bárd ellenségeinek szivébe. A bárd szövetségeseire a dal nem hat, igy ők a dal alatt is a bárd közelébe maradhatnak. Az ellenfelek, akik hallják a dalt, Mágiaellenállás dobására jogosultak, s ha elvétik, azonnal menekülni kezdenek az ének forrásától. A varázslat addig tart, mig a bárd énekel, erősiteni pedig 3E-nként 1 Mana-pontért lehet.',
                    ],
                },
                {
                    name: 'Feledés dala',
                    typ: 'Mentális',
                    mana: 20,
                    manaText: '20',
                    strenght: '12',
                    castTime: '3 perc',
                    effectTime: 'egyszeri',
                    effectRange: '10 láb',
                    resistance: 'Mentális',
                    description: [
                        'A dal segitségével egyetlen nap emlékeit törölheti ki álldozatából. Csak a nap dátumára kell koncentrálnia a varázslat alatt, a tartalmát nem szükséges ismernie. Az emlékek, ha a Mágiaellenállás sikertelen, teljesen elvesznek, s a nap üres foltként marad meg az álldozat emlékezetében. Tudni fogja, hogy a nap létezett, de ennél többet nem. Emlékei nem adhatók vissza, de társai elmagyarázhatják neki, mi is történt akkor. Hogy ezt elhiszi, vagy nem az egészen más kérdés. A varázslat Hatótávolsága 10 láb, erősitése 1E-nként 2 Mana-pontot igényel.',
                    ],
                },
                {
                    name: 'Emlékek dala',
                    typ: 'Mentális',
                    mana: 25,
                    manaText: '25',
                    strenght: '12',
                    castTime: '3 perc',
                    effectTime: 'végleges',
                    effectRange: '10 láb',
                    resistance: 'Mentális',
                    description: [
                        'A dal segitségével lehetségessé válik emlékek, élmények elhelyezése az álldozat elméjében. A varázslattal maximálisan egy napi emlék irható be a memóriába, de ehhez üres helyre van szükség. Ez lehet természetes felejtés, de előidézhető a Feledés dalával is. Igy egy nap teljesen átirhatóvá válik valaki emlékezetében. Ha nincs ennyi kiesett emlék, egy-egy napba legfeljebb plusz 15 perc illeszthető be a varázslattal. A varázslat maximális hatótávolsága 10 láb, erősitése pedig 1E-nként 3 Mana-pont segitségével történhet.',
                    ],
                },
                {
                    name: 'Kinok dala',
                    typ: 'Mentális',
                    mana: 4,
                    manaText: '4/kör',
                    strenght: '25',
                    castTime: '1 kör',
                    effectTime: 'a dal hossza',
                    effectRange: 'hallótávolság',
                    resistance: 'Mentális',
                    description: [
                        'A bárd ezen varázslattal fájdalmat okozhat mindazoknak, akik a dalt halják. A fájdalom borzalmas hasogató fejfájásként jelentkezik, majd kinhullámként seper végig az egész testen. A célpont Mágiaellenállásra jogosult a varázslat ellen. Amennyiben az ME dobás sikertelen, az álldozat 1k6 Sp-t veszit körönként. A dal annyi ideig tartható fenn, mig a bárd kivánja, s Mana-pontjai ezt lehetővé teszi. A hatósugár mindég a hallótávolsággal egyezik meg.',
                        'FIGYELEM! A dalt énekelni, nem bömbölni kell, igy a hatósugár - efféle módon - nem növelhető.',
                    ],
                },
                {
                    name: 'Bájolás dala',
                    typ: 'Asztrális',
                    mana: 5,
                    manaText: '5/lény',
                    strenght: '6',
                    castTime: '1 perc',
                    effectTime: '2 óra',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Asztrális',
                    description: [
                        'A dal segitségével a bárd 10 lábnyi körzeten belül minden hallgatóját barátjává teheti. Ha a hallgatók Mágiaellenállása sikertelen volt, követni, s lehetőségeik szerint segiteni fogják a bárdot. Ha a bárd - fegyverrel vagy mágiával - megtámadja őket, a varázslat hatása semmivé foszlik. Az elbájolt lények mindi igazat fognak válaszolni a bárd kérdéseire, s egy esetleges harmadik féllel vivot harcban is a védelmére kelnek. A varázslat hatóideje 2 óra, erősitése pedig 1E-nként 2 Mana-pont segitségével történhet.',
                    ],
                },
                {
                    name: 'Halál dala',
                    typ: 'Asztrális',
                    mana: 45,
                    manaText: '45/lény',
                    strenght: '15',
                    castTime: '1 kör',
                    effectTime: 'végleges',
                    effectRange: '10 láb sugaró kör',
                    resistance: 'Asztrális',
                    description: [
                        'A bárd legkegyetlenebb fegyvere a lant - szól a mondás Ynev-szerte. A Halál dala valóban pusztulást hozhat minden lényre, aki hallja. Ha a mágiaellenállás sikertelen, az álldozat Asztráltestét megsemmisitő csapás éri, s a lélek szétszakadásának sokkja halált okoz. A célpontnak a bárd 10 lábnyi körzetében kell tartózkodnia, s hallania kell a dalt. A varázslat 1E-nként 4 Mana-pont befektetésével erősithető.',
                    ],
                },
                {
                    name: 'Bátorság dala',
                    typ: 'Asztrális',
                    mana: 7,
                    manaText: '7',
                    strenght: '5',
                    castTime: '1 kör',
                    effectTime: 'a dal hossza',
                    effectRange: '10 láb vagy 100 láb',
                    resistance: '-',
                    description: [
                        'A bárd ezzel a varázslattal társainak harci kedvét növelheti. A varázslat 10 láb körzetben hatásos, s minden a bárdal szövetséges lényre hat. Minden olyan lény KÉ-je 5-tel, TÉ-je 15-tel nő, aki a varázslat pillanatában a dalt hallota, és a Hatótávon belül tartózkodott.',
                        'A varázslat másik alkalmazási módja esetén a Hatótáv 100 lábsugarú kör, melynek területén a dal szinte végigsöpör. Ez a bárddal szövetséges harcosoknak csak a harci kedvét, lelkesedését növeli, s Bátorságukhoz 3-at ad. Ideális varázslat csaták során. A távolság dalával kombinálva különösen ütőképessé válhat.',
                    ],
                },
            ]
        },
        hangMagia: {
            name: 'Hangmágia',
            description: [
                'A megtévesztés ynevi művészei a bárdok, olyannyira, hogy Hang- és Fénymágiájukkal - mely ugyan semmiféle anyagi hatással nem bir - sokszor ütőképesebbek lehetnek, mint más mágiahasználók.',
                'Kevés azon Hangmágiákhoz tartozó varázslatok száma, melyeket önálló alkalmazásra szántak. Ezen varázslatok inkább támogatást bisztositanak a Fénymágia illúzióinak, vagy a Dalmágia hatásait befolyásolják. Összefonódnak a más csoportba tartozó varázslatokkal, tökéletes egységet alkotva velük.',
            ],
            spells: [
                {
                    name: 'Távolság dala',
                    typ: 'Hangmágia',
                    mana: 10,
                    manaText: '10/szorzó',
                    strenght: '5',
                    castTime: '1 szegmens',
                    effectTime: 'a hangositott dal ideje',
                    effectRange: '-',
                    resistance: '-',
                    description: [
                        'Ez a varázslat bármely daltipusú mágiával együtt alkalmazható. A Dalmágia hangerejét többszörösére növeli, igy a hatósugár is nő. A hatósugár 2, 3, 4-szeresére növelhető, méghozzá a kétszeres növelés 10, a háromszoros 20, a négyszeres 30 Mana-pontért stb. A varázslat hatóideje megegyezik a hangositott dal időtartalmával.',
                    ],
                },
                {
                    name: 'Mágia dala',
                    typ: 'Hangmágia',
                    mana: 10,
                    manaText: '10',
                    strenght: '5',
                    castTime: '1 szegmens',
                    effectTime: 'mint az eredeti varázslat',
                    effectRange: '-',
                    resistance: '-',
                    description: [
                        'Ez a dal lehetőséget ad a bárdnak arra, hogy nem daltipusú varázslatokat muzsikálás vagy éneklés leple alatt alkalmazzon. A két varázslat egyszerre lép működésbe, de a Mágia dala csak a másik varázslat megidézéséhez - és annak leplezéséhez - szükséges. Igy észrevétlenül varázsolhat a bárd akár nagy tömegekben is. hiszen a megfigyelők csak annyit tapasztalnak, hogy énekel.',
                    ],
                },
                {
                    name: 'Dalegyesités',
                    typ: 'Hangmágia',
                    mana: 18,
                    manaText: '18',
                    strenght: '5',
                    castTime: '1 szegmens',
                    effectTime: 'mig a varázslatok tartanak',
                    effectRange: '-',
                    resistance: '-',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
            ]
        },
        fenyMagia: {
            name: '',
            description: [
                '',
            ],
            spells: [
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
            ]
        },
        egyebbMagia: {
            name: '',
            description: [
                '',
            ],
            spells: [
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
            ]
        },
    },
};
const getters = {
    bardSpellDescription: () => {
        return state.bardSpellDescription;
    },
    bardSpells: () => {
        return state.bardSpells;
    },
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}