/**-------------------------------------------
 * 
 * STORE FOR MAGUS Skills
 * 
 * -------------------------------------------
 */
 const state = {
    skills: [
        {
            id: 'OKOLHARC',
            name: 'Ökölharc',
            KpAf: 3,
            KpMf: 15,
            description: 'A karakter gyakorlott kétkezi verekedő. Nem jön zavarba, ha fegyverét valamely okból nem használhatja ( esetleg nincs is nála ). Az Ökölharc-bár fegyver nélkül űzik-nem hasonlit a harcművészetekre, nem is nyukszik hasonló alapokon. Inkább egyfajta Erőn és Ügyességen alapuló, művészetnek semmiképp nem nevezhető harcmodor. Az a karakter, aki ismeri az ökölharc fortélyait, nem szenvedi el a Képzetlen Fegyverforgatásból-ezesetben a puszta kéz képzetlen használatából eredő hátrányokat, és a küzdelemben mindkét kezét használhatja ( kétszer támad ). Az Alapfokot és a Mesterfokot kizárólag a puszta ököl sebzésének mértéke különbözteti meg egymástól.',
            Af: '1-2 Sp',
            Mf: '1-6 Sp',
        },
        {
            id: 'BIRKOZAS',
            name: 'Birkózás',
            KpAf: 8,
            KpMf: 15,
            description: 'A képzetség rokon az Ökölharccal, ám a birkózó kezét nem öklözésre, hanem ellenfelének lefogására, leszoritására használja. Ahhoz, hogy ezt megtehesse, természetesen sikeres Támadó Dobást kell tennie. Sebzés nincs, ellenben az álldozat körökre mozgásképtelenné tehető, mialatt támadni sem képes. Ha a képzetség alkalmazója egyszer már megragadta ellenfelét, és erősebb is nála, annak kevés az esélye a szoritásból szabadulni. A birkózó minden körben köteles Erőpróbát tenni, s az álldozatnak csak akkor nyilik egyáltalán lehetősége a szabadulásra, ha elvéti. Még ilyenkor sincs veszve semmi, mert a lefogott csak akkor menekülhet, ha az ő Erőpróbája ellenben sikeres. Ha az álldozat ereje nagyobb a lefogónál, ő tehet minden körbem Erőpróbát, s ha sikerrel jár, nyomban ki is bontakozik a marasztaló karokból. Ha a támadás, amivel a birkózó megragadja áldozatát túlütés, a lefogott személy a szoritásban nagy esélyel elveszti eszméletét. Ez akkor következik be, ha a birkózó, közvetlen a túlütést követő körben, sikeres Erőpróbát tesz.',
            Af: 'Az alapfokon képzett karakter, ha fegyveres ellenféllel birkózik, minden támadását -15-tel dobja.',
            Mf: 'A Mesterfokon képzett birkózó fegyveres ellenfél ellenében sem kerül hátrányba.',
        },
        {
            id: 'FEGYVER_HASZNALAT',
            name: 'Fegyverhasználat',
            KpAf: 3,
            KpMf: 30,
            description: 'A Fegyverhasználat a harcos ( és a harccal bármilyen módon foglalkozó ) kasztok tagjai számára talán a legfontosabb képzetség. Ugyanis mindazok, akik nem képzettek egy adott fegyver forgatásában, ha harcolni szándékoznak vele, csak komoly hátránnyal tehetik. Ezt nevezzük Képzetlen Fegyverforgatásnak, ami a következő hátrányokkal jár: KÉ: -10, TÉ: -25, VÉ: -20 Ha valaki képzetlenül nyúl célzó fegyverhez, 30-cal csökken CÉ-je. A játékos amikor a fegyverhasználat képzetséget kiválasztja, értelemszerűen, meg kell határoznia, hogy melyik fegyver forgatásában kivánja járatossá tenni karakterét.',
            Af: 'A karakter a kiválasztott fegyver forgatásában képzett, azt használva nem sújtják a fent emlitett Képzetlen Fegyverforgatásból származó hátrányok.',
            Mf: 'Képes mesterien forgatni az adott fegyvert, ezért amikor azzal harcol, a következő előnyökben részesül: KÉ: +5, TÉ: +10, VÉ: +10, CÉ: +10',
        },
        {
            id: 'PAJZS_HASZNALAT',
            name: 'Pajzshasználat',
            KpAf: 5,
            KpMf: 30,
            description: 'A Pajzshasználatot oktató legnevesebb iskolák: az Oroszlánsziv Lovagrend, a shadoni Isten Kardja Lovagrend, mig az élezett peremű pajzsok forgatásában a gorwicki Marico con Rabora Lovagrend és egyes kráni lovagrendek a legjáratosabbak.',
            Af: 'A karakter képes a küzdelemben pajzsot használni. Védekezni vele ( a pajzs Vé-je hozzáadódik a karakter Védő Értékéhez ) és akár még támadni is. Pajzsal való támadáskor, sikeres Támadó Dobás esetén, pajzsával fellöki az ellenfelet, miközben még másik, fegyveres karjával is támadhat. Ám ha támad a pajzsal, akkor abban a harci körben a védekezésre nem használhatja ( igy annak Vé-je nem adódik hozzá a Védő Értékéhez ).',
            Mf: 'A pajzsal mesteri módon támad, és ha annak pereme élezett, akkor vágni is képes vele. Emellett másik kezét is használhatja - és egyik támadásának TÉ-jére sincsen minusz. Mesterfokon a karakter egyazon körben támadhat és védekezhet is pajzsával, és a pajzs mozgásgátló tényezője megszűnik ( MGT )',
        },
        {
            id: 'FEGYVER_DOBAS',
            name: 'Fegyverdobás',
            KpAf: 4,
            KpMf: 40,
            description: 'Harci helyzetben gyakran előfordul, hogy a karakter valamely okból hajitani szeretné fegyverét. Az esetek nagy többségében ez eleve hajitófegyver ( tőr, dárda, bárd ), de olykor egyébb kézifegyver is lehet. A karakter mikor a Fegyverdobás képzetség elsajátitásához kezd, köteles meghatározni a fegyver tipusát, amelynek hajitásában járatossá kiván válni. A képesség tanulása főként untalan gyakorlásból áll. A tőr hajitásának avatatlan nagymesterei a tolvajklánok, a dárdavetésben a különböző hegyi népek vadászai, mig a lovagikard célbadobásában a Ramort városállam Deva Morrola rendjének lovagjai jeleskednek messze mások előtt. Dobni bármilyen egykezes fegyvert lehet-akár a másfélkezes kardot is, a dobás sikerességének eldöntésében minden esetben Támadó és nem Célzó Dobást kell tenni.',
            Af: 'A karakternek nincs minusza a választott fegyver dobásakor',
            Mf: 'A választott fegyvert a karakter +10 TÉ-vel dobja.',
        },
        {
            id: 'FEGYVERTORES',
            name: 'Fegyvertörés',
            KpAf: 5,
            KpMf: 20,
            description: 'Harc során sokan alkalmazzák a Fegyvertörés képzetséget. A különleges tudomány arra irányul, hogy küzdelem közbe a karakter fegyverével eltörje - használhatatlanná tegye- ellenfele fegyverét. Erre képzet karakter is csak akkor képes, ha szándékát előre - a harci kör elején - bejelenti, majd sikeres Támadódobást tesz. Fegyvertörés csak akkor lehetséges, ha ezt a két összecsapó fegyver tipusa elképzelhetővé teszi - ennek eldöntése a KM feladata.',
            Af: 'A Támadó Dobás 25-tel csökkentett TÉ-vel',
            Mf: 'TÉ minusz nélkül.',
        },
        {
            id: 'LEFEGYVERZES',
            name: 'Lefegyverzés',
            KpAf: 7,
            KpMf: 18,
            description: 'A különleges képzetség segitségével a karakter képes arra, hogy küzdelem közben lefegyverezze ellenfelét. Ezt teheti fegyverrel, de akár puszta kézzel is ( a képzetség elsajátitásánál kell eldönteni ). Lefegyverző szándékát előre - a harci kör elején - kell bejelentenie, majd sikeres Támadó Dobást tennie.',
            Af: '25-tel csökkentett TÉ-vel.',
            Mf: 'TÉ minusz nélkül.',
        },
        {
            id: 'PANCEL_VISELET',
            name: 'Nehézvért viselet',
            KpAf: 3,
            KpMf: 27,
            description: 'A Nehézvért viselet képzetség birtokosa képes küzdelmet folytatni teljesvértezetben és félvértezetben is. Az a karakter aki még alapfokú képzetséggel sem bir, ha nehézvértet ölt, minden fegyverrel úgy harcol mintha annak forgatásában járatlan lenne ( Képzetlen fegyverforgatás: KÉ: -10, TÉ: -25 VÉ: -20 ). A Nehézvért viselet igazi nagymesterei a lovagok és paplovagok, hiszen ők nem kizárólag harci helyzetben, csatákban viselik páncéljukat, hanem szinte szüntelen, gyakran még diszruhaként is.',
            Af: 'Az alapfokon képzett karakter nem szenvedi el az emlitett minuszokat, de gyorsasága és ügyessége továbbra is annyuval csökken, amennyi a viselt vért Mozgásgátló Tényezője ( MGT ).',
            Mf: 'Mesterfokú képzetség esetén már a viselt vért MGT-je sem érvényesül - azaz nem vonódik le a karakter gyorsaságából és ügyességéből.',
        },
        {
            id: 'KETKEZES_HARC',
            name: 'Kétkezes harc',
            KpAf: 15,
            KpMf: 25,
            description: 'Kétkezes harcot folytat az, aki mindkét kezében fegyvert tart. Abban az esetben, ha mingkét fegyvert támadásra használja, minden harci körben kétszer támad: először egyik majd másik kezével. Ha felváltva használja őket, meghatározhatja melyikkel védekezik, és melyikkel támad. Ha a karakter még Alapfokú képzetséggel sem bir, mégis kétkezes harcot folytat, akkor jobbik kezében tartott fegyverrel a következő minuszokkal harcol: KÉ: -5, TÉ: -10, VÉ: -10, mig rosszabbik kezét a Képzetlen Fegyverforgatásból származó minuszok sújtják.',
            Af: 'Alapfokú képzetség esetén a jobbik kezében tartott fegyverre semmiféle minusz nincsen, mig a rosszabbik kézben lévőre, a következő megszoritások érvényesek: KÉ: -2, TÉ: -5, VÉ: -5',
            Mf: 'Mesterfokú képzetség esetén a karakter mindkét kezét minuszok nélkül használhatja a küzdelemben.',
        },
        {
            id: 'VAKHARC',
            name: 'Vakharc',
            KpAf: 10,
            KpMf: 30,
            description: 'Mindazok, akik -vagy mert vakok, vagy bármely más okból- nem látják ellenfelüket, nem érzékelik pontosan a környezetüket jelentős hátránnyal képesek csak harcolni: KÉ: -20, TÉ: -60, VÉ: -70, CÉ: -150. Félhomályban, vagyis alkonyi sötétségben, gyertyák gyér fényével tessék-lássék átjárt helységben nehezebb harcolni, és csak komoly hátrányokkal lehetséges pontosan célozni. Ugyanezen szabály vonatkozik mindazokra, akik korlátozott látási viszonyok között, netán élhomályosult látással kényszerülnek küzdeni. Ennek oka lehet mágia, könny a szemben, pszi stb. Ez a módositó súlytja azokat is, akik ugyan környezetüket látják, viszont ellenfelük valamilyen oknál fogva láthatatlan: KÉ: -15, TÉ: -30, VÉ: -35, CÉ: -70.',
            Af: 'Hangok és neszek alapján tájékozódva, sőt némileg a megérzéseire hagyatkozva is képes harcolni. Ekkor: KÉ: -10, TÉ: -15, VÉ: -20, CÉ: -60.',
            Mf: 'A karakter már belső megérzései alapján harcol. Nem látására, vagy hallására hagytkozik, igy akár le is hunyhatja a szemét, harcértéke nem fog csökkeni. A Vakharc Mesterfokát eredetileg harcművészek dolgozták ki, de ma már mindenki számára megtanulható. A leghiresebb iskola ahol oktatják, a tiadlani Shai-tra kardművész -iskola, ahol 250 aranypénz fizetség ellenében 2 esztendő alatt bárki elsajátithatja ezt a különös tudományt. A Vakharc Mesterfokú ismerőinek a küzdelem ezen formája a következők szerint módosul: KÉ: -5, TÉ: -5, VÉ: -10, CÉ: -30.',
        },
        {
            id: 'FEGYVER_ISMERET',
            name: 'Fegyverismeret',
            KpAf: 10,
            KpMf: 20,
            description: 'A Fegyverismeret képzetség birtokában a karakter képes megállapitani a kezébe kerülő fegyverekről azok minőségét.',
            Af: 'A karakter jó ismerője a fegyver tipusnak, amit a képzetség elsajátitásakor meghatározott. Ilyet vagy ehhez hasonló fegyvert a kezébe véve, súlyát anyagát megvizsgálva, itéletet tud mondani a fegyver minőségéről, gyakran képes felvilágositást adni készitőjének származásáról, ismertebb mesterember esetén akár még nevéről is.',
            Mf: 'Mindenféle fegyverről tud itéletet mondani, olyanról is amilyen, vagy amelyhez hasonlót még csak nem is látott. Azokról a fegyverekről pedig, amelyek forgatásában képzett, meg tudja állapitani, hogy varázsfegyver vagy sem.',
        },
        {
            id: 'HADVEZETES',
            name: 'Hadvezetés',
            KpAf: 5,
            KpMf: 20,
            description: 'A Hadvezetés képzetség birtokában a karakter képes katonák, fegyelmezett csapatok vezetésére, parancsnoklására. Ismeri a seregek irányitásához szükséges jelrendszert, mitöbb tisztában van a haditaktika alapfogalmaival. A Hadvezetés legnagyobb elméi mindenképpen a Kráni Birodalom intutiven gondolkodó Légiós Procuratorai, vagy az Északi Vörös és Fekete hadurak. Akiktől pedig a karakter a legmagasabb fokon sajátithatja el a Hadvezetés tudományát, azok Ynev szerte a Dreina Lovagrendek, midenekelőtt az Oroszlánsziv Lovagrend, valamint Sigranomoi Egyetem hadvezetés tanszékének profeszorai.',
            Af: 'A karakter valóban csak a taktika alapfogalmait ismeri, igy nem is képes 10-20 főnél nagyobb létszámú csapat sikeres parancsnoklására. Betanitani, kiképezni is csak efféle szabadcsapatokat tud.',
            Mf: 'A karakter akár ezrekből álló csapatokat is sikeresen hadbavezethet. A haditaktika legkifinomultabb szabályaival is tisztában van, e téren jelentős gyakorlati vagy elméleti tapasztalattal rendelkezik. Akárhány fős sereget is képes kiképezni, ha erre elég ideje jut, és akadnak megfelelő segitői.',
        },
        {
            id: 'IRAS_OLVASAS',
            name: 'Irás/Olvasás',
            KpAf: 5,
            KpMf: 25,
            description: 'Egy efféle - túlnyomórészt feudális - világban, amilyen Ynev, korántsem természetes, hogy valaki birja az irás és az olvasás képességét. Sőt, az ilyen kifejezetten tanult, művelt emberek sajátja.',
            Af: 'A karakter tökéletesen ismeri a betűket, gyakorlottan ir, olvas.',
            Mf: 'Kaligráfia. Gondosan rajzolt, szerzetesekhez méltó betűket képes a papirra vetni. A Kalligráfia leggyakoribb alkalmazói a különféle rendek és egyházak szerzetesei, ám igazi mesterei Niaréban élnek, s gyakran bizony jóval prózaibb foglalkozást mondhatnak magukénak. Némelyikük kardművész, hivatalnok, de akad közöttük egyszerő kertész is...',
        },
        {
            id: 'NYELVISMERET',
            name: 'Nyelvismeret',
            KpAf: 3,
            KpMf: 20,
            description: 'A karakter ismer egy álltala tetszés szerint kiválasztott nyelvet a széles Ynevi palettáról. Hogy milyen mértékben teszi ezt magáévá, az attól függ, mennyi Képzetségi Pontot álldozott fel a következők szerint.',
            Af: '1 Kp- ismer néhány szót, ha lassan tagoltan beszélnek hozzá, sejti -de nem tudja bisztosan- miről esik szó. Összefüggően beszélni képtelen. 2 Kp - ha kifejezetten hozzá szólnak, tagolva egyszerű szavakkal, egyszerű szerkezetet használva, megérti. Beszélni csak szakaszosan, körülményessen, gyakran az érthetetlenségig helytelenül, pocsék kiejtéssel képes. Csak közismert szavakból épitkező, egyszerűbb mondatokat használ. 3 Kp -érti, ha beszélnek hozzá, tűrhetően beszél ő is. Ha bir Irás/olvasás képzetséggel, akkor nehézkesen ugyan, de irja és olvassa az adott nyelvet. 4 Kp -mindent ésrt, és választékossan, bár akcentussal beszél. Ha irástudó, az irás, olvasás sem jelent számára gondot. Ha egy kifejezetten ritkán használt szót nem ért, azt pillanatok alatt körül lehet irni számára. 5 Kp - anyanyelvi szinten érti és beszéli, ha irástudó, irja és olvassa is az adott nyelvet. Semilyen akcentus nincs, és néhány egyszerűbb dialektust utánozni is képes.',
            Mf: 'Szónoki fordulatokat használ, beszéde gyönyörködtet, nem jelent számára gondot bármilyen akcentusban ,vagy akár archaizálva, esetleg szaknyelven beszélni. Papok, művelt emberek sajátja ez a képzettség.',
        },
        {
            id: 'OSI_NYELV',
            name: 'Ősi nyelv ismerete',
            KpAf: 10,
            KpMf: 60,
            description: 'Ynev világán a jelen tudománya számára fennmaradt több ősi, mára kihalt nép nyelve is. Ilyen a Kyr, az anur, az aquir, a kheton és az anghmar, jó néhány olyan akad még, amelyeket épp, hogy megfejtettek. Ezek legtöbbjét ma már csak egyes mágusok, papok, bölcsek beszélik, alig olvassák, és szinte senki sem irja. Magukról a népekről és nyelvükről a KM adhat bővebb felvilágositást - a Kalandmester utmutatójának ismeretében. A karakter mikor egy ősi nyelv ismeretének megtanulására adja fejét, meg kell jelölnie, melyiket kivánja elsajátitani. Minden esetben messter segitségét kell igénybe vennie, tekintve, hogy ezen nyelvek belső logikája olyannyira távol esnek a maiakétól, hogy pusztán könyvből lehetetlen azt megérteni.',
            Af: 'Sok szót ismer, de képtelen beszélni, irni, érteni az adott nyelvet. Olvasni akadozva, nem minden szót megértve, de a mondatok értelmét felfogva képes.',
            Mf: 'Folyamatosan irja, olvassa az ősi nyelvet. Érthetően, bár erős akcentussal beszéli, szövegértése sem hagy kivánnivalót maga után.',
        },
        {
            id: 'IDOJOSLAS',
            name: 'Időjóslás',
            KpAf: 3,
            KpMf: 15,
            description: 'Az időjóslás ezer szempontból elengedhetetlen fontosságú Ynev világában is. A tengerészek életének a bisztonság, hadjáratok esetén győzelem, az utazók számára pedig a kényelem bisztositéka. Nem csoda hát, ha sokan igyekeznek kifürkészni szeszélyeit, hogy megjósolhatják az eljövendőt. Ezer módszer létezik erre, egyszerű, tapasztalatokon alapuló találgatástól, egészen a misztikus megoldásokig-mint amilyen a kártyavetés, vagy a madarak belső szerveinek bűbájos megolvasása. Egyet azonban le kell szögeznünk, ezek a módszerek igenis működnek.',
            Af: 'Alapfokú képzetség a karakternek 60 százalékos bisztonsággal képest jóslást késziteni az elkövetkező két nap időjárására nézvést.',
            Mf: 'A Mesterfokon képzet karakter 95 százalékos bisztonsággal készit előrejelzést az elkövetkező 2-7 ( 1K6+1) nap időjárásáról.',
        },
        {
            id: 'TERKEPESZET',
            name: 'Térképészet',
            KpAf: 10,
            KpMf: 17,
            description: '',
            Af: 'Az Alapfokú Térképészet képzetséggel biró karakter ismeri a térképészeti jeleket, könnyen eligazodik bárhol egy térkép segitségével.',
            Mf: 'A Mesterfokon képzett karakter nem csak elolvasni, hanem késziteni is képes a térképeket. Ez korántsem egyszerű feladat, hiszen a sokéves gyakorlaton túl remek térlátás, és mégkülönb szemmértéket igényel.',
        },
        {
            id: 'HERALDIKA',
            name: 'Heraldika',
            KpAf: 5,
            KpMf: 15,
            description: 'A Heraldika tudománza a cimerek, a családi, klán és rendi jelek ismeretét jelenti. Nem lebecsülendően összetett tudomány ez, megvannak a maga törvényszerűségei és szabályai. Milyen alapon milyen figurák szerepelhetnek, milyen szinek párosulhatnak milyenekkel, milyen minták alkalmazhatók...stb.',
            Af: 'A karakter tisztában van mindezen szabályokkal, és bármikor képes tökéletes cimerek megalkotására. Ismeri országa, tájegysége cimereit, közvetlen környezetében, még a legjelenléktelenebbeket is, mitöbb Ynev távoli vidékeinek kiemelkedően fontos cimereit is.',
            Mf: 'Mesterfokú képzetség esetén a karakter előtt nem ismeretlen a távoli tájak cimerei sem, még akkor sem, ha azok nem túl jelentősek. Saját országában még a legapróbb családokét is ismeri, mitöbb, a régmúlt korok cimereire és jeleire is emlékszik.',
        },
        {
            id: 'LEGENDA_ISMERET',
            name: 'Legendaismeret',
            KpAf: 10,
            KpMf: 50,
            description: '',
            Af: 'A Legendaismeret Alapfokon nem több egyszerű lexikális tudásnál. A képzett karakter tisztában van különféle helyekhez, tárgyakhoz, személyekhez kötött legendákkal. Tudása álltalában egy-egy tájegységre vanatkozik.',
            Mf: 'A karakter mérhetetlen számú legendát ismer a világ majd minden tájáról. Soknak az igazságtartalmával is tisztában van. Világosan átlátja a legendák születésének pszihózisát, igy egy sosem halottból is nagy bisztonsággal képes kiszűrni a valóságot elkülönitva a prózai túlzásoktól. A Legendaismeret Mesterfokát általában neves bölcsek birják Ynev szerte.',
        },
        {
            id: 'TORTENELEM_ISMERET',
            name: 'Történelemismeret',
            KpAf: 5,
            KpMf: 20,
            description: 'A Történelemismeret képzetség elsősorban bölcsek, lovagok sajátja. Teljes mértékben lexikális jellegű tudomány, ámbátor mesterei állitják, a múlt ismerete sokban segit a jövő eseményeinek megsejtésében.',
            Af: 'Alapfokon a karakter saját országának, tájegységének történelmét ismeri. Ez kiterjed eseményekre, helyszinekre, jelentős történelmi alakokra egyaránt.',
            Mf: 'A Mesterfokú Történelemismeret felruházza a karaktert azon képességgel, hogy átlássa a történelem eseményei közötti összefüggéseket. Már nem pusztán saját tájegységének, de Ynev egészének történetével tisztában van, tekintettel a hősi múlt történeteire is.',
        },
        {
            id: 'VALLAS_ISMERET',
            name: 'Vallásismeret',
            KpAf: 5,
            KpMf: 25,
            description: '',
            Af: 'Alapvetően a papok képzetsége, de tőlük bárki eltanulhatja. Nagyrészt lexikális jellegű tudás, melynek birtokában a karakter biszton álithatja, ismeri Ynev főbb vallásait, azok Isteneit, történetét, alapvető tanitásait és legnagyobb tanitóit. Számtalan szertartás menetével és céljával is tisztában van.',
            Mf: 'Aki Mesterfokon birja a Vallásismeret képzetséget, az előtt Ynev legapróbb-cseprőbb, netán titkos vallásai sem ismeretlenek. Hallott ezek szertartásairól, és nagy bisztonsággal képes meghatározni azok célját is. A főbb vallásokat szinte teljes alaposággal ismeri, képes idézni azok szent könyveiből, nem jelent számára gondott kevéssé ismert alakjainak felsorolása és jellemzése sem. Saját hitévél és minden azzal kapcsolatos mozzanattal oly fokig tisztában van, hogy a legfelsőbb egyházi körökben sem kerülne zavarba egy teológiai vita kirobbanásakor.',
        },
        {
            id: 'EPITESZET',
            name: 'Épitészet',
            KpAf: 5,
            KpMf: 20,
            description: 'Az Épitészet képzetségben való jártasság nem feltétlenül jelenti az azonos nevű hivatás gyakorlását.',
            Af: 'Az Alapfokon képzett karakter ismeri az Yneven uralkodó főbb épitészeti stilusokat, egy épületről megközelitő pontossággal képes megállapitani, mely században, s melyik kultúra emelte.',
            Mf: 'A Mesterfokon jártas karakter tudománya már nem passziv tudás, ő már képes épületek megtervezésére. Ezek lehetnek házak, de kastélyok, komoly várak nemigen. A Mesterfokú képzetséggel együtt jár, hogy a karakter másoknál nagyobb bisztonsággal képes megsaccolni az esetleges titkos ajtók és folyosók elhelyeszkedését. Ezért a Titkosajtó keresés nevű, szézalékos jártasságban mért képzetségre +20 százalékot kap.',
        },
        {
            id: 'MERGKEVERES',
            name: 'Méregkeverés/semlegesités',
            KpAf: 15,
            KpMf: 60,
            description: 'Sokan nyúlnak ellenfeleik gyengitésére vagy legyilkolásának reményében a mérgezés módszeréhez. Egyesek arra is hajlandók, hogy éveken át tanuljanak, elsajátitsák a méregkeverés tudományát és saját maguk készitsék el a káros matériát. Másokat éppen ellenkezőleg, a segitségnyújtás vágy hajt. Természetesen a képzetség igazi nagymesterei a boszorkányok és boszorkánymesterek, de a nagyobb orrgyilkos klánok mindegyike tart legalább egy méregkeverőt. A mérgezés mestersége sokban támaszkodik az alkimiára, a herbalizmusra és az élettanra, de tanulói e három tudományt, meglehetősen, egyoldalúan tanulják. Ha egy karakter rendelkezik ezekkel a képzetségekkel, jóval könnyebben sajátithatja el a mérgek tudományát ( Mindhárom képzetség 3-3 Képzetség Pontot ad a méregkeverés tanulásához). Ez egyben mutatja azt is, hogy egy herbalista vagy alkimista is állithat elő mérget, de lényegesebben gyengébbet, mint a méregkeverő. A méreg - vagy ellenméreg- előállitásához minden esetben megfelelő alapanyagok, felszerelés és idő kell.',
            Af: 'Az alapfokon képzett karakter képes legfeljebb 5. szintű méreg előállitására, amely azonban ritkán okoz halált vagy ájulást. Kinmérgei legfeljebb 15 Fp vesztést okozhatnak. Alapfokon több komponensű és kontaktméreg nem keverhető. Képes ezenkivül az álltala ismert mérgek ellenszerét is előállitani, ezek +1-3 módositót jelentenek egészségpróba esetén.',
            Mf: 'A Mesterfokon képzett karakter már képes bármilyen méreg előállitására, bár egyes esetben ez igen költséges és egy alkimista vagy herbalista mester közreműködését igényli. A karakter képes bármilyen, álltala ismert méreg ellenszerét előállitani, ami +2-6 módositót jelent egészségpróbánál.',
        },
        {
            id: 'HERBALIZMUS',
            name: 'Herbalizmus',
            KpAf: 5,
            KpMf: 35,
            description: 'Ez a tudomány elsősorban a természeti népek vajákosai és sámánai körében elterjedt, de Ogonomus óta, a világi bölcsek előtt sem ismeretlen. Eredeti célja a gyógyitás volt, de mint oly sok minden mást, at Ember ezt is hamar megtanulta egyébb célok elérése érdekében felhasználni-tegyük hozzá, nem kis sikerrel.A Herbalizmusban járatos karakter alapvetően kétféle hatású szert készithet növényekből: gyógyszert és mérget. Azt, hogy egy adott drog méreg vagy orvosság, inkább felhasználása dönti el, semmint eredete. Ide tartoznak még a halucinogénok-ha úgy tetszik kábitószerek-is. Ezek nem szó szoros értelemben vett mérgek, ám hasonló alkalmazásuk és hatásmechanizmusaik miatt itt tárgyaljuk őket.',
            Af: 'Az Alapfokú képzetséggel képes a karakter legfeljebb 5. szintű betegség gyógyitására alkalmas orvosságok elkészitésére. Ezek álltalában az Egészség-próbára adnak módositót, rendszerint +1-től +9-ig. Képes ezenkivül sebeket és sérüléseket ellátni, melyek igy kétszer olyan gyorsan gyógyulnak, mint egyébbként -vonatkozik Ép és Fp vesztésre egyaránt. Ezeken túlmenően a karakter keverhet mérgeket, melyek beadható mérgek esetén elég erősek lehetnek, bár halált nem okozhatnak, egyébb fajtájú mérgekből, pedig csak gyenge állitható elő. Elkészitheti ezenkivül az álltala ismert mérgek ellenszerét is.',
            Mf: 'Mesterfokú képzetség esetén a karakter bármilyen betegséget gyógyithat, hasonlóan ahhoz ahogy az Alapfokon tette. Az álltala kezelt sebek négyszer gyorsabban gyógyulnak, mint egyébbként. A mérgek közül hatékonnyabbakat készithet, nem csinálhat azonban gáz- és több komponensű mérgeket.',
        },
        {
            id: 'SEBGYOGYITAS',
            name: 'Sebgyógyitás',
            KpAf: 15,
            KpMf: 30,
            description: '',
            Af: 'A sebgyógyitás alapfokon leginkább a seb külső ellátását szolgálja, tehát segit megálitani a vérzést, megakadályozni az elfertőzést vagy a seb ismétlődő felnyillását. Ezért jelentős eredménnyel alkalmazható az Fp-k gyógyitásában. Ép gyógyitására nem alkalmas, ahhoz más jellegű ismeretek is szükségesek. Az Alapfokú képzetség lehetővé teszi a helyes kötés alkalmazását, s használója tisztában van a seb tisztitásának és frtőtlenitésének alapjaival. Ha rendelkezésre áll a szükséges kötszer, a vérzést elállithatja, a sebet bekötözheti. Ha a seben kötés van, a gyógyulás sebessége a kétszeresére nő. Amennyiben a képzetség használója gondozza a sebet, azaz cseréli rajta a kötszert, rendszeresen tisztitja környékét és mindent megtesz a seb gyógyulásáért, a sebesség háromszoros lesz. Ez csak a Fájdalomtűrés pontok gyógyulásakor igaz, az Ép gyógyulásának sebessége nem nő, csak a fertőzésveszély csökken. Az Alapfokú képzetség az Ép-vesztést okozó sebek gyógyitásakor egyötödére csökkenti a fertőzés esélyét. Ez annyit jelent, hogy a fertőzés esélye csak az elveszett Ép-k számának kétszerese lesz, százalékban ( és nem tizszerese!). A törések és repedések, továbbá inszakadások és porc sérülések ellátásához a képzetség csak alapfokú ismeretet ad, s a gyógyulást csak kis mértékben segiti elő.',
            Mf: 'A Mesterfokú képzetség már komoly ismeretanyagot nyújt ezekhez is. Tartalmazza a kenőcsök és gyógynövények alkalmazásának tudományát is. Mesterfokú képzetség esetén mint Fájdalomtűrés pontok, mint az Életerő pontok gyorsabban gyógyulnak. Az Fp sérülések esetében, egyszeri kötözés hatására a gyógyulás háromszoros sebességű lesz, a rendszeres kezelés hatására pedig négyszeres. Az Ép gyógyulásában nagyobb a változás hiszen a Mesterfokú képzetség ebben nyújt igazán fontos segitséget. Kötözéssel, ami sinbe rakást, varrást vagy bármilyen egy alkalommal végrehajtott kezelést értünk - az Ép gyógyulás sebessége kétszeres lesz, az ellfertőzés esélye pedig nullára csökken. A rendszeres kezeléssel a gyógyulás ideje harmadára csökken. A mesterfokú képzetség lehetővé tesz viszonylag bonyolult, szinte műtét értékű beavatkozásokat is, amik az Alapfokú alkalmazással elképzelhetetlenek lennének.',
        },
        {
            id: 'PSZI',
            name: 'Pszi',
            KpAf: 10,
            KpMf: 55,
            description: 'A gondolkodó elme hatalmas erőforrásokat rejt, melynek felhasználásával uralmunk alá hajthatjuk testünk minden porcikáját, befolyásolhatjuk az anyagi világ törvényeit, vagy akár mások tudatát. Pyarronban dolgozták ki a Pszi mindenki számára megtanulható fajtáját, mely segitségével önmagunk és mások felet is korlátozott befolyásra tehetünk szert. A Pyarroni módszer nem alkalmas sem Mana előállitására, és nem is olyan hatékony mint a Slan-út- ám nagy előnye, hogy rövidebb idő alatt elsajátitható, mint az előbbi kettő, és gyakorlatilag bármely kaszt számára elérhető.',
            Af: 'Segitségével saját testünk és akaratunk felett nyerhetünk hatalmat, elménk köré asztrális, vagy mentális pajzsokat épithetünk. Az Alapfok alkalmazói az Általános Diszciplinák mindegyikét végrehajthatják, ám csak saját magukon. Elsajátitásához elegendő 2-3 év, noha szükséges, hogy a tanuló Inteligenciája, Asztrálja és Akaratereje legalább 12 legyen.',
            Mf: 'A Pszi alkalmazás azon foka, amely megengedi, hogy mások tudatára vagy fizikumára is hatást gyakoroljunk. A mesterfok ismerői képesek más Pszi-pajzsokat lebontani, és az Általános Diszciplinákat nem csak magukon, hanem másokon is végrehajthatják. Igaz, ilyenkor a befolyásolni kivánt személy ME dobásra jogosult - asztrális vagy mentális, attól függően, hogy a diszciplina a tudat melyik sikját támadja. A mesterfok eléréséhez szükséges az alapfok ismerete, jó néhány év gyakorlat, és rövid képzés egy Pszi-mestertől ( legalább 5. szintű mesterfokú Pszi használó ).',
        },
        {
            id: 'ALKIMIA',
            name: 'Alkimia',
            KpAf: 10,
            KpMf: 40,
            description: 'Az Alkimia Tudománya elsősorban a Prima Material, más néven a Bölcsek Köve előállitására törekszik. Ez az a principium, melynek segitségével a nemtelen anyag arannyá változtatható. Ámbár Ynev világán a mágusok, de még a varázslók is képessek erre, jóval kevésbé fáradságos módon. Ez mégsem kedvetleniti el az alkimistákat, hiszen ők a tömeges aranycsinálásra törekszenek. Másrészt pedig, az Alkimia mára szerteágazó tudománnyá fejlődött, foglalkozik mindenféle mágikus italok, porok előállitásával, és persze elméleti úton az emberi elme nemesedését is célul tűzi ki.',
            Af: 'A képzetség Alapfokán a karakter egyszerűbb vegyületek, párlatok, őrlemények elkészitésére képes.',
            Mf: 'A karakter bonyolult, nagyhatású anyagokat is készithet.',
        },
        {
            id: 'ELETTAN',
            name: 'Élettan',
            KpAf: 15,
            KpMf: 45,
            description: 'Ynev világi tudományai közül a legtitkosabb az élet forrását kutató Élettan. Tudósait óvatos tisztelet övezi - akár a Bölcsk Kövét kereső alkimistákat - hiszen magát az Élet Principiumát kutatják, a szikrát, ami élővé magasztositja, az amugy nemtelen anygból felépült testet.',
            Af: 'Az Élettan képzetség már alapfokon is elegendő mozgó szobrok ( Gólemek ) megformázásához, hasznos a gyógyitáskor, és elengethetetlen az Átváltotatás varázslat egyszerűbb alkalmazásához, vagy a Mesterfokú képzetség elsajátitásához.',
            Mf: 'Az Élettan Mesterfokú ismerője - ha birja a szükséges mágikus hatalmat - alkothat életképes homonkuluszt, s az átváltoztatás varázslattal szinte bármely varázslást eszközölhet az élőlények szervezetében. Természetesen különleges lények alkotásához, különleges szervek megformázásához az adott teremtmény élettanát is szükséges ismerni, ami nem lebecsülendő akadály, hisyen ki hallott már tudósról, aki - tegyük fel - sárkányokat boncolt ?!',
        },
        {
            id: 'MAGIA_HASZNALAT',
            name: 'Mágia használat',
            KpAf: 15,
            KpMf: 45,
            description: 'A Mágiahasználat képzettség ismerője semmiképp sem számit varászlónak. Tudományának leghasznosabb vonása nem is az, hogy varászlatok létrehozására képes, hanem, hogy ismeri a mágiát, felismeri a varázslatokat, tudja minek mi az ellenszere. Kisenergiájú varázslatai az Elemi Mágiát kivéve nemigen érnek többet egyszerű trükoknél, bűvészmutatványnál. A Mágiahasználat képzetség Mesterfokán 10 Mp-ot képes az elméjébe gyűjteni. Az energiagyűjtést minden nap csak egyszer - pontosabban mindég csak kiadós alvás után, kipihenten - képes.Ez oly mértékben leterheli pszihéjét, hogy a következő huzamosabb alvásig a műveletet megismételni képtelen. A Mágiahasználat képzetséget mágusok dolgozták ki, és Yneven kizárólag két helyen oktatják: a Pyarroni Okkult Tudományok Egyetemén, illetve a Sigranomi Egyetemen. A képzés Alapfokon 3 évbe és 700 aranypénzbe, Mesterfokon 5 évbe és 1000 aranypénzbe kerül.',
            Af: 'A Mágiahasználat képzetség alapfokú ismerője már hatásuk alapján felismerik a varázslatokat, képesek következtetni az alkalmazott mozaikokra - egyszóval tudatában van mindazon elméleti tudásnak, amit a Mágia fejezetben leirtunk - de nem képes használni mágiát.',
            Mf: 'A Mágiaismeret képzetség Mesterfokú elsajátitásával a karakter - bármely kasztú is- képes lesz mozaikmágia használatára. Természetesen csak jelentős megszoritásokkal: az Asztrál és Mentálmágia fejezet alá tartozó varázslatmozaikok alkalmazására egyáltalán nem képes, és a Mana-pontjainak száma sem növekszik TSZ- lépéskor.',
        },
        {
            id: 'DEMONOLOGIA',
            name: 'Demonológia',
            KpAf: 20,
            KpMf: 55,
            description: 'A Démonológia titkos képzetség. Pyarron vagy Doran könyvtáraiban akad csak olyan fóliáns, amely titkairól regél, s pesze a távoli Kránban. Toron egyes rendjei avatják be tudományába a tagjaikat, s a Déli Kolostorokban bukkanhat efféle tudás nyomára a kiválasztott kutató.',
            Af: 'A Démonológiában alapfokon képzett karakter közel száz fajta közdémon nevét, gondolati sémáját és képességeit ismeri. Ugyanigy tisztában van a legtöbb démonúr és démonherceg tudományával.',
            Mf: 'Mesterfokú képzetség esetén ismeri a Démonok mentális testének felépitését, igy Alexandrit használata nélkül is képes rájuk Mentális Mágiával hatni.',
        },
        {
            id: 'RUNAMAGIA',
            name: 'Rúnamágia',
            KpAf: 18,
            KpMf: 45,
            description: 'A Rúnamágia - ha szigorúan nézzük- a Jelmágia azon alfejezete, amely a különböző rúna-rajzolatok mágikus tulajdonságait tanulmányozza. Elsődleges fontossággal bir a Jelmágián alapuló varázstárgyak készitésében, ahol a mágikus hatásokat a rúnák tárolják.',
            Af: 'A Rúnamágiában alapfokon képzett karakter képes szabályosan felolvasni a mások álltal leirt rúnákat. Tudománya elegendő arra, hogy tekercseket olvasson fel, s életrehivja a beléjük fogalmazott varázslatokat, ám nem teszi alkalmassá egyetlen rúna leirására sem.',
            Mf: 'A rána leirásának tudománya. Mivel számtalan mágikus alapismeretet és jelentős mágikus hatalmat követel, még a nagy varázslóiskolákban is csak keveseknek oktatják ( 6. TSZ fölött ). Ismeretében a karakter varázstárgyakat alkothat.',
        },
        {
            id: 'DRAGAKO_MAGIA',
            name: 'Drágakő mágia',
            KpAf: 0,
            KpMf: 52,
            description: 'Titkos képzetség, csak a legnagyobb varázslóiskolákban a kiválasztott ( 9. TSZ felett ) tanitványoknak oktatják.',
            Af: 'Alapfokú alkalmazása nem ismeretes.',
            Mf: 'Mesterfokon varázstárgyak és drágakő esszenciák készitésére alkalmas.',
        },
        {
            id: 'IDOMITAS',
            name: 'Idomitás',
            KpAf: 8,
            KpMf: 20,
            description: 'Ynev világában nagycsomó olyan állat akad, amely betanitható az ember szolgálatára. Ezeknek csak jelentős, de nem kizárólagos hányadát jelentik a lovak, ökrök, kutyák. Hiszen vannak akik farkasokat, madarakat édeskednek magukhoz. Az Idomitás képzetség felruházza a karaktert annak képességével, állatokat tanitson be különféle feladatok végrehajtására.',
            Af: 'Alapfokú képzettség esetén ezek csak hétköznapi, az adott állatfajtól megszokott cselekedetek lehetnek. A ló idomitható lovaglásra, a kutya alapvető engedelmességre.',
            Mf: 'A Mesterfokon idomitó karakter állatait már mindenféle különleges kunsztok végrehajtására is képes betanitani. Remek példája ennek az, ami a vándorcirkuszban történik.',
        },
        {
            id: 'ETIKETT',
            name: 'Etikett',
            KpAf: 8,
            KpMf: 15,
            description: 'Az Etikett az udvarias, társadalmi követelményeknek megfelelő viselkedést jelenti. Azt a tudományt melynek birtokában a karakter tudja, kit miként kell köszöntenie, milyen módon kell meghajolnia, bizonyos helyzetekben hogyan kell viselkednie. Képes cirkalmassan fogalmazni, és megtalálja a helyét úri társaságban. Minden nép, tájegység, ország, birodalom kialakitja saját illemrendszerét, igy a karakternek a képzetség tanulásakor meg kell határoznia, hogy mely vidék etiketjét kivánja elsajátitani. A legismertebbek a shadoni, a pyarroni, erigowi, toroni és abasziszi etikett.',
            Af: 'A karakter járatos a nemesi és főnemesi etikettben. Ismeri a réteg szokásait, az udvariassági fordulatokat, képes burkoltan közölni gondolatait, illetve illedelmesen vérig sérteni valakit.',
            Mf: 'A karakter a fent leirtak mindegyikében még az udvarnál is megállja helyét.',
        },
        {
            id: 'NYOMOLVASAS',
            name: 'Nyomolvasás/eltüntetés',
            KpAf: 10,
            KpMf: 45,
            description: 'A Nyomolvasásban járatos karakter képes követni mások nyomait, pusztán a nyomokból kiolvassa, hányan jártak arra őelőtte és nagyából mi történt a helyszinen. Természetesen az eső, és a köves talaj megneheziti a nyomolvasást.',
            Af: 'Terptől függően 1-6 nap távlatából képes olvasni a nyomokat. Azonos szintű képzetséggel rendelkeznyomolvasó elől el tudja tüntetni nyomait.',
            Mf: 'Tereptől függően akár 1 hónap távlatából is sikerülhet kiolvasnia a nyomokból a kivánt információt. Nyomait teljesen el tudja tüntetni.',
        },
        {
            id: 'ERDOJARAS',
            name: 'Erdőjárás',
            KpAf: 5,
            KpMf: 14,
            description: 'Az Erdőjárás képzetség a természet, különös tekintettel az erdő ismeretét jelenti. Olyan tudás amelynek segitségével a karakter eligazodik a leghatalmasabb rengetegben is, ismeri a ragadozókat, a zsákmányállatokat, tudja mitől kell tartani és mitől nem. Megleli az ehető bogyókat és gyökereket, mint ahogy felismeri a mérgezőket is. Ismeri a vadak szokásait, a növények tipusait.',
            Af: 'A karakter éveket élt erdőben',
            Mf: 'Leginkább elfek, erdőben élő Arel papok vagy évtizedekig erdőben élő erdőjáró.',
        },
        {
            id: 'VADASZAT',
            name: 'Vadászat/halászat',
            KpAf: 8,
            KpMf: 15,
            description: 'A Vadászat/Halászat képzetség azzal a képességgel ruházza fel birtokosát, hogy könnyen, fáradság nélkül jusson élelemhez erdőn, mezőn, tavak, tengerek környékén.',
            Af: 'A képzett karakter ismeri az állatok, halak szokásait, tudja mire, milyen körülmények között, milyen csalétekkel és milyen napszakban érdemes vadászni, illetve halászni. Tudománya saját és mások tapasztalatán alapul, netán bizonyos népek nemzedéről nemzedékre öröklődő hagyományain.',
            Mf: 'A Mesterfokon képzett karakter, ha vadak nyomába szegődik, mintegy ösztönösen, belső intuició által vezetve talál rájuk. Netán olyan misztikus képességekkel is rendelkezik, mely segitségével magához csalogatja a későbbi zsákmányt. A Mesterfokú Vadászat/Halászat igazi mesterei az elfek lehetnének, ha különleges képességeiket hajlandóak lennének efféle általuk megvetett cél szolgálatába állitani.',
        },
        {
            id: 'LOVAGLAS',
            name: 'Lovaglás',
            KpAf: 1,
            KpMf: 15,
            description: 'A Lovaglás képzettség elengethetetlenül fontos minden kalandozó életmódott folytató karakter számára. De nem nélkülözhetik a katonák, harcosok, lovagok sem - sőt! A ló Ynev legelsődlegesebb közlekedési eszköze. Igy vagy ugy de majdnem minden nem paraszti származású ember elsajátitja a Lovaglást.',
            Af: 'Az alapfokon képzett karakter képes megülni a lovat, irányitani, akarata szolgálatába kényszeriteni - feltéve, ha a hátas idomitott. Nem jelent számára gondott a vágta, de az ugratás sem. Kijelenthetjük, már az alapfokú képzetség is tökéletes lovastudományt jelent. Ahoz azonban nem elegendő, hogy a karakter kihasználhassa a lovas harcmodorból származó előnyöket.',
            Mf: 'A Mesterfokon képzett lovas tökéletes uralmat tart az álltala megült hátas felett. Gyakorlotsága révén nem igényel tőle különösebb figyelmet az állat irányitása, ezt ösztönösen teszi. Igy képes ugy harcolni lovaglás közben, hogy teljesen kihasználja az ebből eredő előnyöket.',
        },
        {
            id: 'KOCSIHAJTAS',
            name: 'Kocsihajtás',
            KpAf: 2,
            KpMf: 15,
            description: '',
            Af: 'Az alapfokon képzett karakter gond nélkül hajt egyes- vagy kettesfogatot, tudja miként kell ki- és befogni a lovakat, ismeri a különböző kocsik, hintók teherbirását.',
            Mf: 'Mesterfokú képzetség esetén a karakter elboldogul a négyes- vagy akár a hatosfogattal is, mitöbb, harcikocsi hajtásban is megtalálja a helyét.',
        },
        {
            id: 'USZAS',
            name: 'Úszás',
            KpAf: 2,
            KpMf: 10,
            description: 'Az úszni tudás korántsem hétköznapi ismeret Ynev világán. Leginkább csak a tengerek, tavak, folyók prtján élők birják. Egyes hadseregekben alacsony szinten megkövetelik a katonáktól, de ez nem álltalános. A különféle Harcos kasztok tagjai esetében azonban már mindennapos tudománynak számit.',
            Af: 'A karakter jól úszik. Ha kevés súly huzza, akár egy óra hosszatt is képes lebegni a felszinen. Könnyedén átuszik egy közepesen erős sodrású folyót.',
            Mf: 'Képes teljes felszerelését a viz felszinén tartani, könnyedén úszik órákig is, ha úgy hozza a sors. Átússza a legsebesebb sodrású folyót is. FIGYELEM! fémvértezetben még mesterfokon sem lehet úszni.',
        },
        {
            id: 'SZEXUALIS_KULTURA',
            name: 'Szexuális kultúra',
            KpAf: 5,
            KpMf: 30,
            description: 'A Szexuális kultúra képzetség valójában a szeretkezés művészetét jelenti. Ynev világán több kultúrkör is kialakitotta a maga, a többitől differens tudományát az érintett területen. A karakter ezek közül válogathat, mikor a képzetség elsajátitására készül.',
            Af: 'A karakter kultúráltan szeretkezik, érzékeli és képes teljesiteni partnere kivánságait.',
            Mf: 'A karakter szeretkezés közben a legmagasabb kéjben részesiti, szinte megörjiti partnerét. Mindezek eredményeként, álltalában, érzelmileg is magához láncolja a másikat.',
        },
        {
            id: 'HAJOZAS',
            name: 'Hajózás',
            KpAf: 15,
            KpMf: 40,
            description: 'Ynev világának beltengerein, tavain és folyamain jelentős hajózás folyik. Használnak tutajokat, gályákat, vitorlás hajókat, de még acélból épitett mágikus hajtású vizijárműveket is. A három legjelentősebb vizi-kereskedelmi útvonal: az úgynevezett Bibor-út a Quiron-tengeren, mely Toronból Abasziszba vezet, a szintén ugyanezen tengert átszelő a Tiadlan kikötőiből a Városállamokba vezető útvonal, valamint maga az egész Gályák Tengere.',
            Af: 'A Hajózásban alapfokon képzett karakter képes elirányitani folyami, vagy kisebb tavi hajókat, és megálja helyét matrózként a tengeri hajókon.',
            Mf: 'Mesterfok képzettség esetén képes tengerjáró hajók parancsnoklására, sőt partmenti, óceáni fuvar lebonyolitására is. Azonban Mesterfok esetén már meg kell határozni azt a hajótipust, melyre ugymond szakosodik. Választhat egy vagy több árbócos vitorláshajót, Galeaszt, vagy gályát, netán ezen csoportok bármelyikébe tartozó, de külön kategóriának számitó hadihajót.',
        },
        {
            id: 'ENEKLES',
            name: 'Éneklés/zenélés',
            KpAf: 5,
            KpMf: 30,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'TANC',
            name: 'Tánc',
            KpAf: 5,
            KpMf: 30,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'HANGUTANZAS',
            name: 'Hangutánzás',
            KpAf: 3,
            KpMf: 16,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'ERTEKBECSLES',
            name: 'Értékbecslés',
            KpAf: 5,
            KpMf: 11,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'CSAPDAALLITAS',
            name: 'Csabdaállitás',
            KpAf: 10,
            KpMf: 20,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'CSOMOZAS',
            name: 'Csomózás',
            KpAf: 7,
            KpMf: 24,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'ZSONGLORKODES',
            name: 'Zsonglőrködés',
            KpAf: 3,
            KpMf: 10,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'FUTAS',
            name: 'Futás',
            KpAf: 9,
            KpMf: 24,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'SZAKMA',
            name: 'Szakma',
            KpAf: 2,
            KpMf: 15,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'KOCSMAI_VEREKEDES',
            name: 'Kocsmai verekedés',
            KpAf: 3,
            KpMf: 15,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'HATBASZURAS',
            name: 'Hátbaszúrás',
            KpAf: 10,
            KpMf: 25,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'HAMISKARTYA',
            name: 'Hamiskártya',
            KpAf: 10,
            KpMf: 20,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'KOTELEKBOL_SZABADULAS',
            name: 'Kötelékből szabadulás',
            KpAf: 8,
            KpMf: 16,
            description: '',
            Af: '',
            Mf: '',
        },
        {
            id: 'ALCAZAS',
            name: 'Álcázás/álruha',
            KpAf: 12,
            KpMf: 24,
            description: '',
            Af: '',
            Mf: '',
        },
    ],
    skillsPrecent: [
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
        {
            name: '',
            description: '',
        },
    ],
};
const getters = {
    skills: () => {
        return state.skills;
    },
    skill: (state) => (id) => {
        return state.skills.find(s => s.id === id);
    },
    skillsPrecent: () => {
        return state.skillsPrecent;
    },
    skillPrecent: (state) => (id) => {
        return state.skillsPrecent.find(p => p.id === id);
    },
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}