/**-------------------------------------------
 * 
 * STORE FOR MAGUS Skills
 * 
 * -------------------------------------------
 */
 const state = {
    skills: [
        {
            id: 'OKOLHARC',
            name: 'Ökölharc',
            KpAf: 3,
            KpMf: 15,
            description: 'A karakter gyakorlott kétkezi verekedő. Nem jön zavarba, ha fegyverét valamely okból nem használhatja ( esetleg nincs is nála ). Az Ökölharc - bár fegyver nélkül űzik - nem hasonlít a harcművészetekre, nem is nyukszik hasonló alapokon. Inkább egyfajta Erőn és Ügyességen alapuló, művészetnek semmiképp nem nevezhető harcmodor. Az a karakter, aki ismeri az ökölharc fortélyait, nem szenvedi el a Képzetlen Fegyverforgatásból - ezesetben a puszta kéz képzetlen használatából eredő hátrányokat, és a küzdelemben mindkét kezét használhatja ( kétszer támad ). Az Alapfokot és a Mesterfokot kizárólag a puszta ököl sebzésének mértéke különbözteti meg egymástól.',
            Af: '1-2 Sp',
            Mf: '1-6 Sp',
        },
        {
            id: 'BIRKOZAS',
            name: 'Birkózás',
            KpAf: 8,
            KpMf: 15,
            description: 'A képzetség rokon az Ökölharccal, ám a birkózó kezét nem öklözésre, hanem ellenfelének lefogására, leszorítására használja. Ahhoz, hogy ezt megtehesse, természetesen sikeres Támadó Dobást kell tennie. Sebzés nincs, ellenben az álldozat körökre mozgásképtelenné tehető, mialatt támadni sem képes. Ha a képzetség alkalmazója egyszer már megragadta ellenfelét, és erősebb is nála, annak kevés az esélye a szoritásból szabadulni. A birkózó minden körben köteles Erőpróbát tenni, s az álldozatnak csak akkor nyílik egyáltalán lehetősége a szabadulásra, ha elvéti. Még ilyenkor sincs veszve semmi, mert a lefogott csak akkor menekülhet, ha az ő Erőpróbája ellenben sikeres. Ha az álldozat ereje nagyobb a lefogónál, ő tehet minden körbem Erőpróbát, s ha sikerrel jár, nyomban ki is bontakozik a marasztaló karokból. Ha a támadás, amivel a birkózó megragadja áldozatát túlütés, a lefogott személy a szorításban nagy esélyel elveszti eszméletét. Ez akkor következik be, ha a birkózó, közvetlen a túlütést követő körben, sikeres Erőpróbát tesz.',
            Af: 'Az alapfokon képzett karakter, ha fegyveres ellenféllel birkózik, minden támadását -15-tel dobja.',
            Mf: 'A Mesterfokon képzett birkózó fegyveres ellenfél ellenében sem kerül hátrányba.',
        },
        {
            id: 'FEGYVER_HASZNALAT',
            name: 'Fegyverhasználat',
            KpAf: 3,
            KpMf: 30,
            description: 'A Fegyverhasználat a harcos ( és a harccal bármilyen módon foglalkozó ) kasztok tagjai számára talán a legfontosabb képzetség. Ugyanis mindazok, akik nem képzettek egy adott fegyver forgatásában, ha harcolni szándékoznak vele, csak komoly hátránnyal tehetik. Ezt nevezzük Képzetlen Fegyverforgatásnak, ami a következő hátrányokkal jár: KÉ: -10, TÉ: -25, VÉ: -20 Ha valaki képzetlenül nyúl célzó fegyverhez, 30-cal csökken CÉ-je. A játékos amikor a fegyverhasználat képzetséget kiválasztja, értelemszerűen, meg kell határoznia, hogy melyik fegyver forgatásában kívánja járatossá tenni karakterét.',
            Af: 'A karakter a kiválasztott fegyver forgatásában képzett, azt használva nem sújtják a fent emlitett Képzetlen Fegyverforgatásból származó hátrányok.',
            Mf: 'Képes mesterien forgatni az adott fegyvert, ezért amikor azzal harcol, a következő előnyökben részesül: KÉ: +5, TÉ: +10, VÉ: +10, CÉ: +10',
        },
        {
            id: 'PAJZS_HASZNALAT',
            name: 'Pajzshasználat',
            KpAf: 5,
            KpMf: 30,
            description: 'A Pajzshasználatot oktató legnevesebb iskolák: az Oroszlánszív Lovagrend, a shadoni Isten Kardja Lovagrend, míg az élezett peremű pajzsok forgatásában a gorwicki Marico con Rabora Lovagrend és egyes kráni lovagrendek a legjáratosabbak.',
            Af: 'A karakter képes a küzdelemben pajzsot használni. Védekezni vele ( a pajzs Vé-je hozzáadódik a karakter Védő Értékéhez ) és akár még támadni is. Pajzsal való támadáskor, sikeres Támadó Dobás esetén, pajzsával fellöki az ellenfelét, miközben még másik, fegyveres karjával is támadhat. Ám ha támad a pajzsal, akkor abban a harci körben a védekezésre nem használhatja ( így annak Vé-je nem adódik hozzá a Védő Értékéhez ).',
            Mf: 'A pajzsal mesteri módon támad, és ha annak pereme élezett, akkor vágni is képes vele. Emellett másik kezét is használhatja - és egyik támadásának TÉ-jére sincsen mínusz. Mesterfokon a karakter egyazon körben támadhat és védekezhet is pajzsával, és a pajzs mozgásgátló tényezője megszűnik ( MGT )',
        },
        {
            id: 'FEGYVER_DOBAS',
            name: 'Fegyverdobás',
            KpAf: 4,
            KpMf: 40,
            description: 'Harci helyzetben gyakran előfordul, hogy a karakter valamely okból hajítani szeretné fegyverét. Az esetek nagy többségében ez eleve hajítófegyver ( tőr, dárda, bárd ), de olykor egyébb kézifegyver is lehet. A karakter mikor a Fegyverdobás képzetség elsajátításához kezd, köteles meghatározni a fegyver tipusát, amelynek hajításában járatossá kíván válni. A képesség tanulása főként untalan gyakorlásból áll. A tőr hajításának avatatlan nagymesterei a tolvajklánok, a dárdavetésben a különböző hegyi népek vadászai, mig a lovagikard célbadobásában a Ramort városállam Deva Morrola rendjének lovagjai jeleskednek messze mások előtt. Dobni bármilyen egykezes fegyvert lehet - akár a másfélkezes kardot is, a dobás sikerességének eldöntésében minden esetben Támadó és nem Célzó Dobást kell tenni.',
            Af: 'A karakternek nincs mínusza a választott fegyver dobásakor',
            Mf: 'A választott fegyvert a karakter +10 TÉ-vel dobja.',
        },
        {
            id: 'FEGYVERTORES',
            name: 'Fegyvertörés',
            KpAf: 5,
            KpMf: 20,
            description: 'Harc során sokan alkalmazzák a Fegyvertörés képzetséget. A különleges tudomány arra irányul, hogy küzdelem közbe a karakter fegyverével eltörje - használhatatlanná tegye- ellenfele fegyverét. Erre képzet karakter is csak akkor képes, ha szándékát előre - a harci kör elején - bejelenti, majd sikeres Támadódobást tesz. Fegyvertörés csak akkor lehetséges, ha ezt a két összecsapó fegyver tipusa elképzelhetővé teszi - ennek eldöntése a KM feladata.',
            Af: 'A Támadó Dobás 25-tel csökkentett TÉ-vel',
            Mf: 'TÉ mínusz nélkül.',
        },
        {
            id: 'LEFEGYVERZES',
            name: 'Lefegyverzés',
            KpAf: 7,
            KpMf: 18,
            description: 'A különleges képzetség segítségével a karakter képes arra, hogy küzdelem közben lefegyverezze ellenfelét. Ezt teheti fegyverrel, de akár puszta kézzel is ( a képzetség elsajátításánál kell eldönteni ). Lefegyverző szándékát előre - a harci kör elején - kell bejelentenie, majd sikeres Támadó Dobást tennie.',
            Af: '25-tel csökkentett TÉ-vel.',
            Mf: 'TÉ mínusz nélkül.',
        },
        {
            id: 'PANCEL_VISELET',
            name: 'Nehézvért viselet',
            KpAf: 3,
            KpMf: 27,
            description: 'A Nehézvért viselet képzetség birtokosa képes küzdelmet folytatni teljesvértezetben és félvértezetben is. Az a karakter aki még alapfokú képzetséggel sem bír, ha nehézvértet ölt, minden fegyverrel úgy harcol mintha annak forgatásában járatlan lenne ( Képzetlen fegyverforgatás: KÉ: -10, TÉ: -25 VÉ: -20 ). A Nehézvért viselet igazi nagymesterei a lovagok és paplovagok, hiszen ők nem kizárólag harci helyzetben, csatákban viselik páncéljukat, hanem szinte szüntelen, gyakran még díszruhaként is.',
            Af: 'Az alapfokon képzett karakter nem szenvedi el az említett minuszokat, de gyorsasága és ügyessége továbbra is annyival csökken, amennyi a viselt vért Mozgásgátló Tényezője ( MGT ).',
            Mf: 'Mesterfokú képzetség esetén már a viselt vért MGT-je sem érvényesül - azaz nem vonódik le a karakter gyorsaságából és ügyességéből.',
        },
        {
            id: 'KETKEZES_HARC',
            name: 'Kétkezes harc',
            KpAf: 15,
            KpMf: 25,
            description: 'Kétkezes harcot folytat az, aki mindkét kezében fegyvert tart. Abban az esetben, ha mindkét fegyvert támadásra használja, minden harci körben kétszer támad: először egyik majd másik kezével. Ha felváltva használja őket, meghatározhatja melyikkel védekezik, és melyikkel támad. Ha a karakter még Alapfokú képzetséggel sem bír, mégis kétkezes harcot folytat, akkor jobbik kezében tartott fegyverrel a következő minuszokkal harcol: KÉ: -5, TÉ: -10, VÉ: -10, míg rosszabbik kezét a Képzetlen Fegyverforgatásból származó mínuszok sújtják.',
            Af: 'Alapfokú képzetség esetén a jobbik kezében tartott fegyverre semmiféle mínusz nincsen, mig a rosszabbik kézben lévőre, a következő megszorítások érvényesek: KÉ: -2, TÉ: -5, VÉ: -5',
            Mf: 'Mesterfokú képzetség esetén a karakter mindkét kezét mínuszok nélkül használhatja a küzdelemben.',
        },
        {
            id: 'VAKHARC',
            name: 'Vakharc',
            KpAf: 10,
            KpMf: 30,
            description: 'Mindazok, akik - vagy mert vakok, vagy bármely más okból- nem látják ellenfelüket, nem érzékelik pontosan a környezetüket jelentős hátránnyal képesek csak harcolni: KÉ: -20, TÉ: -60, VÉ: -70, CÉ: -150. Félhomályban, vagyis alkonyi sötétségben, gyertyák gyér fényével tessék-lássék átjárt helységben nehezebb harcolni, és csak komoly hátrányokkal lehetséges pontosan célozni. Ugyanezen szabály vonatkozik mindazokra, akik korlátozott látási viszonyok között, netán elhomályosult látással kényszerülnek küzdeni. Ennek oka lehet mágia, könny a szemben, pszi stb. Ez a módosító súlytja azokat is, akik ugyan környezetüket látják, viszont ellenfelük valamilyen oknál fogva láthatatlan: KÉ: -15, TÉ: -30, VÉ: -35, CÉ: -70.',
            Af: 'Hangok és neszek alapján tájékozódva, sőt némileg a megérzéseire hagyatkozva is képes harcolni. Ekkor: KÉ: -10, TÉ: -15, VÉ: -20, CÉ: -60.',
            Mf: 'A karakter már belső megérzései alapján harcol. Nem látására, vagy hallására hagytkozik, így akár le is hunyhatja a szemét, harcértéke nem fog csökkeni. A Vakharc Mesterfokát eredetileg harcművészek dolgozták ki, de ma már mindenki számára megtanulható. A leghíresebb iskola ahol oktatják, a tiadlani Shai-tra kardművész-iskola, ahol 250 aranypénz fizetség ellenében 2 esztendő alatt bárki elsajátíthatja ezt a különös tudományt. A Vakharc Mesterfokú ismerőinek a küzdelem ezen formája a következők szerint módosul: KÉ: -5, TÉ: -5, VÉ: -10, CÉ: -30.',
        },
        {
            id: 'FEGYVER_ISMERET',
            name: 'Fegyverismeret',
            KpAf: 10,
            KpMf: 20,
            description: 'A Fegyverismeret képzetség birtokában a karakter képes megállapítani a kezébe kerülő fegyverekről azok minőségét.',
            Af: 'A karakter jó ismerője a fegyvertipusnak, amit a képzetség elsajátításakor meghatározott. Ilyet vagy ehhez hasonló fegyvert a kezébe véve, súlyát anyagát megvizsgálva, ítéletet tud mondani a fegyver minőségéről, gyakran képes felvilágosítást adni készítőjének származásáról, ismertebb mesterember esetén akár még nevéről is.',
            Mf: 'Mindenféle fegyverről tud ítéletet mondani, olyanról is amilyen, vagy amelyhez hasonlót még csak nem is látott. Azokról a fegyverekről pedig, amelyek forgatásában képzett, meg tudja állapítani, hogy varázsfegyver vagy sem.',
        },
        {
            id: 'HADVEZETES',
            name: 'Hadvezetés',
            KpAf: 5,
            KpMf: 20,
            description: 'A Hadvezetés képzetség birtokában a karakter képes katonák, fegyelmezett csapatok vezetésére, parancsnoklására. Ismeri a seregek irányításához szükséges jelrendszert, mitöbb tisztában van a haditaktika alapfogalmaival. A Hadvezetés legnagyobb elméi mindenképpen a Kráni Birodalom intutiven gondolkodó Légiós Procuratorai, vagy az Északi Vörös és Fekete hadurak. Akiktől pedig a karakter a legmagasabb fokon sajátíthatja el a Hadvezetés tudományát, azok Ynev szerte a Dreina Lovagrendek, midenekelőtt az Oroszlánszív Lovagrend, valamint Sigranomoi Egyetem hadvezetés tanszékének profeszorai.',
            Af: 'A karakter valóban csak a taktika alapfogalmait ismeri, igy nem is képes 10-20 főnél nagyobb létszámú csapat sikeres parancsnoklására. Betanítani, kiképezni is csak efféle szabadcsapatokat tud.',
            Mf: 'A karakter akár ezrekből álló csapatokat is sikeresen hadba vezethet. A haditaktika legkifinomultabb szabályaival is tisztában van, e téren jelentős gyakorlati vagy elméleti tapasztalattal rendelkezik. Akárhány fős sereget is képes kiképezni, ha erre elég ideje jut, és akadnak megfelelő segítői.',
        },
        {
            id: 'IRAS_OLVASAS',
            name: 'Írás/Olvasás',
            KpAf: 5,
            KpMf: 25,
            description: 'Egy efféle - túlnyomórészt feudális - világban, amilyen Ynev, korántsem természetes, hogy valaki bírja az írás és az olvasás képességét. Sőt, az ilyen kifejezetten tanult, művelt emberek sajátja.',
            Af: 'A karakter tökéletesen ismeri a betűket, gyakorlottan ír, olvas.',
            Mf: 'Kaligráfia. Gondosan rajzolt, szerzetesekhez méltó betűket képes a papirra vetni. A Kalligráfia leggyakoribb alkalmazói a különféle rendek és egyházak szerzetesei, ám igazi mesterei Niaréban élnek, s gyakran bizony jóval prózaibb foglalkozást mondhatnak magukénak. Némelyikük kardművész, hivatalnok, de akad közöttük egyszerő kertész is...',
        },
        {
            id: 'NYELVISMERET',
            name: 'Nyelvismeret',
            KpAf: 3,
            KpMf: 20,
            description: 'A karakter ismer egy álltala tetszés szerint kiválasztott nyelvet a széles Ynevi palettáról. Hogy milyen mértékben teszi ezt magáévá, az attól függ, mennyi Képzetségi Pontot álldozott fel a következők szerint.',
            Af: '1 Kp- ismer néhány szót, ha lassan tagoltan beszélnek hozzá, sejti - de nem tudja bisztosan - miről esik szó. Összefüggően beszélni képtelen. 2 Kp - ha kifejezetten hozzá szólnak, tagolva egyszerű szavakkal, egyszerű szerkezetet használva, megérti. Beszélni csak szakaszosan, körülményessen, gyakran az érthetetlenségig helytelenül, pocsék kiejtéssel képes. Csak közismert szavakból épitkező, egyszerűbb mondatokat használ. 3 Kp -érti, ha beszélnek hozzá, tűrhetően beszél ő is. Ha bir Irás/olvasás képzetséggel, akkor nehézkesen ugyan, de írja és olvassa az adott nyelvet. 4 Kp -mindent ért, és választékossan, bár akcentussal beszél. Ha írástudó, az írás, olvasás sem jelent számára gondot. Ha egy kifejezetten ritkán használt szót nem ért, azt pillanatok alatt körül lehet írni számára. 5 Kp - anyanyelvi szinten érti és beszéli, ha írástudó, írja és olvassa is az adott nyelvet. Semilyen akcentusa nincs, és néhány egyszerűbb dialektust utánozni is képes.',
            Mf: 'Szónoki fordulatokat használ, beszéde gyönyörködtet, nem jelent számára gondot bármilyen akcentusban ,vagy akár archaizálva, esetleg szaknyelven beszélni. Papok, művelt emberek sajátja ez a képzettség.',
        },
        {
            id: 'OSI_NYELV',
            name: 'Ősi nyelv ismerete',
            KpAf: 10,
            KpMf: 60,
            description: 'Ynev világán a jelen tudománya számára fennmaradt több ősi, mára kihalt nép nyelve is. Ilyen a Kyr, az anur, az aquir, a kheton és az anghmar, jó néhány olyan akad még, amelyeket épp, hogy megfejtettek. Ezek legtöbbjét ma már csak egyes mágusok, papok, bölcsek beszélik, alig olvassák, és szinte senki sem írja. Magukról a népekről és nyelvükről a KM adhat bővebb felvilágosítást - a Kalandmester útmutatójának ismeretében. A karakter mikor egy ősi nyelv ismeretének megtanulására adja fejét, meg kell jelölnie, melyiket kivánja elsajátítani. Minden esetben mester segítségét kell igénybe vennie, tekintve, hogy ezen nyelvek belső logikája olyannyira távol esnek a maiakétól, hogy pusztán könyvből lehetetlen azt megérteni.',
            Af: 'Sok szót ismer, de képtelen beszélni, írni, érteni az adott nyelvet. Olvasni akadozva, nem minden szót megértve, de a mondatok értelmét felfogva képes.',
            Mf: 'Folyamatosan írja, olvassa az ősi nyelvet. Érthetően, bár erős akcentussal beszéli, szövegértése sem hagy kívánnivalót maga után.',
        },
        {
            id: 'IDOJOSLAS',
            name: 'Időjóslás',
            KpAf: 3,
            KpMf: 15,
            description: 'Az időjóslás ezer szempontból elengedhetetlen fontosságú Ynev világában is. A tengerészek életének a bisztonság, hadjáratok esetén győzelem, az utazók számára pedig a kényelem bisztosítéka. Nem csoda hát, ha sokan igyekeznek kifürkészni szeszélyeit, hogy megjósolhatják az eljövendőt. Ezer módszer létezik erre, egyszerű, tapasztalatokon alapuló találgatástól, egészen a misztikus megoldásokig - mint amilyen a kártyavetés, vagy a madarak belső szerveinek bűbájos megolvasása. Egyet azonban le kell szögeznünk, ezek a módszerek igenis működnek.',
            Af: 'Alapfokú képzetség a karakternek 60 százalékos bisztonsággal képest jóslást készíteni az elkövetkező két nap időjárására nézvést.',
            Mf: 'A Mesterfokon képzet karakter 95 százalékos bisztonsággal készít előrejelzést az elkövetkező 2-7 ( 1K6+1) nap időjárásáról.',
        },
        {
            id: 'TERKEPESZET',
            name: 'Térképészet',
            KpAf: 10,
            KpMf: 17,
            description: '',
            Af: 'Az Alapfokú Térképészet képzetséggel bíró karakter ismeri a térképészeti jeleket, könnyen eligazodik bárhol egy térkép segítségével.',
            Mf: 'A Mesterfokon képzett karakter nem csak elolvasni, hanem készíteni is képes a térképeket. Ez korántsem egyszerű feladat, hiszen a sokéves gyakorlaton túl remek térlátás, és mégkülönb szemmértéket igényel.',
        },
        {
            id: 'HERALDIKA',
            name: 'Heraldika',
            KpAf: 5,
            KpMf: 15,
            description: 'A Heraldika tudománya a címerek, a családi, klán és rendi jelek ismeretét jelenti. Nem lebecsülendően összetett tudomány ez, megvannak a maga törvényszerűségei és szabályai. Milyen alapon milyen figurák szerepelhetnek, milyen szinek párosulhatnak milyenekkel, milyen minták alkalmazhatók...stb.',
            Af: 'A karakter tisztában van mindezen szabályokkal, és bármikor képes tökéletes cimerek megalkotására. Ismeri országa, tájegysége cimereit, közvetlen környezetében, még a legjelenléktelenebbeket is, mitöbb Ynev távoli vidékeinek kiemelkedően fontos cimereit is.',
            Mf: 'Mesterfokú képzetség esetén a karakter előtt nem ismeretlen a távoli tájak cimerei sem, még akkor sem, ha azok nem túl jelentősek. Saját országában még a legapróbb családokét is ismeri, mitöbb, a régmúlt korok címereire és jeleire is emlékszik.',
        },
        {
            id: 'LEGENDA_ISMERET',
            name: 'Legendaismeret',
            KpAf: 10,
            KpMf: 50,
            description: '',
            Af: 'A Legendaismeret Alapfokon nem több egyszerű lexikális tudásnál. A képzett karakter tisztában van különféle helyekhez, tárgyakhoz, személyekhez kötött legendákkal. Tudása álltalában egy-egy tájegységre vanatkozik.',
            Mf: 'A karakter mérhetetlen számú legendát ismer a világ majd minden tájáról. Soknak az igazságtartalmával is tisztában van. Világosan átlátja a legendák születésének pszihózisát, igy egy sosem halottból is nagy bisztonsággal képes kiszűrni a valóságot elkülönítve a prózai túlzásoktól. A Legendaismeret Mesterfokát álltalában neves bölcsek bírják Ynev szerte.',
        },
        {
            id: 'TORTENELEM_ISMERET',
            name: 'Történelemismeret',
            KpAf: 5,
            KpMf: 20,
            description: 'A Történelemismeret képzetség elsősorban bölcsek, lovagok sajátja. Teljes mértékben lexikális jellegű tudomány, ámbátor mesterei állítják, a múlt ismerete sokban segít a jövő eseményeinek megsejtésében.',
            Af: 'Alapfokon a karakter saját országának, tájegységének történelmét ismeri. Ez kiterjed eseményekre, helyszínekre, jelentős történelmi alakokra egyaránt.',
            Mf: 'A Mesterfokú Történelemismeret felruházza a karaktert azon képességgel, hogy átlássa a történelem eseményei közötti összefüggéseket. Már nem pusztán saját tájegységének, de Ynev egészének történetével tisztában van, tekintettel a hősi múlt történeteire is.',
        },
        {
            id: 'VALLAS_ISMERET',
            name: 'Vallásismeret',
            KpAf: 5,
            KpMf: 25,
            description: '',
            Af: 'Alapvetően a papok képzetsége, de tőlük bárki eltanulhatja. Nagyrészt lexikális jellegű tudás, melynek birtokában a karakter biszton állíthatja, ismeri Ynev főbb vallásait, azok Isteneit, történetét, alapvető tanításait és legnagyobb tanítóit. Számtalan szertartás menetével és céljával is tisztában van.',
            Mf: 'Aki Mesterfokon bírja a Vallásismeret képzetséget, az előtt Ynev legapróbb-cseprőbb, netán titkos vallásai sem ismeretlenek. Hallott ezek szertartásairól, és nagy bisztonsággal képes meghatározni azok célját is. A főbb vallásokat szinte teljes alaposággal ismeri, képes idézni azok szent könyveiből, nem jelent számára gondott kevéssé ismert alakjainak felsorolása és jellemzése sem. Saját hitévél és minden azzal kapcsolatos mozzanattal oly fokig tisztában van, hogy a legfelsőbb egyházi körökben sem kerülne zavarba egy teológiai vita kirobbanásakor.',
        },
        {
            id: 'EPITESZET',
            name: 'Építészet',
            KpAf: 5,
            KpMf: 20,
            description: 'Az Építészet képzetségben való jártasság nem feltétlenül jelenti az azonos nevű hivatás gyakorlását.',
            Af: 'Az Alapfokon képzett karakter ismeri az Yneven uralkodó főbb építészeti stílusokat, egy épületről megközelítő pontossággal képes megállapítani, mely században, s melyik kultúra emelte.',
            Mf: 'A Mesterfokon jártas karakter tudománya már nem passziv tudás, ő már képes épületek megtervezésére. Ezek lehetnek házak, de kastélyok, komoly várak nemigen. A Mesterfokú képzetséggel együtt jár, hogy a karakter másoknál nagyobb bisztonsággal képes megsaccolni az esetleges titkos ajtók és folyosók elhelyeszkedését. Ezért a Titkosajtó keresés nevű, szézalékos jártasságban mért képzetségre +20 százalékot kap.',
        },
        {
            id: 'MERGKEVERES',
            name: 'Méregkeverés/semlegesítés',
            KpAf: 15,
            KpMf: 60,
            description: 'Sokan nyúlnak ellenfeleik gyengítésére vagy legyilkolásának reményében a mérgezés módszeréhez. Egyesek arra is hajlandók, hogy éveken át tanuljanak, elsajátítsák a méregkeverés tudományát és saját maguk készitsék el a káros matériát. Másokat éppen ellenkezőleg, a segítségnyújtás vágya hajt. Természetesen a képzetség igazi nagymesterei a boszorkányok és boszorkánymesterek, de a nagyobb orrgyilkos klánok mindegyike tart legalább egy méregkeverőt. A mérgezés mestersége sokban támaszkodik az alkímiára, a herbalizmusra és az élettanra, de tanulói e három tudományt, meglehetősen, egyoldalúan tanulják. Ha egy karakter rendelkezik ezekkel a képzetségekkel, jóval könnyebben sajátíthatsa el a mérgek tudományát ( Mindhárom képzetség 3-3 Képzetség Pontot ad a méregkeverés tanulásához). Ez egyben mutatja azt is, hogy egy herbalista vagy alkimista is állíthat elő mérget, de lényegesebben gyengébbet, mint a méregkeverő. A méreg - vagy ellenméreg- előállításához minden esetben megfelelő alapanyagok, felszerelés és idő kell.',
            Af: 'Az alapfokon képzett karakter képes legfeljebb 5. szintű méreg előállítására, amely azonban ritkán okoz halált vagy ájulást. Kínmérgei legfeljebb 15 Fp vesztést okozhatnak. Alapfokon több komponensű és kontaktméreg nem keverhető. Képes ezenkívül az álltala ismert mérgek ellenszerét is előállítani, ezek +1-3 módosítót jelentenek egészségpróba esetén.',
            Mf: 'A Mesterfokon képzett karakter már képes bármilyen méreg előállítására, bár egyes esetben ez igen költséges és egy alkímista vagy herbalista mester közreműködését igényli. A karakter képes bármilyen, álltala ismert méreg ellenszerét előállítani, ami +2-6 módosítót jelent egészségpróbánál.',
        },
        {
            id: 'HERBALIZMUS',
            name: 'Herbalizmus',
            KpAf: 5,
            KpMf: 35,
            description: 'Ez a tudomány elsősorban a természeti népek vajákosai és sámánai körében elterjedt, de Ogonomus óta, a világi bölcsek előtt sem ismeretlen. Eredeti célja a gyógyitás volt, de mint oly sok minden mást, at Ember ezt is hamar megtanulta egyébb célok elérése érdekében felhasználni - tegyük hozzá, nem kis sikerrel. A Herbalizmusban járatos karakter alapvetően kétféle hatású szert készíthet növényekből: gyógyszert és mérget. Azt, hogy egy adott drog méreg vagy orvosság, inkább felhasználása dönti el, semmint eredete. Ide tartoznak még a halucinogénok - ha úgy tetszik kábitószerek - is. Ezek nem szó szoros értelemben vett mérgek, ám hasonló alkalmazásuk és hatásmechanizmusaik miatt itt tárgyaljuk őket.',
            Af: 'Az Alapfokú képzetséggel képes a karakter legfeljebb 5. szintű betegség gyógyítására alkalmas orvosságok elkészítésére. Ezek álltalában az Egészség-próbára adnak módosítót, rendszerint +1-től +9-ig. Képes ezenkivül sebeket és sérüléseket ellátni, melyek így kétszer olyan gyorsan gyógyulnak, mint egyébbként - vonatkozik Ép és Fp vesztésre egyaránt. Ezeken túlmenően a karakter keverhet mérgeket, melyek beadható mérgek esetén elég erősek lehetnek, bár halált nem okozhatnak, egyébb fajtájú mérgekből, pedig csak gyenge állítható elő. Elkészitheti ezenkivül az álltala ismert mérgek ellenszerét is.',
            Mf: 'Mesterfokú képzetség esetén a karakter bármilyen betegséget gyógyíthat, hasonlóan ahhoz ahogy az Alapfokon tette. Az álltala kezelt sebek négyszer gyorsabban gyógyulnak, mint egyébbként. A mérgek közül hatékonnyabbakat készithet, nem csinálhat azonban gáz- és több komponensű mérgeket.',
        },
        {
            id: 'SEBGYOGYITAS',
            name: 'Sebgyógyítás',
            KpAf: 15,
            KpMf: 30,
            description: '',
            Af: 'A sebgyógyitás alapfokon leginkább a seb külső ellátását szolgálja, tehát segít megállítani a vérzést, megakadályozni az elfertőződést vagy a seb ismétlődő felnyillását. Ezért jelentős eredménnyel alkalmazható az Fp-k gyógyításában. Ép gyógyítására nem alkalmas, ahhoz más jellegű ismeretek is szükségesek. Az Alapfokú képzetség lehetővé teszi a helyes kötés alkalmazását, s használója tisztában van a seb tisztításának és fertőtlenítésének alapjaival. Ha rendelkezésre áll a szükséges kötszer, a vérzést elállíthatja, a sebet bekötözheti. Ha a seben kötés van, a gyógyulás sebessége a kétszeresére nő. Amennyiben a képzetség használója gondozza a sebet, azaz cseréli rajta a kötszert, rendszeresen tisztítja környékét és mindent megtesz a seb gyógyulásáért, a sebesség háromszoros lesz. Ez csak a Fájdalomtűrés pontok gyógyulásakor igaz, az Ép gyógyulásának sebessége nem nő, csak a fertőzésveszély csökken. Az Alapfokú képzetség az Ép-vesztést okozó sebek gyógyításakor egyötödére csökkenti a fertőzés esélyét. Ez annyit jelent, hogy a fertőzés esélye csak az elveszett Ép-k számának kétszerese lesz, százalékban ( és nem tízszerese!). A törések és repedések, továbbá ínszakadások és porc sérülések ellátásához a képzetség csak alapfokú ismeretet ad, s a gyógyulást csak kis mértékben segíti elő.',
            Mf: 'A Mesterfokú képzetség már komoly ismeretanyagot nyújt ezekhez is. Tartalmazza a kenőcsök és gyógynövények alkalmazásának tudományát is. Mesterfokú képzetség esetén mint Fájdalomtűrés pontok, mint az Életerő pontok gyorsabban gyógyulnak. Az Fp sérülések esetében, egyszeri kötözés hatására a gyógyulás háromszoros sebességű lesz, a rendszeres kezelés hatására pedig négyszeres. Az Ép gyógyulásában nagyobb a változás hiszen a Mesterfokú képzetség ebben nyújt igazán fontos segítséget. Kötözéssel, ami sínbe rakást, varrást vagy bármilyen egy alkalommal végrehajtott kezelést értünk - az Ép gyógyulás sebessége kétszeres lesz, az ellfertőzés esélye pedig nullára csökken. A rendszeres kezeléssel a gyógyulás ideje harmadára csökken. A mesterfokú képzetség lehetővé tesz viszonylag bonyolult, szinte műtét értékű beavatkozásokat is, amik az Alapfokú alkalmazással elképzelhetetlenek lennének.',
        },
        {
            id: 'PSZI',
            name: 'Pszi',
            KpAf: 10,
            KpMf: 55,
            description: 'A gondolkodó elme hatalmas erőforrásokat rejt, melynek felhasználásával uralmunk alá hajthatjuk testünk minden porcikáját, befolyásolhatjuk az anyagi világ törvényeit, vagy akár mások tudatát. Pyarronban dolgozták ki a Pszi mindenki számára megtanulható fajtáját, mely segitségével önmagunk és mások felet is korlátozott befolyásra tehetünk szert. A Pyarroni módszer nem alkalmas sem Mana előállítására, és nem is olyan hatékony mint a Slan-út- ám nagy előnye, hogy rövidebb idő alatt elsajátítható, mint az előbbi kettő, és gyakorlatilag bármely kaszt számára elérhető.',
            Af: 'Segítségével saját testünk és akaratunk felett nyerhetünk hatalmat, elménk köré asztrális, vagy mentális pajzsokat építhetünk. Az Alapfok alkalmazói az Általános Diszciplinák mindegyikét végrehajthatják, ám csak saját magukon. Elsajátításához elegendő 2-3 év, noha szükséges, hogy a tanuló Intelligenciája, Asztrálja és Akaratereje legalább 12 legyen.',
            Mf: 'A Pszi alkalmazás azon foka, amely megengedi, hogy mások tudatára vagy fizikumára is hatást gyakoroljunk. A mesterfok ismerői képesek más Pszi-pajzsokat lebontani, és az Általános Diszciplinákat nem csak magukon, hanem másokon is végrehajthatják. Igaz, ilyenkor a befolyásolni kivánt személy ME dobásra jogosult - asztrális vagy mentális, attól függően, hogy a diszciplina a tudat melyik síkját támadja. A mesterfok eléréséhez szükséges az alapfok ismerete, jó néhány év gyakorlat, és rövid képzés egy Pszi-mestertől ( legalább 5. szintű mesterfokú Pszi használó ).',
        },
        {
            id: 'ALKIMIA',
            name: 'Alkímia',
            KpAf: 10,
            KpMf: 40,
            description: 'Az Alkímia Tudománya elsősorban a Prima Material, más néven a Bölcsek Köve előállítására törekszik. Ez az a principium, melynek segítségével a nemtelen anyag arannyá változtatható. Ámbár Ynev világán a mágusok, de még a varázslók is képessek erre, jóval kevésbé fáradságos módon. Ez mégsem kedvetleniti el az alkimistákat, hiszen ők a tömeges aranycsinálásra törekszenek. Másrészt pedig, az Alkimia mára szerteágazó tudománnyá fejlődött, foglalkozik mindenféle mágikus italok, porok előállításával, és persze elméleti úton az emberi elme nemesedését is célul tűzi ki.',
            Af: 'A képzetség Alapfokán a karakter egyszerűbb vegyületek, párlatok, őrlemények elkészitésére képes.',
            Mf: 'A karakter bonyolult, nagyhatású anyagokat is készíthet.',
        },
        {
            id: 'ELETTAN',
            name: 'Élettan',
            KpAf: 15,
            KpMf: 45,
            description: 'Ynev világi tudományai közül a legtitkosabb az élet forrását kutató Élettan. Tudósait óvatos tisztelet övezi - akár a Bölcsek Kövét kereső alkímistákat - hiszen magát az Élet Principiumát kutatják, a szikrát, ami élővé magasztosítja, az amugy nemtelen anygból felépült testet.',
            Af: 'Az Élettan képzetség már alapfokon is elegendő mozgó szobrok ( Gólemek ) megformázásához, hasznos a gyógyításkor, és elengethetetlen az Átváltotatás varázslat egyszerűbb alkalmazásához, vagy a Mesterfokú képzetség elsajátításához.',
            Mf: 'Az Élettan Mesterfokú ismerője - ha bírja a szükséges mágikus hatalmat - alkothat életképes homonkuluszt, s az átváltoztatás varázslattal szinte bármely varázslást eszközölhet az élőlények szervezetében. Természetesen különleges lények alkotásához, különleges szervek megformázásához az adott teremtmény élettanát is szükséges ismerni, ami nem lebecsülendő akadály, hiszen ki hallott már tudósról, aki - tegyük fel - sárkányokat boncolt ?!',
        },
        {
            id: 'MAGIA_HASZNALAT',
            name: 'Mágia használat',
            KpAf: 15,
            KpMf: 45,
            description: 'A Mágiahasználat képzettség ismerője semmiképp sem számít varászlónak. Tudományának leghasznosabb vonása nem is az, hogy varászlatok létrehozására képes, hanem, hogy ismeri a mágiát, felismeri a varázslatokat, tudja minek mi az ellenszere. Kisenergiájú varázslatai az Elemi Mágiát kivéve nemigen érnek többet egyszerű trüköknél, bűvészmutatványnál. A Mágiahasználat képzetség Mesterfokán 10 Mp-ot képes az elméjébe gyűjteni. Az energiagyűjtést minden nap csak egyszer - pontosabban mindég csak kiadós alvás után, kipihenten - képes.Ez oly mértékben leterheli pszihéjét, hogy a következő huzamosabb alvásig a műveletet megismételni képtelen. A Mágiahasználat képzetséget mágusok dolgozták ki, és Yneven kizárólag két helyen oktatják: a Pyarroni Okkult Tudományok Egyetemén, illetve a Sigranomi Egyetemen. A képzés Alapfokon 3 évbe és 700 aranypénzbe, Mesterfokon 5 évbe és 1000 aranypénzbe kerül.',
            Af: 'A Mágiahasználat képzetség alapfokú ismerője már hatásuk alapján felismerik a varázslatokat, képesek következtetni az alkalmazott mozaikokra - egyszóval tudatában van mindazon elméleti tudásnak, amit a Mágia fejezetben leirtunk - de nem képes használni mágiát.',
            Mf: 'A Mágiaismeret képzetség Mesterfokú elsajátitásával a karakter - bármely kasztú is- képes lesz mozaikmágia használatára. Természetesen csak jelentős megszoritásokkal: az Asztrál és Mentálmágia fejezet alá tartozó varázslatmozaikok alkalmazására egyáltalán nem képes, és a Mana-pontjainak száma sem növekszik TSZ- lépéskor.',
        },
        {
            id: 'DEMONOLOGIA',
            name: 'Démonológia',
            KpAf: 20,
            KpMf: 55,
            description: 'A Démonológia titkos képzetség. Pyarron vagy Doran könyvtáraiban akad csak olyan fóliáns, amely titkairól regél, s pesze a távoli Kránban. Toron egyes rendjei avatják be tudományába a tagjaikat, s a Déli Kolostorokban bukkanhat efféle tudás nyomára a kiválasztott kutató.',
            Af: 'A Démonológiában alapfokon képzett karakter közel száz fajta közdémon nevét, gondolati sémáját és képességeit ismeri. Ugyanigy tisztában van a legtöbb démonúr és démonherceg tudományával.',
            Mf: 'Mesterfokú képzetség esetén ismeri a Démonok mentális testének felépítését, így Alexandrit használata nélkül is képes rájuk Mentális Mágiával hatni.',
        },
        {
            id: 'RUNAMAGIA',
            name: 'Rúnamágia',
            KpAf: 18,
            KpMf: 45,
            description: 'A Rúnamágia - ha szigorúan nézzük- a Jelmágia azon alfejezete, amely a különböző rúna-rajzolatok mágikus tulajdonságait tanulmányozza. Elsődleges fontossággal bir a Jelmágián alapuló varázstárgyak készítésében, ahol a mágikus hatásokat a rúnák tárolják.',
            Af: 'A Rúnamágiában alapfokon képzett karakter képes szabályosan felolvasni a mások álltal leírt rúnákat. Tudománya elegendő arra, hogy tekercseket olvasson fel, s életrehivja a beléjük fogalmazott varázslatokat, ám nem teszi alkalmassá egyetlen rúna leírására sem.',
            Mf: 'A rúna leírásának tudománya. Mivel számtalan mágikus alapismeretet és jelentős mágikus hatalmat követel, még a nagy varázslóiskolákban is csak keveseknek oktatják ( 6. TSZ fölött ). Ismeretében a karakter varázstárgyakat alkothat.',
        },
        {
            id: 'DRAGAKO_MAGIA',
            name: 'Drágakő mágia',
            KpAf: 0,
            KpMf: 52,
            description: 'Titkos képzetség, csak a legnagyobb varázslóiskolákban a kiválasztott ( 9. TSZ felett ) tanítványoknak oktatják.',
            Af: 'Alapfokú alkalmazása nem ismeretes.',
            Mf: 'Mesterfokon varázstárgyak és drágakő esszenciák készítésére alkalmas.',
        },
        {
            id: 'IDOMITAS',
            name: 'Idomítás',
            KpAf: 8,
            KpMf: 20,
            description: 'Ynev világában nagycsomó olyan állat akad, amely betanítható az ember szolgálatára. Ezeknek csak jelentős, de nem kizárólagos hányadát jelentik a lovak, ökrök, kutyák. Hiszen vannak akik farkasokat, madarakat édeskednek magukhoz. Az Idomítás képzetség felruházza a karaktert annak képességével, hogy állatokat tanítson be különféle feladatok végrehajtására.',
            Af: 'Alapfokú képzettség esetén ezek csak hétköznapi, az adott állatfajtól megszokott cselekedetek lehetnek. A ló idomítható lovaglásra, a kutya alapvető engedelmességre.',
            Mf: 'A Mesterfokon idomító karakter állatait már mindenféle különleges kunsztok végrehajtására is képes betanítani. Remek példája ennek az, ami a vándorcirkuszban történik.',
        },
        {
            id: 'ETIKETT',
            name: 'Etikett',
            KpAf: 8,
            KpMf: 15,
            description: 'Az Etikett az udvarias, társadalmi követelményeknek megfelelő viselkedést jelenti. Azt a tudományt melynek birtokában a karakter tudja, kit miként kell köszöntenie, milyen módon kell meghajolnia, bizonyos helyzetekben hogyan kell viselkednie. Képes cirkalmassan fogalmazni, és megtalálja a helyét úri társaságban. Minden nép, tájegység, ország, birodalom kialakitja saját illemrendszerét, igy a karakternek a képzetség tanulásakor meg kell határoznia, hogy mely vidék etiketjét kívánja elsajátitani. A legismertebbek a shadoni, a pyarroni, erigowi, toroni és abasziszi etikett.',
            Af: 'A karakter járatos a nemesi és főnemesi etikettben. Ismeri a réteg szokásait, az udvariassági fordulatokat, képes burkoltan közölni gondolatait, illetve illedelmesen vérig sérteni valakit.',
            Mf: 'A karakter a fent leírtak mindegyikében még az udvarnál is megállja helyét.',
        },
        {
            id: 'NYOMOLVASAS',
            name: 'Nyomolvasás/eltüntetés',
            KpAf: 10,
            KpMf: 45,
            description: 'A Nyomolvasásban járatos karakter képes követni mások nyomait, pusztán a nyomokból kiolvassa, hányan jártak arra őelőtte és nagyából mi történt a helyszinen. Természetesen az eső, és a köves talaj megnehezíti a nyomolvasást.',
            Af: 'Terptől függően 1-6 nap távlatából képes olvasni a nyomokat. Azonos szintű képzetséggel rendelkező nyomolvasó elől el tudja tüntetni nyomait.',
            Mf: 'Tereptől függően akár 1 hónap távlatából is sikerülhet kiolvasnia a nyomokból a kívánt információt. Nyomait teljesen el tudja tüntetni.',
        },
        {
            id: 'ERDOJARAS',
            name: 'Erdőjárás',
            KpAf: 5,
            KpMf: 14,
            description: 'Az Erdőjárás képzetség a természet, különös tekintettel az erdő ismeretét jelenti. Olyan tudás amelynek segítségével a karakter eligazodik a leghatalmasabb rengetegben is, ismeri a ragadozókat, a zsákmányállatokat, tudja mitől kell tartani és mitől nem. Megleli az ehető bogyókat és gyökereket, mint ahogy felismeri a mérgezőket is. Ismeri a vadak szokásait, a növények tipusait.',
            Af: 'A karakter éveket élt erdőben',
            Mf: 'Leginkább elfek, erdőben élő Arel papok vagy évtizedekig erdőben élő erdőjáró.',
        },
        {
            id: 'VADASZAT',
            name: 'Vadászat/halászat',
            KpAf: 8,
            KpMf: 15,
            description: 'A Vadászat/Halászat képzetség azzal a képességgel ruházza fel birtokosát, hogy könnyen, fáradság nélkül jusson élelemhez erdőn, mezőn, tavak, tengerek környékén.',
            Af: 'A képzett karakter ismeri az állatok, halak szokásait, tudja mire, milyen körülmények között, milyen csalétekkel és milyen napszakban érdemes vadászni, illetve halászni. Tudománya saját és mások tapasztalatán alapul, netán bizonyos népek nemzedéről nemzedékre öröklődő hagyományain.',
            Mf: 'A Mesterfokon képzett karakter, ha vadak nyomába szegődik, mintegy ösztönösen, belső intuíció álltal vezetve talál rájuk. Netán olyan misztikus képességekkel is rendelkezik, mely segítségével magához csalogatja a későbbi zsákmányt. A Mesterfokú Vadászat/Halászat igazi mesterei az elfek lehetnének, ha különleges képességeiket hajlandóak lennének efféle általuk megvetett cél szolgálatába állítani.',
        },
        {
            id: 'LOVAGLAS',
            name: 'Lovaglás',
            KpAf: 1,
            KpMf: 15,
            description: 'A Lovaglás képzettség elengethetetlenül fontos minden kalandozó életmódott folytató karakter számára. De nem nélkülözhetik a katonák, harcosok, lovagok sem - sőt! A ló Ynev legelsődlegesebb közlekedési eszköze. Így vagy ugy de majdnem minden nem paraszti származású ember elsajátítja a Lovaglást.',
            Af: 'Az alapfokon képzett karakter képes megülni a lovat, irányítani, akarata szolgálatába kényszeríteni - feltéve, ha a hátas idomított. Nem jelent számára gondott a vágta, de az ugratás sem. Kijelenthetjük, már az alapfokú képzetség is tökéletes lovastudományt jelent. Ahoz azonban nem elegendő, hogy a karakter kihasználhassa a lovas harcmodorból származó előnyöket.',
            Mf: 'A Mesterfokon képzett lovas tökéletes uralmat tart az álltala megült hátas felett. Gyakorlotsága révén nem igényel tőle különösebb figyelmet az állat irányítása, ezt ösztönösen teszi. Így képes ugy harcolni lovaglás közben, hogy teljesen kihasználja az ebből eredő előnyöket.',
        },
        {
            id: 'KOCSIHAJTAS',
            name: 'Kocsihajtás',
            KpAf: 2,
            KpMf: 15,
            description: '',
            Af: 'Az alapfokon képzett karakter gond nélkül hajt egyes- vagy kettesfogatot, tudja miként kell ki- és befogni a lovakat, ismeri a különböző kocsik, hintók teherbírását.',
            Mf: 'Mesterfokú képzetség esetén a karakter elboldogul a négyes- vagy akár a hatosfogattal is, mitöbb, harcikocsi hajtásban is megtalálja a helyét.',
        },
        {
            id: 'USZAS',
            name: 'Úszás',
            KpAf: 2,
            KpMf: 10,
            description: 'Az úszni tudás korántsem hétköznapi ismeret Ynev világán. Leginkább csak a tengerek, tavak, folyók prtján élők bírják. Egyes hadseregekben alacsony szinten megkövetelik a katonáktól, de ez nem álltalános. A különféle Harcos kasztok tagjai esetében azonban már mindennapos tudománynak számít.',
            Af: 'A karakter jól úszik. Ha kevés súly huzza, akár egy óra hosszatt is képes lebegni a felszinen. Könnyedén átuszik egy közepesen erős sodrású folyót.',
            Mf: 'Képes teljes felszerelését a viz felszínén tartani, könnyedén úszik órákig is, ha úgy hozza a sors. Átússza a legsebesebb sodrású folyót is. FIGYELEM! fémvértezetben még mesterfokon sem lehet úszni.',
        },
        {
            id: 'SZEXUALIS_KULTURA',
            name: 'Szexuális kultúra',
            KpAf: 5,
            KpMf: 30,
            description: 'A Szexuális kultúra képzetség valójában a szeretkezés művészetét jelenti. Ynev világán több kultúrkör is kialakította a maga, a többitől differens tudományát az érintett területen. A karakter ezek közül válogathat, mikor a képzetség elsajátítására készül.',
            Af: 'A karakter kultúráltan szeretkezik, érzékeli és képes teljesíteni partnere kívánságait.',
            Mf: 'A karakter szeretkezés közben a legmagasabb kéjben részesíti, szinte megörjíti partnerét. Mindezek eredményeként, álltalában, érzelmileg is magához láncolja a másikat.',
        },
        {
            id: 'HAJOZAS',
            name: 'Hajózás',
            KpAf: 15,
            KpMf: 40,
            description: 'Ynev világának beltengerein, tavain és folyamain jelentős hajózás folyik. Használnak tutajokat, gályákat, vitorlás hajókat, de még acélból épitett mágikus hajtású vizijárműveket is. A három legjelentősebb vizi-kereskedelmi útvonal: az úgynevezett Bíbor-út a Quiron-tengeren, mely Toronból Abasziszba vezet, a szintén ugyanezen tengert átszelő a Tiadlan kikötőiből a Városállamokba vezető útvonal, valamint maga az egész Gályák Tengere.',
            Af: 'A Hajózásban alapfokon képzett karakter képes elirányítani folyami, vagy kisebb tavi hajókat, és megálja helyét matrózként a tengeri hajókon.',
            Mf: 'Mesterfok képzettség esetén képes tengerjáró hajók parancsnoklására, sőt partmenti, óceáni fuvar lebonyolítására is. Azonban Mesterfok esetén már meg kell határozni azt a hajótípust, melyre ugymond szakosodik. Választhat egy vagy több árbócos vitorláshajót, Galeaszt, vagy gályát, netán ezen csoportok bármelyikébe tartozó, de külön kategóriának számító hadihajót.',
        },
        {
            id: 'ENEKLES',
            name: 'Éneklés/zenélés',
            KpAf: 5,
            KpMf: 30,
            description: 'Nincs oly világ, ahol ne ismernének az ének és zene művészetét. Nem kivétel ez alól Ynev sem - sőt! Az udvari zenészektől a kizárólag maguk szórakoztatására éneklő bárdokig, a szent énekeket kántáló kórusoktól a primitív benszülött ceremóniák énekeséig mindenféle és fajta zenecsinálló fellelhető a kontinensen. A képzetség elsajátításával a karakter szert tehet a különféle hangszereken történő játék, valamint az éneklés tudományára. Olyan ismeret ez, mely kellő fokon űzve bisztos kenyeret bisztosít a karakternek bármilyen nemesi udvartartásban, olykor pedig segítségére lehet az egyébbként kemény szivek meglágyításában. Különösen igaz e utóbbi kitétel Ilanorban, ahol a nyers, képzetlen hangú, de tagadhatatlanul lelkes és tehetséges dalnokok búskomor nótái hamar könnyet csalnak a hallgatóság szemébe.',
            Af: 'Az alapfokú képzetség esetén a karakter tagadhatatlanul szépen énekel, és játszik egy álltala választott hangszeren.',
            Mf: 'A karakter kiművelt hangon énekel, sokféle hangszeren játszik. Ha zenél, egyhamar elbűvöli a hallgatóságát. Tudománya már minden szempontból művészetnek nevezhető.',
        },
        {
            id: 'TANC',
            name: 'Tánc',
            KpAf: 5,
            KpMf: 30,
            description: 'Fontos elkülöniteni a köznépi és az udvari stílust, valamint az igazi táncművészetet. Az Ynevi vidék és város egyszerű népe ünnepei alkalmával szívesen táncol, s ugyanez áll a jómódú polgárházak, paloták lakóira is. Az előbbi látványa viszolygást kelt, az úgynevezett felsőbb körökbe, utóbbié kacajt fakaszt a közrendű ajkakon - az egyes osztályok képviselőinek azonban felettébb ritkán adatik meg, hogy produkcióikkal egymást boldogitsák. A tánc művészetének számtalan vállfaja akad a kontinensen, példaként elég, ha az ilanori és yllinori kardtáncot, a niarei tőrtáncot, vagy a dzsad tűztáncot említjük.',
            Af: 'Alapfokú képzetség birtokában a karakter ismeri szülőhelyének és környékének táncait, és - ha koncentrál - úri társaságban sem hoz szégyent magára.',
            Mf: 'Mesterfokon a karakter már az összes számottevő irányzat lépéseit ismeri, a divatosabbakban pedig egyenesen kivállónak minősül - akár egy uralkodóházban is megálja a helyét. Ha anyagi helyzete megkívánja, fellépést vállalhat, leckéket is adhat, megfelelő javadalmazásért.',
        },
        {
            id: 'HANGUTANZAS',
            name: 'Hangutánzás',
            KpAf: 3,
            KpMf: 16,
            description: 'Sokrétű képzetségről van szó, ide soroljuk a vadászok állathang utánzó képességét, mellyel magukhoz csalogatják a vadat, ide tartozik a komédiások tudománya is, ennek segítségével ismert személyek, főurak, papok, királyok hangját utánozzák, közönségük épülésére.',
            Af: 'A képzettség alapfokán a karakter utánozhat szinte bármely állat, madár hangját, s a jellegzetes karakteres hangú, beszédmondó emberek utánzásával is elboldogul. Ellenben azokat, akik az utánzott személyeket közelről ismerik nem képes megtéveszteni, legfeljebb remekül elszórakoztatni.',
            Mf: 'A karakter bármilyen emberi, vagy nem emberi, de emberi szájjal reprodukállható hangot képes leutánozni. Kis gyakorlással ezt olyan tökélyre viheti, hogy még az utánzott személy édesanyja is összekeveri őt saját fiával - persze hacsak hangját hallja. Mesterfokú képzetséggel zajok, zörejek is valósághűen utánozhatók, például kulccsörgés, fegyvercsattogás, léptek dobogása, ajtónyikorgás.',
        },
        {
            id: 'ERTEKBECSLES',
            name: 'Értékbecslés',
            KpAf: 5,
            KpMf: 11,
            description: 'Az értékbecslés tudománya álltalában ékszerészek, aranyművesek, tolvajok képessége, de némi gyakorlással és tanulással bárki elsajátíthatja. A képesség segitségéval az értő szemű karkter rögvest megállapíthatja a drágaságok értékét, és könnyen elkülöníti a valóst a hamistól.',
            Af: 'Az Alapfokú értékbecslő képes meghatározni a drágakövek, arnay- és ezüsttárgyak értékét. Felismeri a megmunkáltság minőségéből eredő különbségeket és a neves mesterek kezemunkáját. Egy ilyen karaktert bizony nehezen vernek át, mikor vásárol vagy elad.',
            Mf: 'A Mesterfokon képzett karakter már a régiségek, mitöbb a varázsos tárgyak értékét is meg tudja becsülni. Távoli tájak rég elhunyt kézműveseinek munkáit is felismeri, és tisztában van annak valós árával.',
        },
        {
            id: 'CSAPDAALLITAS',
            name: 'Csabdaállitás',
            KpAf: 10,
            KpMf: 20,
            description: '',
            Af: 'A karakter képes embert vagy állatot fogjulejtő, vagy akár csak figyelmeztető jellegű csapda elkészítésére. Ezzel Ép vesztést nem okozhat, Fp vesztést max 1-10-et, továbbá ember foglyul ejtésekor nagyon valószinű, hogy az kiszabadul.',
            Mf: 'A karakter képes embert is tartósan fogvatartó csabda készitésére, vagy a csapdával 3-30 Fp-t illetve 1-10 Ép-t sebezni.',
        },
        {
            id: 'CSOMOZAS',
            name: 'Csomózás',
            KpAf: 7,
            KpMf: 24,
            description: 'A kötélhasználat mesterei, a hurkok és bogok legjobb ismerői mindég is a hajósnépek voltak. Idővel a szárazföldek kalandorai is felismerték a kötélhasználatban rejlő lehetőségeket és egyre rátermetebben kezdték alkalmazni.',
            Af: 'Alapfokú képzetség olyan csomók készítésére alkalmas, melyet józan ésszel képesek vagyunk elképzelni.',
            Mf: 'Mesterfokon pedig mindaz, ami az alapfokon túl van.',
        },
        {
            id: 'ZSONGLORKODES',
            name: 'Zsonglőrködés',
            KpAf: 3,
            KpMf: 10,
            description: 'A Zsonglőrködés a szórakoztatás kedvelt módja Yneven. A felsőbb körök éppoly szivesen szemlélik, mint a piacterek jöttment közönsége. Társulatok járják a falvakat, városokat, igyekeznek hosszabb-rövidebb időre beférkőzni egy-egy tudományukat méltányoló földesúr kegyeibe. Álltalában vidéken találják meg könnyebben számításaikat, ahol a vándorcirkusz érkezte jelentős eseménynek, kitüntetett látványosságnak számít. A nagyobb városokba márcsak az igazi profik keresik meg a kenyerüket, míg a főnemesi -ne adj Isten Királyi udvarba csak a legjobbak juthatnak be.',
            Af: 'A karakter kezdő szinten zsonglőrködik, ügyesen dobál a levegőbe egyszerre három, vagy akár négy tárgyat is, és ezeket semmiképp nem ejti el. Nehezebb kunsztokba azonban - közönség előtt - jobb ha nem fog.',
            Mf: 'A karakter mesterien zsonglőrködik. Bármilyen társulatban, a legelőkelőbb közönség előtt is megálja a helyét, a piacterekre kiállva hamar pénzhez jutt.',
        },
        {
            id: 'FUTAS',
            name: 'Futás',
            KpAf: 9,
            KpMf: 24,
            description: 'A Futás képzetség sokkal inkább jelent kitartó, mint szélsebes futást.',
            Af: 'Az Alapfokú képzettséggel bíró karakter, órákig képes egyfolytában, lendületes tempóban futni - pontosan annyi óra hosszatt amenyi az Állóképessége.',
            Mf: 'A Futás képzetségnek is akadnak hihetetlen teljesitményre képes űzői. Olyanok, akik napokig birnak egyfolytába futni, pihenő nélkül, vagy olyanok akik órák hosszat lépést tartanak egy vágtató lóval. A Mesterfokú karakter nincs időhöz kötve képzetsége gyakorlásában, ám ha túlfesziti a húrt, akár életét is veszítheti.',
        },
        {
            id: 'SZAKMA',
            name: 'Szakma',
            KpAf: 2,
            KpMf: 15,
            description: 'Természetesen Ynev világán is élnek suszterok, szatócsok, kovácsok, asztalosok, mindnek megvan a maga tudománya, másként fogalmazva a szakmája. A magus Képzetségrendszerében a karakternek arra is van lehetősége, hogy ezeket elsajátítsa. Akár azért, hogy ínséges időkben megéljen belőle, akár azért mert úgy véli, hogy hasznára válik az efféle ismeret kalandozása során. A Szakma képzetség segítségével a karakter elsajátíthat egy általa megnevezett kézműves, civil szakmát.',
            Af: 'A karakter ismeri a szakma alapjait, inasként bárhol beválna. Egyszerűbb feladatokat maga is képes elvégezni, de semmiképpen sem számít elismert mesterembernek.',
            Mf: 'A karakter szakemberként ismeri az adott szakmát. Tudása elegendő arra, hogy - ha úgy hozza a szükség - akár meg is éljen belőle. Bárhol telepszik le, szívesen fogadják, hozzáértését elismerik. Műhely híján képes egyszerűbb, műhelyben akár bonyolultabb holmik elkészitésére.',
        },
        {
            id: 'KOCSMAI_VEREKEDES',
            name: 'Kocsmai verekedés',
            KpAf: 3,
            KpMf: 15,
            description: 'A karakter gyakorlott kocsmai verekedő. Képes bármilyen kézbe akadó, fegyverként használható tárgyal verekedni. Korsóval, székkel, asztallábal. Az efféle képzetséget álltalában saját kárán okulva sajátítja el, esetleg valamilyen mester útmutatása alapján. Ilyesmit oktató iskolák, tárgyaló könyvek nemigen akadnak.',
            Af: 'Ha a felsorolt használati tárgyakkal verekszik, a karakter Té-je Vé-je nem csökken a Képzetlen Fegyverforgatásból származó mínuszokkal.',
            Mf: 'A felsorolt tárgyakkal, egy kör alatt, képes mindkét kézzel támadni.',
        },
        {
            id: 'HATBASZURAS',
            name: 'Hátbaszúrás',
            KpAf: 10,
            KpMf: 25,
            description: 'A leggyakrabban fejvadászok vagy Boszorkánymesterek álltal ismert és oktatott képzetség. Ma már azonban más kasztokba tartozó személyek, olykor egész klánok és rendek folyamodnak használatához. A képzetségel bíró karakter halálos pontossággal támad hátulról, tudja hova milyen erővel kell döfnie, vágnia, ütnie-hogy ezzel áldozatán a lehető legsúlyosabb sebet ejtse. Hátbaszúrásra csak olyan egykezes fegyvert lehet használni, melynek forgatásában a karakter legalább alapfokon képzett.',
            Af: 'A hátulról ejtett seb Sp értékéhez a fegyver sebzésén túl még hozzáadódik 2k6 Sp.',
            Mf: 'Különféle ősi, mitikus mozdulatok sorozata, melynek hatásaként a karakter megacélozza akaratát, megfékezi kezének remegését, s minden figyelmét a döfés pontosságának finomítására szenteli. Az Af-nál már tárgyaltakon kivül az áldozatnak így még további 1k6 Ép -mindenképpen Ép-sebet képes okozni.',
        },
        {
            id: 'HAMISKARTYA',
            name: 'Hamiskártya',
            KpAf: 10,
            KpMf: 20,
            description: 'Ynev fogadóiban, tábortüzei mellett, de még az úri körökben is ismerik és űzik a kártyajátékokat. És akadnak persze olyanok is, akik fittyet hánynak a szabályoknak, és kézügyességüket kihasználva, becstelen trükkök bevetésével  igyekeznek meggazdagodni becsületesebb vagy éppen ostobáb társaik kárára. A kártyalapok szemfényvesztő forgatását, cserélgetését, a hátlapokra rótt titkos jelek leolvasásával folytatott játékot nevezzük hamiskártyázásnak. A képzettség ezen kétes értékű tudományt jelent.',
            Af: 'Alapfoku szinten képes nyerni a képzetséggel nem rendelkező ellen.',
            Mf: 'Mesterfokon átveri az alapfokkal rendelkező hamiskártyást is.',
        },
        {
            id: 'KOTELEKBOL_SZABADULAS',
            name: 'Kötelékből szabadulás',
            KpAf: 8,
            KpMf: 16,
            description: 'A képpzetséggel bíró karakter rövid idő alatt képes kiszabadulni, ha megkötözik. Sok erre irányuló trükkhöz folyamodhat, kötelékeit eldörzsöli valamin, ügyesen kezeli rejtett apró pengéit, netán kígyószerűen hajlékonnyá edzi testét, és egy óvatlan pillanatban kibúj a hurokból.',
            Af: 'Egyszerűbb hurkokból képes kiszabadulni. Ilyen a hátul összekötött kéz, a bokánál való felakasztás. Ha csomózásban akár alapfokon képzett karakter kötözi meg tehetetlen.',
            Mf: 'Bonyolultabb, szakértők álltal készített csomók sem tartják sokáig vissza, hasztalan kötik gúzsba, karikára. Csomózásban alapfokon bírók álltal készitett kötelékből is megszabadul, ám a Mesterfokú csomózók munkái már kifognak rajta.',
        },
        {
            id: 'ALCAZAS',
            name: 'Álcázás/álruha',
            KpAf: 12,
            KpMf: 24,
            description: 'Gyakran tanácsos az embernek arcot váltani, mássá alakulnia, hogy eltűnhessen a tömegben, megtévessze ellenségeit. A menekülés, nemkülönben az észrevétlen támadás eszköze ez. A Képzetségben járatos karakter képes álcázni magát, bármely szituációban meggyőző álruhát ölt.',
            Af: 'Az Alapfokon képzett karakter képes elváltoztatni arcát, alakját, olyannyira, hogy legközelebbi ismerősei sem igen ismerik fel.',
            Mf: 'A Mesterfokú képzetség már annyit tesz, hogy a karakter bárkinek az alakját, arcvonásait képes felölteni némi segédanyag, ruházat és kozmetikum segitségével.',
        },
    ],
    skillsPrecent: [
        {
            id: 'maszas',
            name: 'Mászás',
            description: 'A Mászás képzetség a fák, falak megmászásában való különleges jártasságot jelenti. Azt, amikor a karakter fürgén és bisztosan kúszik fel az átlagember számára megmászhatatlannak itélt meredélyeken is. Az igazán gyakorlott falmászók, még a hihetetlenül sima felületeken is képesek kapaszkodót, támaszt találni. Nem jelentenek számukra akadályt a várak, lakóházak falai, a függőleges, vagy akár a kifelé dőlő sziklák sem. A Mászás képzettségben való Százalékos Jártasság értéke olyan falra, fára vonatkozik, melyet nagy szerencsével egy ügyes, de gyakorlatlan karakter is képes lenne megmászni. Ilyenkor módosító tényező nincs. Ha a fal nehezebben, vagy könnyebben leküzdhető, akkor a KM a karakter hátrányára vagy előnyére százalékot vonhat le, vagy adhat hozzá a jártassághoz. Átlagos nehézségűnek minősül a függőleges, egymásra rakott dinnyényi kövekből halmozott várfal, ahol a kiálló kövek, és a  repedések sűrű, könnyű kapaszkodót bisztosítanak. A Képzetségpróbát minden megtett 25 méter ( vagy 3 perc tétlen kapaszkodás ) után meg kell ismételni. Igy egy 50 méter magas várfal leküzdéséhez két sikeres próba kell. A Mászás képzetség a tolvajok sajátja, de sokan űzik ilyen vagy olyan - akár még az övéknél is magasabb - szinten.',
        },
        {
            id: 'eses',
            name: 'Esés',
            description: 'A karakter ügyesen kigurulja, tompítja az eséseket. Ha nagyon magasról zuhan, érti a módját, hogy a keze ügyébe akadó rögzitett tárgyak segitségével hogyan fékezze, vagy akár állítsa meg a zuhanást. Regéket mesélnek olyan harcművészekről, akik egy kútba zuhanva, a kövek összeillesztésénél keletkező résekbe bele-belekapaszkodva képesek voltak fékezni, sőt kis idő múltán a falhoz tapadva akár meg is állitani az esést. A képzetség általános felhasználása azonban a harc során való esésekből származó ütések tompítása. Az a karakter, aki sikeres Képzetségpróbát tesz, nem szenvedi el az esésből származó sebzést, sőt, jóval könnyebben talpra is keveredik. Az Esés képzettségből való előnyök kihasználásához a karakternek előbb sikeres Képzetségpróbát kell tennie. Az Esés avatatlan nagymesterei mindenképpen a harcművészek, ám a képzetség mindenki számára tanulható.',
        },
        {
            id: 'ugras',
            name: 'Ugrás/Akrobatika',
            description: 'A karakter a legkülönlegesebb ugrások, perdülések, szaltók, passzív és dinamikus hajlékonysági elemek végrehajtására képes, ezeket akár harc közben is alkalmazni tudja. Ezzel természetesen nehezebbé teszi ellenfele számára, hogy az megsebezhesse őt. Igy az Ugrás képzetséget harc közben is használó karakter VÉ-jéhez hozzáadódik az ugrás százalékának egyötöde. ( Pl: Ugrás 40%, akkor +8 a Vé-re ). Ennek természetes alapvető feltétele, hogy a küzdelem helyszinén ehhez elegendő tér álljon rendelkezésre. Vagyis alacsony helységekben, szűk folyosókban az Ugrás képzetsége harc közben nem alkalmazható.A Képzetség nem használható arra, hogy különösen magas falakat, vagy különlegesen széles árkokat ugorjon át. Ezt a Pszi Testsúlycsökkentés diszciplinával lehet elérni.',
        },
        {
            id: 'lopakodas',
            name: 'Lopódzás',
            description: 'A Lopózás képzettségben járatos karakter képes csendben haladni. Sem lépései, sem egyébb mozdulatai nem vernek neszt. Minél képzettebb, annál nehezebb talajon teheti. Nagy segítségére lehet ez az észrevétlen behatolásban, a meglepetésszerű támadásban. Mindezen túl a képzetség ismeret még a haladás közben rejtőzködés képességét is jelenti, mikor a lopódzó kihasználja a terep kínálta tárgyakat, azok takarásába, netán árnyékába húzódva közelíti meg célpontját. A Lopózás mesterei a könnyű léptű elfek valamint a tolvajok és fejvadászok. Ők azok is, akiktől a karakter a legmagasabb szinten sajátíthatja el a képzettséget.',
        },
        {
            id: 'rejtozes',
            name: 'Rejtőzés',
            description: 'A Rejtőzés a félhomályban, vagy tárgyak takarásában való mozdulatlan meghúzódás tudományát jelenti. A képzett karakter képes felfedezni és kihasználni a fényviszonyokat, az emberi gondolkodás hiányosságai kínálta legalkalmasabb búvóhelyeken. A Rejtőzés képzettség a Lopózáshoz hasonlóan a tolvajok és fejvadászok sajátja. Igazi mesterei képesek szinte egybeolvadni a tereptárgyakkal, akár még fényes nappal is.',
        },
        {
            id: 'koteltanc',
            name: 'Kötéltánc',
            description: 'A kötéltánc nem feltétlenül a mutatványosok egy száll kötélen bemutatott szórakoztató produkcióit jelenti. Felettébb hasznos képzetség ez a hétköznapi életben is - különösen azok számára, akik gyakran kényszerűlnek úgy távozni valahonnan, hogy más ne eredhessen a nyomukba. A képzett karakter képes vízszintes, vagy attól 30 fokban eltérő szögben kifeszitett kötélen, rúdon, padlón sétálni. Hogy ezt megtehesse, ahhoz sikeres Képzettségpróbát kell dobnia, minden megtett 10 láb után. Képzetségének százalékban mért értéke  átlagos nehézségű feladatra vonatkozik, amit befolyásolhat a kötél ( padló, rúd ) meredeksége illetve vastagsága, a szél ereje stb. Átlagos nehézségű kötéltáncnak nevezzük a két cm vastag, mereven kifeszített kötélen való gyaloglást, mikor a karakter minden figyelmét a feladatnak szentelheti, és szél továbbá egyébb zavaró körülmények nincsenek. A Kötéltánc mesterei a Harcművészek és a Tolvajok.',
        },
        {
            id: 'zsebmetszes',
            name: 'Zsebmetszés',
            description: 'Ynev világán is akadnak emberek, akik mások pénzének elcsenéséből kívánnak meggazdagodni. A tolvajláson és az erőszakos rabláson túl azonban akadnak jóval finomabb módszerek is. Ilyen a Zsebmetszés. Általában tömegben, a kínálkozó alkalmat kihasználva űzik. A tolvaj belenyúl álldozata zsebébe vagy erszényébe, netán felmetszi azt, és a benne található javakat elemeli. Ahoz, hogy sikerrel járjon, Képzettségpróbát kell tennie. Természetesen léteznek bizonyos könnyítő és nehezitő körülmények, melyekkel számolni kell - ez azonban a KM feladata és jogköre!',
        },
        {
            id: 'csabdafelfedezes',
            name: 'Csapdakeresés',
            description: 'Az elrejtett csapdák felfedezése és hatástalanítása rendkívül hasznos tudomány. Sok kellemetlenségtől óvhatja meg a karaktert és társait. Természetesen a tevékenység nem tudatalatti, csak akkor alkalmazható, ha a karakter előre szól. Nem is nevezhető gyorsnak, hiszen a gyanús terület aprólékos átvizsgálásából áll. A felfedezés és hatástalanítás két egymást követő próba függvénye.',
        },
        {
            id: 'zarnyitas',
            name: 'Zárnyitás',
            description: 'Zárt ajtókkal, lakatokkal gyakran szembesül a kalandozó - hiszen számtalanszor tér be mások házába, kincseskamrájába meghívó nélkül. Az ajtók beszakitása, a lakatok leverése nem mindég célravezető, mivel nemkivánatos zajjal jár. A zárakkal egyidős az állkulcs alkalmazásának tudománya. A Zárnyitásban járatos karakter ismeri a zárak szerkezetét, működési mechanizmusát. Álkulcs készlete - vagy jobb hiján egy darabb drót - segitségével csodákra képes. A sikeres zárnyitás esélyét növelheti a jóminőségű felszerelés és csökkenti a zár bonyolultsága, összetettsége, hozzáférhetetlensége, netán egyedisége.',
        },
        {
            id: 'titkosajto',
            name: 'Titkosajtó-keresés',
            description: 'Várakban, kastélyokban, de olykor még városi házakba is épitenek olyan titkos folyosókat, melyek létéről, bejáratáról a ház urának és bizalmasainak kivételével senki nem tud. A lakók, ha bajba kerülnek, ezekben észrevétlenül elhagyhatják az épületet, vagy meghúzódhatnak rejtett helységeikben. Gyakran efféle folyosók vezetnek a kincseskamrákba, titkos laboratóriumokba vagy föld alatti tanácskozó termekbe. Ugynide soroljuk még a falakban nyilló titkos kamrákat és fülkéket, a padlódeszkák alatt vagy a mennyezetet boritó rozetták mögött meghúzódó rekeszeket. A Titkosajtó keresésben járatos karakternek esélye van arra, hogy meglelje ezen rejtett helyiségek bejáratát, ha létüket sejti, de pontos helyükről nem tud. A képesség gyakorlásához a karakternek a legtöbb esetbe be kell jelentenie kutatási szándékát. Ilyenkor a falat kopogtatja döngő szakaszokat keresve, rések repedések után viszgálódik. A Képzettségpróbát pozitívan befolyásolja, ha megmondja pontosan hol és mit keres. Minnél pontosabb meghatározást add a keresés mikéntjéről, annál nagyobb az esély a sikerre - persze csak abban az esetben, ha a titkos bejárat valóban a gyanúnak megfelelő természetű. A siker esélye annál kisebb, minnél jobban álcázták a titkosajtót, minnél szokatlanabb módon helyezték el. Bizonyos esetben akkor is akad lehetőség egy titkosajtó észlelésére, ha a karakter nem jelenti be kutatási szándékát. Ilzenkor persze nem magát az ajtót leli meg, csak gyanúja támad fel léte felől. Például inokolatlan huzatott érezhet, szemet szúrhatnak neki bizonyos jellegzetes épitészeti megoldások. Ha az adott helységben ilyesmi előfordul, a KM titokban Képzettségpróbát dob a karakter helyett, s csak akkor szól neki, ha a próba sikeres. Ilyen esetben még a karakternek is dobnia kell, ha meg is kívánja lelni az ajtót - ám dobására +25%-ot kap. A titkosajtó felfedezése nem eggyenlő kinyitásával. Olykor egyszerű retesz, zár, netán ravasz mechanizmus gondoskodik a túloldali helység bisztonságáról. Ha a zár nem nyitható néhány egyszerű mozdulattal, ha a karakter nem rendelkezik a beillő kulcsal, vagy a mechanizmus működéséhez szükséges ismerettel, csak a Zárnyitás képzettség segíthet - vagy a fejsze.',
        },
    ],
};
const getters = {
    skills: () => {
        return state.skills;
    },
    skill: (state) => (id) => {
        return state.skills.find(s => s.id === id);
    },
    skillsPrecent: () => {
        return state.skillsPrecent;
    },
    skillPrecent: (state) => (id) => {
        return state.skillsPrecent.find(p => p.id === id);
    },
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}