/**-------------------------------------------
 * 
 * STORE FOR MAGUS WEAPONS
 * 
 * -------------------------------------------
 */
 const state = {
    weapons: [
        {
            id: 'BUZOGANY_SHADLEKI',
            name: 'Buzogány, shadleki',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 8,
            Te: 13,
            Ve: 14,
            Ce: 0,
            Sp: {
                name: 'k6+1',
                damage: [2, 7]
            },
            weight: '1,8 kg',
            price: '1 arany 3 ezüst',
            description: 'A shadleki buzogány Shadon egy tartományában kifejlesztett, négy baltaéllel és vaskos heggyel ellátot páncélnyitogató eszköz - inkább vágó-, mintsem zúzófegyver.',
        },
        {
            id: 'CSATABARD_EGYKEZES',
            name: 'Csatabárd, egykezes',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 5,
            Te: 12,
            Ve: 11,
            Ce: 0,
            Sp: {
                name: 'k10',
                damage: [1, 10]
            },
            weight: '2 kg',
            price: '6 ezüst',
            description: 'A csatabárd a balta harcban használt rokona. Egy hoszabb rövidebb fa nyélhez erősitenek egy vagy akár két éles pengét.Az egykezes változat fél méteres. A törpék kedvenc fegyvere.',
        },
        {
            id: 'CSATABARD_KETKEZES',
            name: 'Csatabárd, kétkezes',
            TamKor: '1/2',
            Type: 'Szúró/vágófegyver',
            Ke: 0,
            Te: 8,
            Ve: 6,
            Ce: 0,
            Sp: {
                name: '3k6',
                damage: [3, 18]
            },
            weight: '5 kg',
            price: '2 arany',
            description: 'A csatabárd a balta harcban használt rokona. Egy hoszabb rövidebb fa nyélhez erősitenek egy vagy akár két éles pengét.A kétkezes változat egy méteres. A törpék kedvenc fegyvere.',
        },
        {
            id: 'CSATACSAKANY',
            name: 'Csatacsákány',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 5,
            Te: 11,
            Ve: 8,
            Ce: 0,
            Sp: {
                name: 'k10',
                damage: [1, 10]
            },
            weight: '2,5 kg',
            price: '8 ezüst',
            description: 'A csatacsákány, más néven fokos sokban hasonlit a közönséges csákányhoz, ám feje jóval rövidebb, úgy egyarasznyi. Gyakran két hegyel látják el.',
        },
        {
            id: 'HAJITOBARD',
            name: 'Hajitóbárd',
            TamKor: '2',
            Type: 'Szúró/vágófegyver',
            Ke: 9,
            Te: 10,
            Ve: 7,
            Ce: 0,
            Sp: {
                name: 'k6',
                damage: [1, 6]
            },
            weight: '1,2 kg',
            price: '1 ezüst',
            description: 'A hajitóbárd két fő változatban készül, az egyik egy teljesen hagyományos kisbalta, a másik -gyakoribb- változat teljes egészében fémből készül.',
        },
        {
            id: 'KARD_ROVID',
            name: 'Kard, rövid',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 9,
            Te: 12,
            Ve: 14,
            Ce: 0,
            Sp: {
                name: 'k6+1',
                damage: [2, 7]
            },
            weight: '1 kg',
            price: '1 arany',
            description: 'A rövidkard 40-60 cm hosszú, egyenes pengéje mindkét oldalon ki van élezve. Gyakran ijászok második fegyvere.',
        },
        {
            id: 'KARD_HOSSZU',
            name: 'Kard, hosszú',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 6,
            Te: 14,
            Ve: 16,
            Ce: 0,
            Sp: {
                name: 'k10',
                damage: [1, 10]
            },
            weight: '1,5 kg',
            price: '1 arany 5 ezüst',
            description: 'A hosszúkard pengéje 60-80 cm-es, egyenes és kétélű. Álltalában gyalogos katonák fő fegyvere.',
        },
        {
            id: 'KARD_MASFELKEZES',
            name: 'Kard, másfélkezes',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 4,
            Te: 13,
            Ve: 12,
            Ce: 0,
            Sp: {
                name: '2k6',
                damage: [2, 12]
            },
            weight: '2 kg',
            price: '2 arany 5 ezüst',
            description: 'A másfélkezes kard a hosszúkardhoz hasonló, pengéje egyenes, kétélű, ám markolata hozávetőlegesen kétszer olyan hosszú, hogy két kézzel is lehessen fogni.',
        },
        {
            id: 'KARD_LOVAGI',
            name: 'Kard, lovagi',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 2,
            Te: 10,
            Ve: 7,
            Ce: 0,
            Sp: {
                name: '2k6+2',
                damage: [4, 14]
            },
            weight: '3,5 kg',
            price: '3 arany',
            description: 'A lovagi kard a lovagok kedvenc fegyvere. Egyenes, kétélű pengéje 80-120 cm hosszú. A vége lekerekitett, vagy igen tompa szögben csúcsos. Keresztvasa gyakran S alakú.',
        },
        {
            id: 'KARD_PALLOS',
            name: 'Kard, pallos',
            TamKor: '1/2',
            Type: 'Szúró/vágófegyver',
            Ke: 0,
            Te: 6,
            Ve: 2,
            Ce: 0,
            Sp: {
                name: '3k6+2',
                damage: [5, 20]
            },
            weight: '7 kg',
            price: '5 arany',
            description: 'A pallos szintén lovagi fegyver, hossza nem ritkán eléri a két métert, amiből az egyenes, kétélű penge 160 cm. Két kézzel forgatják.',
        },
        {
            id: 'KARD_SZABLYA',
            name: 'Kard, szablya',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 7,
            Te: 15,
            Ve: 17,
            Ce: 0,
            Sp: {
                name: 'k6+2',
                damage: [3, 8]
            },
            weight: '1,5 kg',
            price: '1 arany 6 ezüst',
            description: 'A szablya pengéje 60-80 cm hosszú és enyhén hajlitott. Csak a külső iv van kiélezve. Ivelése miatt sokkal jobban lehet vele vágni, mint az egyenes kardokkal -szúrásra, döfésre ritkán használják.',
        },
        {
            id: 'KARD_DZSENN_SZABLYA',
            name: 'Kard, dzsenn szablya',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 9,
            Te: 20,
            Ve: 17,
            Ce: 0,
            Sp: {
                name: 'k6+3',
                damage: [4, 9]
            },
            weight: '0,5 kg',
            price: '120 arany',
            description: 'A dzsenn szablya szokatlanul keskeny és hosszú, ivelt pengéjű, mágikus úton készitett, ám mágikus tulajdonságokkal nem rendelkező fegyver. Gyakorlatilag törhetetlen.',
        },
        {
            id: 'KARD_JATAGAN',
            name: 'Kard, jatagán',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 7,
            Te: 14,
            Ve: 14,
            Ce: 0,
            Sp: {
                name: 'k6+2',
                damage: [3, 8]
            },
            weight: '0,8 kg',
            price: '1 arany 4 ezüst',
            description: 'A jatagán elnyújtott S alakot formázó, egyélű pengéje rővid, a kiszélesedő hegy ráadás pengéje visszahúzáskor mélyit a seben',
        },
        {
            id: 'KARD_HANDZSAR',
            name: 'Kard, handzsár',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 6,
            Te: 14,
            Ve: 15,
            Ce: 0,
            Sp: {
                name: 'k6+3',
                damage: [4, 9]
            },
            weight: '2 kg',
            price: '1 arany 5 ezüst',
            description: 'A handzsár a dzsadok kedvelt fegyvere. Erősen ivelt, csak a külső éle van kifenve. Jellegzetessége, hogy a penge a keresztvasnál allig tenyérnyi, a hegynél viszont jó másféltenyérnyi széles.',
        },
        {
            id: 'KARD_FEJVADASZ',
            name: 'Kard, fejvadász',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 8,
            Te: 16,
            Ve: 16,
            Ce: 0,
            Sp: {
                name: 'k6+2',
                damage: [3, 8]
            },
            weight: '0,8 kg',
            price: '2 arany',
            description: 'A fejvadászkard speciális, kétmarkolatú fegyver, Gorviktól Kránig szinte mindenütt alkalmazzák. Hossza személyre szabott, alsó, úgynevezett tonfa-markolatnál fogva, az alkarra szoritva épp könyékig ér. Külső élre és hegyre fenik.',
        },
        {
            id: 'KARD_SLAN',
            name: 'Kard, slan',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 8,
            Te: 20,
            Ve: 12,
            Ce: 0,
            Sp: {
                name: 'k10+2',
                damage: [3, 12]
            },
            weight: '1,4 kg',
            price: '100 arany',
            description: 'A Slan kard a kardművész fegyvere. Keskeny enyhén ivelt pengéjének csak a külső ivét fenik ki. Hossza 1,1 méter amiből 30 cm a markolat. Keresztvasa kicsi, kör alakú. Különleges kovácsolási eljárással készül, nagyon nehezen törik, borotvaélles.',
        },
        {
            id: 'KARD_KIGYO',
            name: 'Kard, kigyó',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 6,
            Te: 14,
            Ve: 15,
            Ce: 0,
            Sp: {
                name: 'k10',
                damage: [1, 10]
            },
            weight: '1,4 kg',
            price: '6 arany',
            description: 'A kigyókard szinte kizárólag a Tharr-papok fegyvertárában lelhető fel. Hossza 1,1 méter, kétélű pengéje enyhén hullámos. Egykezes fegyver.',
        },
        {
            id: 'KES',
            name: 'Kés',
            TamKor: '2',
            Type: 'Szúró/vágófegyver',
            Ke: 10,
            Te: 4,
            Ve: 0,
            Ce: 0,
            Sp: {
                name: 'k5',
                damage: [1, 5]
            },
            weight: '0,2 kg',
            price: '50 réz',
            description: 'A kés, bár nem fegyvernek készült, szükség esetén azzá válhat. A legfontosabb részletek, amelyek a tőrtől megkülönböztetik: nincs kereszvasa, és álltalában egyélű.',
        },
        {
            id: 'MARA_SEQUOR',
            name: 'Mara-sequor',
            TamKor: '1',
            Type: 'Szúró/vágófegyver',
            Ke: 7,
            Te: 16,
            Ve: 14,
            Ce: 0,
            Sp: {
                name: '2k6+2',
                damage: [3, 14]
            },
            weight: '1 kg',
            price: '2 arany',
            description: 'A mara-sequor 1 méter hosszúságú, enyhe ivben hajló, hegyénél kétélű, belső pengére fent vágókard. Hagyományos kráni fejvadászeszköz-lásd még sequor.',
        },
        {
            id: 'RAMIERA',
            name: 'Ramiera',
            TamKor: '2',
            Type: 'Szúró/vágófegyver',
            Ke: 8,
            Te: 17,
            Ve: 14,
            Ce: 0,
            Sp: {
                name: 'k6+1',
                damage: [2, 7]
            },
            weight: '0,8 kg',
            price: '2 arany',
            description: 'A ramiera jó 40 cm hosszúságú, levélkeresztbetszetű, keskeny, kétélű és tűhegyes szúrófegyver, a gorviki fejvadászok és orgyilkosok kedvenc eszköze.',
        },
        {
            id: 'SEQUOR',
            name: 'Sequor',
            TamKor: '2',
            Type: 'Szúró/vágófegyver',
            Ke: 8,
            Te: 13,
            Ve: 16,
            Ce: 0,
            Sp: {
                name: 'k6+2',
                damage: [3, 8]
            },
            weight: '0,4 kg',
            price: '1 arany 3 ezüst',
            description: 'A sequor erősen görbitett pengéjű, kétélű és borotvaéles vágótőr. Krán fejvadászainak hagyományos fegyvere. Rajtuk kivül szinte csak egy yllinori embervadász-iskola beavatottai alkalmazzák.',
        },
        {
            id: 'SLAN_CSILLAG',
            name: 'Slan csillag',
            TamKor: '3',
            Type: 'Szúró/vágófegyver',
            Ke: 10,
            Te: 4,
            Ve: 0,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '0,1 kg',
            price: '40 réz',
            description: 'A Slan csillag lapos, sokágú tenyérnyi fémlap, kiválóan lehet dobni.Általában 3-8 csúcsa van.',
        },
        {
            id: 'TOR',
            name: 'Tőr',
            TamKor: '2',
            Type: 'Szúró/vágófegyver',
            Ke: 10,
            Te: 8,
            Ve: 2,
            Ce: 0,
            Sp: {
                name: 'k6',
                damage: [1, 6]
            },
            weight: '0,3 kg',
            price: '1 ezüst',
            description: 'A tőr a legáltalánosabb fegyver szerte Yneven. Rengeteg különböző formája van, de pengéje nem haladja meg a 40 cm-t. Legtöbbször kétélű.',
        },
        {
            id: 'TOR_DOBO',
            name: 'Tőr, dobó',
            TamKor: '2',
            Type: 'Szúró/vágófegyver',
            Ke: 10,
            Te: 11,
            Ve: 2,
            Ce: 0,
            Sp: {
                name: 'k6',
                damage: [1, 6]
            },
            weight: '0,5 kg',
            price: '1 ezüst 50 réz',
            description: 'A dobótőr különlegesen kiképzett tőr, aminek súlyelosztása jó dobhatóságot tesz lehetővé. Kétélű. Keresztvasa kicsi vagy egyáltalán nincs is. Gyakran egyetlen fémdarabból készül, és nem vonják be külön a markolatott.',
        },
        {
            id: 'TOR_SLAN',
            name: 'Tőr, slan',
            TamKor: '2',
            Type: 'Szúró/vágófegyver',
            Ke: 9,
            Te: 14,
            Ve: 6,
            Ce: 0,
            Sp: {
                name: 'k6+2',
                damage: [3, 8]
            },
            weight: '0,8 kg',
            price: '70 arany',
            description: 'A Slan tőr sokban hasonlit a Slan kardra, csak rövidebb. Felépitésében inkább kardra, mint tőrre emlékeztet, de pengéje hossza nem haladja meg a 40 cm-t.',
        },
        {
            id: 'TORKARD',
            name: 'Tőrkard',
            TamKor: '2',
            Type: 'Szúró/vágófegyver',
            Ke: 9,
            Te: 12,
            Ve: 14,
            Ce: 0,
            Sp: {
                name: 'k6+2',
                damage: [3, 8]
            },
            weight: '0,8 kg',
            price: '2 arany',
            description: 'A tőrkard vagy rapir pengéje 80 cm hosszú, keskeny és egyenes. Mindkét oldalán ki van élezve, de főleg döfésre használják. Keskeny pengéje kivételes hajlékonyságot tesz lehetővé, ezért is terjedt el vivóeszközként. Keresztvasa diszes, a markolatot gyakran kosár védi.',
        },
        {
            id: 'BOT_HOSSZU',
            name: 'Bot, hosszú',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 4,
            Te: 10,
            Ve: 16,
            Ce: 0,
            Sp: {
                name: 'k5',
                damage: [1, 5]
            },
            weight: '1,2 kg',
            price: '50 réz',
            description: 'A botot, mint fegyvert, Ynev-szerte alkalmazzák, bár általában lenézik használóját. Niarén és Enoszukén kivül inkább csak furkósbotot forgatnak, ami lehet akár egy frissen vágot husáng is - az előbb emlitett országok harcművészei viszont tökélyre fejlesztették a botok használatának tudományát.',
        },
        {
            id: 'BOT_ROVID',
            name: 'Bot, rövid',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 9,
            Te: 9,
            Ve: 17,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '0,7 kg',
            price: '30 réz',
            description: 'A botot, mint fegyvert, Ynev-szerte alkalmazzák, bár általában lenézik használóját. Niarén és Enoszukén kivül inkább csak furkósbotot forgatnak, ami lehet akár egy frissen vágot husáng is - az előbb emlitett országok harcművészei viszont tökélyre fejlesztették a botok használatának tudományát.',
        },
        {
            id: 'BOT_FURKOS',
            name: 'Bot, furkós',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 2,
            Te: 7,
            Ve: 14,
            Ce: 0,
            Sp: {
                name: 'k6',
                damage: [1, 6]
            },
            weight: '1,3 kg',
            price: 'ingyen',
            description: 'A botot, mint fegyvert, Ynev-szerte alkalmazzák, bár általában lenézik használóját. Niarén és Enoszukén kivül inkább csak furkósbotot forgatnak, ami lehet akár egy frissen vágot husáng is - az előbb emlitett országok harcművészei viszont tökélyre fejlesztették a botok használatának tudományát.',
        },
        {
            id: 'BUZOGANY_EGYKEZES',
            name: 'Buzogány, egykezes',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 7,
            Te: 11,
            Ve: 12,
            Ce: 0,
            Sp: {
                name: 'k6',
                damage: [1, 6]
            },
            weight: '2 kg',
            price: '8 ezüst',
            description: 'A buzogánynak rengeteg változata van. Az alapképlet egyszerű, egy hoszabb-rövidebb nyél végére nehezék kerül, ennek csapása súlyos kárt tesz az ellenfélben. Az egykezes változatoknál ez a nyél 0,5-1 méteres, mig a kétkezesnél az 1,5 métert is elérheti. Az egykezes buzogány különböző változatai szögekkel vagy bordákkal vannak ellátva, netán a nyél és a súly közé egy lánc kerül. A láncos és kétkezes buzogányok szinte mindég tüskézettek.',
        },
        {
            id: 'BUZOGANY_KETKEZES',
            name: 'Buzogány, kétkezes',
            TamKor: '1/2',
            Type: 'Zúzófegyver',
            Ke: 0,
            Te: 7,
            Ve: 6,
            Ce: 0,
            Sp: {
                name: '3k6',
                damage: [3, 18]
            },
            weight: '3 kg',
            price: '1 arany 2 ezüst',
            description: 'A buzogánynak rengeteg változata van. Az alapképlet egyszerű, egy hoszabb-rövidebb nyél végére nehezék kerül, ennek csapása súlyos kárt tesz az ellenfélben. Az egykezes változatoknál ez a nyél 0,5-1 méteres, mig a kétkezesnél az 1,5 métert is elérheti. Az egykezes buzogány különböző változatai szögekkel vagy bordákkal vannak ellátva, netán a nyél és a súly közé egy lánc kerül. A láncos és kétkezes buzogányok szinte mindég tüskézettek.',
        },
        {
            id: 'BUZOGANY_TUSKES',
            name: 'Buzogány, tüskés',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 7,
            Te: 12,
            Ve: 13,
            Ce: 0,
            Sp: {
                name: 'k6+2',
                damage: [3, 8]
            },
            weight: '2 kg',
            price: '1 arany',
            description: 'A buzogánynak rengeteg változata van. Az alapképlet egyszerű, egy hoszabb-rövidebb nyél végére nehezék kerül, ennek csapása súlyos kárt tesz az ellenfélben. Az egykezes változatoknál ez a nyél 0,5-1 méteres, mig a kétkezesnél az 1,5 métert is elérheti. Az egykezes buzogány különböző változatai szögekkel vagy bordákkal vannak ellátva, netán a nyél és a súly közé egy lánc kerül. A láncos és kétkezes buzogányok szinte mindég tüskézettek.',
        },
        {
            id: 'BUZOGANY_TOLLAS',
            name: 'Buzogány, tollas',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 7,
            Te: 12,
            Ve: 13,
            Ce: 0,
            Sp: {
                name: 'k6+1',
                damage: [2, 7]
            },
            weight: '2 kg',
            price: '1 arany 1 ezüst',
            description: 'A buzogánynak rengeteg változata van. Az alapképlet egyszerű, egy hoszabb-rövidebb nyél végére nehezék kerül, ennek csapása súlyos kárt tesz az ellenfélben. Az egykezes változatoknál ez a nyél 0,5-1 méteres, mig a kétkezesnél az 1,5 métert is elérheti. Az egykezes buzogány különböző változatai szögekkel vagy bordákkal vannak ellátva, netán a nyél és a súly közé egy lánc kerül. A láncos és kétkezes buzogányok szinte mindég tüskézettek.',
        },
        {
            id: 'BUZOGANY_LANCOS',
            name: 'Buzogány, láncos',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 4,
            Te: 13,
            Ve: 11,
            Ce: 0,
            Sp: {
                name: 'k6+3',
                damage: [4, 9]
            },
            weight: '2 kg',
            price: '1 arany 2 ezüst',
            description: 'A buzogánynak rengeteg változata van. Az alapképlet egyszerű, egy hoszabb-rövidebb nyél végére nehezék kerül, ennek csapása súlyos kárt tesz az ellenfélben. Az egykezes változatoknál ez a nyél 0,5-1 méteres, mig a kétkezesnél az 1,5 métert is elérheti. Az egykezes buzogány különböző változatai szögekkel vagy bordákkal vannak ellátva, netán a nyél és a súly közé egy lánc kerül. A láncos és kétkezes buzogányok szinte mindég tüskézettek.',
        },
        {
            id: 'CSEPHADARO',
            name: 'Cséphadaró',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 1,
            Te: 6,
            Ve: 5,
            Ce: 0,
            Sp: {
                name: 'k6+1',
                damage: [2, 7]
            },
            weight: '2,5 kg',
            price: '7 ezüst',
            description: 'A cséphadaró a láncos buzogány távoli rokona. Egy hosszú nyélre lánc segitségével egy fél méteres fa- vagy vasnehezéket erősitenek. Néha a nehezéket szögekkel is kiverik.',
        },
        {
            id: 'HARCIKALAPACS',
            name: 'Harcikalapács',
            TamKor: '1',
            Type: 'Zúzófegyver',
            Ke: 5,
            Te: 10,
            Ve: 8,
            Ce: 0,
            Sp: {
                name: 'k6+2',
                damage: [3, 8]
            },
            weight: '3 kg',
            price: '8 ezüst',
            description: 'A harcikalapács a csatacsákány rokona, de itt a hegy nagyon tompa, vagy teljesen elmarad. Törpék kedvelt fegyvere.',
        },
        {
            id: 'ALABARD',
            name: 'Alabárd',
            TamKor: '1/2',
            Type: 'Szálfegyver',
            Ke: 1,
            Te: 14,
            Ve: 15,
            Ce: 0,
            Sp: {
                name: '2k6+2',
                damage: [3, 14]
            },
            weight: '3 kg',
            price: '5 arany',
            description: 'Az alabárdnak rengeteg különböző formája ismert. Egyes példányok döfésre, mások vágásra, megint mások zúzásra szolgálnak. Igen gyakori, hogy az egyes pengeelemeket keverik, igen különös formákat létrehozva. Hoszuk is változó, 2-4 méter közti lehet.',
        },
        {
            id: 'DARDA',
            name: 'Dárda/hajitódárda',
            TamKor: '1',
            Type: 'Szálfegyver',
            Ke: 8,
            Te: 13,
            Ve: 5,
            Ce: 0,
            Sp: {
                name: 'k6+1',
                damage: [2, 7]
            },
            weight: '1,5 kg',
            price: '5 ezüst',
            description: 'A dárda rövid, másfél méteres nyelén keskeny, hegyes penge helyeszkedik el, melynek gyakorta még éle sincs. Súlyelosztása miatt kiválóan dobható.',
        },
        {
            id: 'KOPJA_KONNYU',
            name: 'Kopja, könnyű',
            TamKor: '1',
            Type: 'Szálfegyver',
            Ke: 2,
            Te: 11,
            Ve: 12,
            Ce: 0,
            Sp: {
                name: 'k10',
                damage: [1, 10]
            },
            weight: '2 kg',
            price: '9 ezüst',
            description: 'A könnyű kopját lovasok és gyalogosok egyaránt használják. Nyele 2-3 méteres, feje keskeny hegybe végződik. A fej alá gyakorta zászlót is erősitenek.',
        },
        {
            id: 'KOPJA_LOVAS',
            name: 'Kopja, lovas',
            TamKor: '1/2',
            Type: 'Szálfegyver',
            Ke: 1,
            Te: 15,
            Ve: 0,
            Ce: 0,
            Sp: {
                name: 'k6',
                damage: [1, 6]
            },
            weight: '3,5 kg',
            price: '1 arany',
            description: 'A lovaskopja kizárólag a könnyűlovasság fegyvere. Hossza 3-4 méter, feje viszont rövidebb, mint a könnyű kopjáé. A nyélre gyakran külön kézvédő tárcsát húznak.',
        },
        {
            id: 'KOPJA_NEHEZLOVAS',
            name: 'Kopja, nehézlovas',
            TamKor: '1/3',
            Type: 'Szálfegyver',
            Ke: 0,
            Te: 16,
            Ve: 0,
            Ce: 0,
            Sp: {
                name: '2k10',
                damage: [2, 20]
            },
            weight: '5 kg',
            price: '1 arany 5 ezüst',
            description: 'A nehézlovas kopja jellegzetes lovagi fegyver. Hossza akár az öt métert is elérheti, enyhén kúpos alakú. A kézvédő itt már a kopja fájából van kifaragva.',
        },
        {
            id: 'LANDZSA',
            name: 'Lándzsa',
            TamKor: '1',
            Type: 'Szálfegyver',
            Ke: 4,
            Te: 12,
            Ve: 12,
            Ce: 0,
            Sp: {
                name: 'k10',
                damage: [1, 10]
            },
            weight: '2 kg',
            price: '8 ezüst',
            description: 'A lándzsa a szerte Yneven megtalálható fegyverek egyike - bár minden vidéken más és más az alakja. Feje mindég szélesebb a dárda és kopja fejénél, nyele 2-2,5 méter hosszú. Főleg döfésre használják.',
        },
        {
            id: 'SZIGONY',
            name: 'Szigony',
            TamKor: '1',
            Type: 'Szálfegyver',
            Ke: 4,
            Te: 15,
            Ve: 10,
            Ce: 0,
            Sp: {
                name: 'k10+1',
                damage: [2, 11]
            },
            weight: '2 kg',
            price: '5 ezüst',
            description: 'A szigony a halásznépek egész különleges lándzsája. Hegye olyan keskeny, akár a nyél, és visszahajló tüskék sorakoznak rajta, ami megneheziti eltávolitását a sebből. Másik változatában a hegye két- vagy háromfelé ágazik szét.',
        },
        {
            id: 'BOLA',
            name: 'Bola',
            TamKor: '1',
            Type: 'Egyébb fegyverek',
            Ke: 2,
            Te: 10,
            Ve: 2,
            Ce: 0,
            Sp: {
                name: 'k5',
                damage: [1, 5]
            },
            weight: '0,8 kg',
            price: '40 réz',
            description: 'A bola három rövid kötél- vagy szijdarab, ezeket a szijakat egyik végükön egymáshoz, a másikon ökölnyi nehezékhez rögzitik. A csomónál megfogva, megpörgetve és elhajitva sikeres Támadás esetén a kötelek ( szijak ) az álldozat valamelyik testrészére ( kivátképp a nyak a cél ) tekerednek, a feltekeredő súlyok pedig kábitó, nem ritkán halálos ütést mérnek rá. Az ellenfél -ha egyáltalán talpon marad- a továbbiakban 15-el csökkent VÉ-vel küzd, hisz mozgása nehézkesebbé válik.',
        },
        {
            id: 'DOBOHALO',
            name: 'Dobóháló',
            TamKor: '1/3',
            Type: 'Egyébb fegyverek',
            Ke: 1,
            Te: 8,
            Ve: 4,
            Ce: 0,
            Sp: {
                name: '0',
                damage: [0, 0]
            },
            weight: '1 kg',
            price: '3 ezüst',
            description: 'A dobóháló az abasziszi gladiátorok egyik közkedvelt fegyvere. A hozzávetőleg egy-két négyzetméteres, nem túl sürü szövésű hálót a baljukba tartják összefogva. A megfelelő pillanatban elhajitva a hálót, az a szélére erősitett sulyok hatására kibomlik, az ellenfélre terül, aki minden heves mozdulatával csak jobban belegabalyodik. A háló közepén akad egy külső kötél, amelynek végét a gladiátor mindvégig a kezében tartja. Sikeres támadásnál ezzel még jobban ráhurkolja a hálót az ellenfelére, sikertelen támadásnál ezzel ránthatja vissza fegyverét egy esetleges újrabróbálkozás reményében.A második és az összes többi támadásnál a támadó TÉ-jéből 15 levonódik - mivel hálója egyszer kibomlott már, és harc közben csak tessék -lássék lehet feltekerni. Ugynezen okból a hálóval legfeljebb minden harmadik körben kisérelhet meg támadást a használója. Ha a támadás sikeres, az ellenfél VÉ-je 40-el csökken.',
        },
        {
            id: 'GAROTT',
            name: 'Garott',
            TamKor: '1',
            Type: 'Egyébb fegyverek',
            Ke: 0,
            Te: 5,
            Ve: -20,
            Ce: 0,
            Sp: {
                name: 'k10',
                damage: [1, 10]
            },
            weight: '0,1 kg',
            price: '1 ezüst',
            description: 'A garott vagy fojtóhurok jellegzetes orrgyilkos fegyver. Nem más, mint egy hozzávetőleg 60-80 centiméteres acélhuzal, két végén foggantyúval. A támadó álldozata háta mögé osonva hurkot vett annak nyakába és addig szoritja, mig az meg nem fullad, vagy át nem vágja a torkát a vékony huzal. Az álldozat körönkénk 1k10-Sp-t veszit, mig meg nem hall-vagy ki nem szabadul. Szabadságra igen kicsi az esélye, hiszen szorongatot helyzete miatt kevesett tehet, csak az alábbi levonásokkal támadhat sikeres Akaraterőbróba után: Gyorsaság -5, Ügyesség -5, KÉ -10, TÉ -15, VÉ -20.Persze a támadó sajátossan kiszolgáltatott helyzetben van, mig a gyilkosság elkövetésére öszpontosit, ezért az ő VÉ-je is 20-szal csökken. Ha az álldozat sikeres támadást hajt végre támadója ellen, akkor annak kell Akaraterő próbát tennie, vajon sikerül-e továbbra is kitartania. Természetesen ez a fegyver csakis és kizárólag hátulról és meglepetésszerűen alkalmazható ( azaz csakis ha a Kezdeményezés a támadóé ), nyilt közelharcban semmi haszna. TÉ-je is csak a hátbatámadásra vonatkozik. Túlütés esetén az első körben -és csakis akkor - a garott Ép-t is sebezhet, a hirtelen rántás következtében.',
        },
        {
            id: 'HARITOTOR',
            name: 'Háritótőr',
            TamKor: '2',
            Type: 'Egyébb fegyverek',
            Ke: 8,
            Te: 4,
            Ve: 19,
            Ce: 0,
            Sp: {
                name: 'k6',
                damage: [1, 6]
            },
            weight: '0,3 kg',
            price: '2 ezüst',
            description: 'A háritótőr egy különlegessen széles keresztvasú tőr, amit a vivó álltalában bal kézben forgat, felfogva vele ellenfele csapásait. A markolatot kosár védi. A háritótőr támadásra is használható, bár pengéje gyakran csak hegyes, éle nincs.',
        },
        {
            id: 'KORBACS',
            name: 'Korbács',
            TamKor: '2',
            Type: 'Egyébb fegyverek',
            Ke: 4,
            Te: 6,
            Ve: 0,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '0,5 kg',
            price: '1 ezüst 20 réz',
            description: 'A korbács sok helyen fenyitő eszköz. Egy-másfélméteres fonott bőrszij, vég tüskékkel, nehezékekkel kirakva. Túlütésnél nem sebez Ép-t, hanem kétszeres mennyiségű Fp-t, tekintettel arra, hogy ez az eszköz elsősorban kinozásra készült.',
        },
        {
            id: 'LASSZO',
            name: 'Lasszó',
            TamKor: '1/3',
            Type: 'Egyébb fegyverek',
            Ke: 0,
            Te: 1,
            Ve: 0,
            Ce: 0,
            Sp: {
                name: '0',
                damage: [0, 0]
            },
            weight: '0,6 kg',
            price: '80 réz',
            description: 'A lasszót a legtöbb nép felfedezte magának, bár harcban ritkán használják, hiszen két kéz kell hozzá, védekezésre pedig teljesen alkalmatlan. Ha viszont sikeres támadást hajtanak végre vele, az álldozat Vé-je a továbbiakban 20-szal csökken.',
        },
        {
            id: 'OSTOR',
            name: 'Ostor',
            TamKor: '2',
            Type: 'Egyébb fegyverek',
            Ke: 3,
            Te: 6,
            Ve: 0,
            Ce: 0,
            Sp: {
                name: 'k2',
                damage: [1, 2]
            },
            weight: '0,6 kg',
            price: '1 ezüst',
            description: 'Az ostor nem csak lovak ösztönzésére használható, de harcban és mászásban egyaránt nagy segitség. Harci értéke nem sebzésében rejlik, hanem abban, hogy rátekeredik ellenfelére, megbénitva vagy lefegyverezve azt. Sikeres támadás esetén áldozata Vé-je 15-el csökken.',
        },
        {
            id: 'OKOL',
            name: 'Ököl',
            TamKor: '2',
            Type: 'Egyébb fegyverek',
            Ke: 3,
            Te: 4,
            Ve: 0,
            Ce: 0,
            Sp: {
                name: 'k2',
                damage: [1, 2]
            },
            weight: '0',
            price: '0',
            description: 'Az ököl egy régi mondás szerint mindég kéznél van. Ha más fegyver nincs, ez is megteszi. Igazán mesteri használói a harcművészek. Más nem is okozhat vele Ép sebzést, még túlütés esetén sem.',
        },
        {
            id: 'VASOKOL',
            name: 'Vasököl',
            TamKor: '2',
            Type: 'Egyébb fegyverek',
            Ke: 9,
            Te: 5,
            Ve: 2,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '0,2 kg',
            price: '1 ezüst',
            description: 'A vasököl egy ovális fémdarab, amit megmarkolva jóval nagyobbakat lehet ütni, mint puszta kézzel. Egyes helyeken szögekkel is kiverik.',
        },
    ],
    rangedWeapons: [
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
        {
            id: '',
            name: '',
            TamKor: '',
            Ke: 9,
            Tav: 5,
            Ce: 0,
            Sp: {
                name: 'k3',
                damage: [1, 3]
            },
            weight: '',
            price: '',
            description: '',
        },
    ],
};
const getters = {
    weapons: () => {
        return state.weapons;
    },
    weapon: (state) => (id) => {
        return state.weapons.find(w => w.id === id);
    }
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}