/**-------------------------------------------
 * 
 * STORE FOR MAGUS ARMORS
 * 
 * -------------------------------------------
 */
const state = {
    armors: [
        {
            id: 'POSZTO',
            name: 'Posztó vért',
            material: 'szövet vagy puha bőr',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 1,
            Mgt: 0,     
            weight: '5 kg',
            price: '1 ezüst',
            description: 'A posztóvért a szegényebb gyalogosok viselete. Vastag posztóból vagy puha bőrből készül, és valamenyire felfogja az ütéseket. A lábat combközépig vagy térdig fedi, a kart könyékig.',
        },
        {
            id: 'BOR_SZEGECSELT',
            name: 'Kivert bőr vért',
            material: 'bőr vas szegecsekkel',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 1,
            Mgt: 0,     
            weight: '8 kg',
            price: '4 ezüst',
            description: 'A kivert bőrpáncél puha, de vastag bőrből készül, amit szegecsekkel vernek ki. A felkart és a combot is fedi. Gyakran a combokra rálógó rész középen fel van hasitva, hogy lovagolni lehessen benne.',
        },
        {
            id: 'BOR_KEMENY',
            name: 'Keményitett bőr vért',
            material: 'bőr',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 2,
            Mgt: 2,     
            weight: '7 kg',
            price: '5 ezüst',
            description: 'A keményitett bőrpáncél vagy bőr mellvért olajban kifőzött, vastag bőrből készül, amely az eljárás hatására megkeményedik. Általában csak a felsőtestet védi, mert meglehetősen merev.',
        },
        {
            id: 'BOR_GYURUS',
            name: 'Gyűrűspáncél',
            material: 'bőr vagy szövet, vas karikákkal',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 1,
            Mgt: 1,     
            weight: '12 kg',
            price: '2 arany',
            description: 'A gyűrűspáncél a posztóvért továbbfejlesztett változata, ahol a posztóra vagy bőrre kivülről fém karikákat varrnak. A kivert bőrhöz hasonlóan a combot és a felkart is védi.',
        },
        {
            id: 'BRIGANTIN',
            name: 'Brigantin',
            material: 'Szövet vagy bőr vas lemezekkel',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 3,
            Mgt: 2,     
            weight: '15 kg',
            price: '4 arany',
            description: 'A brigantin alapja szintén a posztóvért, de itt két vékonyabb réteg közé varrnak fém lapocskákat. A felsőtestet védi.',
        },
        {
            id: 'LANCING',
            name: 'Láncing',
            material: 'vas',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 2,
            Mgt: 1,     
            weight: '20 kg',
            price: '10 arany',
            description: 'A láncing egymásba bújtatott kis fémkarikák összesége, mintha csak valaki láncból készitett volna szövetet. Álltalában a felsőtestet és a felkart védi, de egyes változatai egészen csuklóig, illetve térdig lenyúlnak. Gyakran készitenek láncból egyébb, ruhadarabokat utánzó páncélokat is, például nadrágot, csuklyát vagy kesztyűt.',
        },
        {
            id: 'SODRONY_FEM',
            name: 'Vas sodronying',
            material: 'vas',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 3,
            Mgt: 1,     
            weight: '20 kg',
            price: '12 arany',
            description: 'A sodronying sokban hasonlit a láncinghez, de a láncszemek itt finomabbak, és az egymásra szőtt láncok meg vannak tekeredve, igy az egész láncszövet vastagabb, miáltal jobban véd.',
        },
        {
            id: 'SODRONY_ABIT',
            name: 'Abitacél sodronying',
            material: 'abitacél',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 4,
            Mgt: 0,     
            weight: '12 kg',
            price: '30 arany',
            description: 'A sodronying sokban hasonlit a láncinghez, de a láncszemek itt finomabbak, és az egymásra szőtt láncok meg vannak tekeredve, igy az egész láncszövet vastagabb, miáltal jobban véd.',
        },
        {
            id: 'SODRONY_MIT',
            name: 'Mithrill sodronying',
            material: 'mithrill',
            type: 'L',
            typeName: 'könnyű vért',
            Sfe: 5,
            Mgt: 0,     
            weight: '10 kg',
            price: '1200 arany',
            description: 'A sodronying sokban hasonlit a láncinghez, de a láncszemek itt finomabbak, és az egymásra szőtt láncok meg vannak tekeredve, igy az egész láncszövet vastagabb, miáltal jobban véd.',
        },
        {
            id: 'PIKKELY_FEM',
            name: 'Vas pikkelyvért',
            material: 'vas',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 3,
            Mgt: 2,     
            weight: '16 kg',
            price: '20 arany',
            description: 'A pikkelyvért kis kör vagy félkör alakú lemezek sokasága, amelyeket egymáshoz vagy egy posztóhoz erősitenek.',
        },
        {
            id: 'PIKKELY_BRONZ',
            name: 'Bronz pikkelyvért',
            material: 'bronz',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 2,
            Mgt: 2,     
            weight: '18 kg',
            price: '16 arany',
            description: 'A pikkelyvért kis kör vagy félkör alakú lemezek sokasága, amelyeket egymáshoz vagy egy posztóhoz erősitenek.',
        },
        {
            id: 'PIKKELY_ABIT',
            name: 'Abitacél pikkelyvért',
            material: 'abitacél',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 4,
            Mgt: 1,     
            weight: '7 kg',
            price: '50 arany',
            description: 'A pikkelyvért kis kör vagy félkör alakú lemezek sokasága, amelyeket egymáshoz vagy egy posztóhoz erősitenek.',
        },
        {
            id: 'PIKKELY_MIT',
            name: 'Mithrill pikkelyvért',
            material: 'mithrill',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 5,
            Mgt: 0,     
            weight: '5 kg',
            price: '2000 arany',
            description: 'A pikkelyvért kis kör vagy félkör alakú lemezek sokasága, amelyeket egymáshoz vagy egy posztóhoz erősitenek.',
        },
        {
            id: 'LEMEZ_FEM',
            name: 'Vas lemezvértezet',
            material: 'vas',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 3,
            Mgt: 3,     
            weight: '16 kg',
            price: '40 arany',
            description: 'A lemezvértezet hosszabb-rövidebb egymáshoz kapcsolt fémlapokból áll. Ezek álltalában téglalap alakúak, és úgy vannak meghajlitva, hogy kövessék a test vonalát. A válnál az ivelt lemezek átfedik egymást, szijakkal kapcsolódnak, igy nagyobb mozgásszabadságot bisztositanak. A felsőtestet és a felkart védi, egyes esetekben elöl combközépig ér. Alá legtöbbször posztóvértet vagy vastag ruhát vesznek, ami megfelelő kipárnázást bisztosit.',
        },
        {
            id: 'LEMEZ_BRONZ',
            name: 'Bronz lemezvértezet',
            material: 'bronz',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 2,
            Mgt: 3,     
            weight: '18 kg',
            price: '30 arany',
            description: 'A lemezvértezet hosszabb-rövidebb egymáshoz kapcsolt fémlapokból áll. Ezek álltalában téglalap alakúak, és úgy vannak meghajlitva, hogy kövessék a test vonalát. A válnál az ivelt lemezek átfedik egymást, szijakkal kapcsolódnak, igy nagyobb mozgásszabadságot bisztositanak. A felsőtestet és a felkart védi, egyes esetekben elöl combközépig ér. Alá legtöbbször posztóvértet vagy vastag ruhát vesznek, ami megfelelő kipárnázást bisztosit.',
        },
        {
            id: 'LEMEZ_ABIT',
            name: 'Abitacél lemezvértezet',
            material: 'abitacél',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 4,
            Mgt: 2,     
            weight: '7 kg',
            price: '100 arany',
            description: 'A lemezvértezet hosszabb-rövidebb egymáshoz kapcsolt fémlapokból áll. Ezek álltalában téglalap alakúak, és úgy vannak meghajlitva, hogy kövessék a test vonalát. A válnál az ivelt lemezek átfedik egymást, szijakkal kapcsolódnak, igy nagyobb mozgásszabadságot bisztositanak. A felsőtestet és a felkart védi, egyes esetekben elöl combközépig ér. Alá legtöbbször posztóvértet vagy vastag ruhát vesznek, ami megfelelő kipárnázást bisztosit.',
        },
        {
            id: 'LEMEZ_MIT',
            name: 'Mithrill lemezvértezet',
            material: 'mithrill',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 5,
            Mgt: 1,     
            weight: '5 kg',
            price: '4000 arany',
            description: 'A lemezvértezet hosszabb-rövidebb egymáshoz kapcsolt fémlapokból áll. Ezek álltalában téglalap alakúak, és úgy vannak meghajlitva, hogy kövessék a test vonalát. A válnál az ivelt lemezek átfedik egymást, szijakkal kapcsolódnak, igy nagyobb mozgásszabadságot bisztositanak. A felsőtestet és a felkart védi, egyes esetekben elöl combközépig ér. Alá legtöbbször posztóvértet vagy vastag ruhát vesznek, ami megfelelő kipárnázást bisztosit.',
        },
        {
            id: 'MELL_FEM',
            name: 'Vas mellvért',
            material: 'vas',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 4,
            Mgt: 4,     
            weight: '18 kg',
            price: '80 arany',
            description: 'A mellvért egyetlen lemezből kovácsolt páncél, amely többé-kevésbé illeszkedik a testhez. Csak a felsőtestet védi, de az hátul is. Gyakran egészül ki alkar- és lábszárvédőkkel. Álltalában posztóvérttel vagy vastag ruhával hordják a megfelelő kipárnázás miatt. Néha a védtelen helyeken láncruhával egészül ki. Sisakot vagy lánccsuklyát hordanak hozzá.',
        },
        {
            id: 'MELL_BRONZ',
            name: 'Bronz mellvért',
            material: 'bronz',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 3,
            Mgt: 4,     
            weight: '20 kg',
            price: '60 arany',
            description: 'A mellvért egyetlen lemezből kovácsolt páncél, amely többé-kevésbé illeszkedik a testhez. Csak a felsőtestet védi, de az hátul is. Gyakran egészül ki alkar- és lábszárvédőkkel. Álltalában posztóvérttel vagy vastag ruhával hordják a megfelelő kipárnázás miatt. Néha a védtelen helyeken láncruhával egészül ki. Sisakot vagy lánccsuklyát hordanak hozzá.',
        },
        {
            id: 'MELL_ABIT',
            name: 'Abitacél mellvért',
            material: 'abitacél',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 5,
            Mgt: 2,     
            weight: '8 kg',
            price: '200 arany',
            description: 'A mellvért egyetlen lemezből kovácsolt páncél, amely többé-kevésbé illeszkedik a testhez. Csak a felsőtestet védi, de az hátul is. Gyakran egészül ki alkar- és lábszárvédőkkel. Álltalában posztóvérttel vagy vastag ruhával hordják a megfelelő kipárnázás miatt. Néha a védtelen helyeken láncruhával egészül ki. Sisakot vagy lánccsuklyát hordanak hozzá.',
        },
        {
            id: 'MELL_MIT',
            name: 'Mithrill mellvért',
            material: 'mithrill',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 6,
            Mgt: 1,     
            weight: '6 kg',
            price: '8000 arany',
            description: 'A mellvért egyetlen lemezből kovácsolt páncél, amely többé-kevésbé illeszkedik a testhez. Csak a felsőtestet védi, de az hátul is. Gyakran egészül ki alkar- és lábszárvédőkkel. Álltalában posztóvérttel vagy vastag ruhával hordják a megfelelő kipárnázás miatt. Néha a védtelen helyeken láncruhával egészül ki. Sisakot vagy lánccsuklyát hordanak hozzá.',
        },
        {
            id: 'FEL_FEM',
            name: 'Vas félvértezet',
            material: 'vas',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 5,
            Mgt: 6,     
            weight: '30 kg',
            price: '120 arany',
            description: 'A félvértezett mellvértből, teljes karvértből, vaskesztyűből, nyakvédőből, acélsisakból és csataszoknyából áll. A csataszoknya a mellvért alsó részéhez szijakkal kapcsolódó lemezek összesége. Combközépig ér, és csak elöl fedi viselőjét. Posztóvértel vagy vastag ruhával hordják, a megfelelő kipárnázás miatt. Néha láncnadrággal egészül ki.',
        },
        {
            id: 'FEL_BRONZ',
            name: 'Bronz félvértezet',
            material: 'bronz',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 4,
            Mgt: 6,     
            weight: '35 kg',
            price: '100 arany',
            description: 'A félvértezett mellvértből, teljes karvértből, vaskesztyűből, nyakvédőből, acélsisakból és csataszoknyából áll. A csataszoknya a mellvért alsó részéhez szijakkal kapcsolódó lemezek összesége. Combközépig ér, és csak elöl fedi viselőjét. Posztóvértel vagy vastag ruhával hordják, a megfelelő kipárnázás miatt. Néha láncnadrággal egészül ki.',
        },
        {
            id: 'FEL_ABIT',
            name: 'Abitacél félvértezet',
            material: 'abitacél',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 6,
            Mgt: 4,     
            weight: '12 kg',
            price: '300 arany',
            description: 'A félvértezett mellvértből, teljes karvértből, vaskesztyűből, nyakvédőből, acélsisakból és csataszoknyából áll. A csataszoknya a mellvért alsó részéhez szijakkal kapcsolódó lemezek összesége. Combközépig ér, és csak elöl fedi viselőjét. Posztóvértel vagy vastag ruhával hordják, a megfelelő kipárnázás miatt. Néha láncnadrággal egészül ki.',
        },
        {
            id: 'FEL_MIT',
            name: 'Mithrill félvértezett',
            material: 'mithrill',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 7,
            Mgt: 3,     
            weight: '8 kg',
            price: '12000 arany',
            description: 'A félvértezett mellvértből, teljes karvértből, vaskesztyűből, nyakvédőből, acélsisakból és csataszoknyából áll. A csataszoknya a mellvért alsó részéhez szijakkal kapcsolódó lemezek összesége. Combközépig ér, és csak elöl fedi viselőjét. Posztóvértel vagy vastag ruhával hordják, a megfelelő kipárnázás miatt. Néha láncnadrággal egészül ki.',
        },
        {
            id: 'TELJES_FEM',
            name: 'Vas teljes vértezet',
            material: 'vas',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 6,
            Mgt: 8,     
            weight: '35 kg',
            price: '200 arany',
            description: 'A teljes vértezet egész testet beboritó fémlemezekből áll. A sisak pontosan illeszkedik a nyakvérthez, az arcot rostély védi. Csak posztóvértel együtt használják, ami megfelelő kipárnázást bisztosit. Teljes vértezetben harcolni vagy megerőltető tevékenységet végezni legfeljebb 15-20 percig lehet.',
        },
        {
            id: 'TELJES_BRONZ',
            name: 'Bronz teljes vértezet',
            material: 'bronz',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 5,
            Mgt: 8,     
            weight: '40 kg',
            price: '160 arany',
            description: 'A teljes vértezet egész testet beboritó fémlemezekből áll. A sisak pontosan illeszkedik a nyakvérthez, az arcot rostély védi. Csak posztóvértel együtt használják, ami megfelelő kipárnázást bisztosit. Teljes vértezetben harcolni vagy megerőltető tevékenységet végezni legfeljebb 15-20 percig lehet.',
        },
        {
            id: 'TELJES_ABIT',
            name: 'Abitacél teljes vértezet',
            material: 'abitacél',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 7,
            Mgt: 6,     
            weight: '15 kg',
            price: '500 arany',
            description: 'A teljes vértezet egész testet beboritó fémlemezekből áll. A sisak pontosan illeszkedik a nyakvérthez, az arcot rostély védi. Csak posztóvértel együtt használják, ami megfelelő kipárnázást bisztosit. Teljes vértezetben harcolni vagy megerőltető tevékenységet végezni legfeljebb 15-20 percig lehet.',
        },
        {
            id: 'TELJES_MIT',
            name: 'Mithrill teljes vértezet',
            material: 'mithrill',
            type: 'H',
            typeName: 'Nehéz vért',
            Sfe: 8,
            Mgt: 4,     
            weight: '10 kg',
            price: '20000 arany',
            description: 'A teljes vértezet egész testet beboritó fémlemezekből áll. A sisak pontosan illeszkedik a nyakvérthez, az arcot rostély védi. Csak posztóvértel együtt használják, ami megfelelő kipárnázást bisztosit. Teljes vértezetben harcolni vagy megerőltető tevékenységet végezni legfeljebb 15-20 percig lehet.',
        },
    ],
};
const getters = {
    armors: () => {
        return state.armors;
    },
    armor: (state) => (id) => {
        return state.armors.find(a => a.id === id);
    }
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}