/**-------------------------------------------
 * 
 * STORE FOR MAGUS BESTIARIUM
 * 
 * -------------------------------------------
 */
 const state = {
    friendlyNpcs: [
        {
            name: 'Done a Kocsmáros',
            race: 'Ember',
            level: '1',
            exp: '10',
            ERO: '12',
            GYORS: '10',
            UGY: '14',
            ALLO: '10',
            EG: '11',
            SZEP: '13',
            INT: '12',
            AK: '16',
            ASZT: '8',
            KE: '15',
            TE: '27',
            VE: '73',
            CE: '4',
            SP: 'k6',
            SFE: '0',
            EP: '5',
            FP: '9',
            description: 'Nagy darab kocsmáros ember, aki mindenki barátja ( ha fizetnek neki ), de hamar dühbe gurul. Ha harcra kerül sor fegyvert nem használ, csak a keze ügyébe akadó tárgyakat ( kocsmai verekedés af). Alkudni nehéz vele, mert nagyon akaratos, és tudja minek mi az értéke ( értékbecslés af ). Védelmi pénzt fizet a helyi tolvajklánnak, ugyhogy, ha baja esne, az elkövetőknek a tolvajklán bérgyilkosaival gyülne meg a baja. Alvilági kapcsolatai révén jó információforrás lehet, és tudását szívesen éruba bocsájtsa, persze a megfelelő ellenjuttatás fejében.',
            role: 'Elsősorban kocsmáros és információ diller.',
            sablon: 'A vendégeket kiszolgálja, ha kérdezik valamiről rögtön az információ árába akar megalkudni, néha várni kell az infóra egy-két napot, de legtöbbször van valami használható információja, ha véletlenül nincs, akkor sem fizeti vissza az info árát.',
        },
        {
            name: '',
            race: 'Ember',
            level: '1',
            exp: '0',
            ERO: '10',
            GYORS: '10',
            UGY: '10',
            ALLO: '10',
            EG: '10',
            SZEP: '10',
            INT: '10',
            AK: '10',
            ASZT: '10',
            KE: '',
            TE: '',
            VE: '',
            CE: '',
            SP: '',
            SFE: '0',
            EP: '',
            FP: '',
            description: '',
            role: '',
            sablon: '',
        },
    ],
    enemyNpc: [
        {
            name: '',
            race: 'Ember',
            level: '1',
            exp: '0',
            ERO: '10',
            GYORS: '10',
            UGY: '10',
            ALLO: '10',
            EG: '10',
            SZEP: '10',
            INT: '10',
            AK: '10',
            ASZT: '10',
            KE: '',
            TE: '',
            VE: '',
            CE: '',
            SP: '',
            SFE: '0',
            EP: '',
            FP: '',
            description: '',
            role: '',
            sablon: '',
        },
        {
            name: '',
            race: 'Ember',
            level: '1',
            exp: '0',
            ERO: '10',
            GYORS: '10',
            UGY: '10',
            ALLO: '10',
            EG: '10',
            SZEP: '10',
            INT: '10',
            AK: '10',
            ASZT: '10',
            KE: '',
            TE: '',
            VE: '',
            CE: '',
            SP: '',
            SFE: '0',
            EP: '',
            FP: '',
            description: '',
            role: '',
            sablon: '',
        },
    ],
    monsters: [
        {
            name: '',
            race: 'Ember',
            level: '1',
            exp: '0',
            ERO: '10',
            GYORS: '10',
            UGY: '10',
            ALLO: '10',
            EG: '10',
            SZEP: '10',
            INT: '10',
            AK: '10',
            ASZT: '10',
            KE: '',
            TE: '',
            VE: '',
            CE: '',
            SP: '',
            SFE: '0',
            EP: '',
            FP: '',
            description: '',
            role: '',
            sablon: '',
        },
        {
            name: '',
            race: 'Ember',
            level: '1',
            exp: '0',
            ERO: '10',
            GYORS: '10',
            UGY: '10',
            ALLO: '10',
            EG: '10',
            SZEP: '10',
            INT: '10',
            AK: '10',
            ASZT: '10',
            KE: '',
            TE: '',
            VE: '',
            CE: '',
            SP: '',
            SFE: '0',
            EP: '',
            FP: '',
            description: '',
            role: '',
            sablon: '',
        },
    ],
};
const getters = {
    friendlyNpcs: () => {
        return state.friendlyNpcs;
    },
    enemyNpc: () => {
        return state.enemyNpc;
    },
    monsters: () => {
        return state.monsters;
    },
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}