/**-------------------------------------------
 * 
 * STORE FOR MAGUS BARD SPELLS
 * 
 * -------------------------------------------
 */
 const state = {
    bardSpellDescription: [
        'A BÁRD MANA-PONTJAI',
        'A bárd mágiájának titkát hiába keresnénk Ynev beláthatatlan térségein: e kaszt képviselői Mana-pontjaikat-ellentétben az összes többi varászhasználó kaszttal-a Felsőbb Szférák, a csillagok energiájából meritik. Éjszakánként, mikor fények garmadája tündököl az égen, a bárdnak lehetősége nyillik arra, hogy ( maga választotta főhangszerén ) megszólaltassa a mitikus erők öszhangzatát. Az Öszhangzat megszólaltatása mindössze 18 kört vesz igénybe, ez idő alatt a bárd max Mp-jaira kerül. A bárd csak akkor képes az Öszhangzat segitségével Mana-pontokhoz jutni, ha a csillagfény szabad szemmel érzékelhető számára-borús ég alatt, zivatar sötétjében nem jutnak el hozzá az energiák.',
    ],
    bardSpells: {
        dalMagia: {
            name: 'Dalmágia',
            description: [
                'Ynev bárdjai jártassak az Asztrál- és Mentálvarázslatok használatában, ám azokat csak egy különleges módszer, a Dalmágia segitségével képessek alkalmazni. Ennek gyakorlásához énekelniük, vagy muzsikálniuk kell, hogy a dallamok formába öntség, és célba juttassák, a varázslat bennük felgyúlt energiáit.',
                'FIGYELEM! A bárd dalmágiája kizárólag élőlényekre hat! A varázslat eredményességének feltétele az is, hogy a kiszemelt alany hallja a dalt. Amenyiben a célpont süket, vagy - saját jól felfogott érdekében - fülének befogásával védekezik a mágia ellen, a dal hatástalan marad.',
                'A bárdok egyszerre több lényre is alkalmazhatják a Dalmágia varázslatait, s a dal hatókörén belül ők határozhatják meg, ki legyen az, akire a dal varázslatként hat. A dal többi hallgatója nem érzékeli a dallamba ágyazott mágiát: értetlenül állnak majd társaik megváltozott viselkedése előtt. A bárdnak, mint fentebb emlitettük, énekelnie sem feltétlenül szükséges, elég, ha hangszerén játszik, a Dalmágia ez esetben is megidézhető.',
                'Ritkán kerül sor arra, hogy egy bárd csatába használja a dalmágiát - ez alól talán csak a Bátorság dala jelent kivételt. A harcmező zaja ugyanis elnyomja a bárd énekét, s a Dalmágia varázslatainak hatótávolsága a felére csökken. A dalok mágiájának viszont kedvez a csend, melyben a dal messzire elhallatszik, s a hatótáv ennek hatására a kétszeresére nő.',
                'Fontos, hogy a Dalmágia varázslatai tökéletesen összekapcsolódnak a bárd énekmondó, szórakoztató képességeivel. Hisz varázslataik mindaddig észrevétlenek maradhatnak, mig a hatás nyilvánvalóvá nem válik - ám ekkora sokszor már minden hiába. A Dalmágia álldozatait a bárd választhatja meg, tehát a varázslat hatókörén belül tartózkodók közül csak azokra vonatkozik a hatás, akiket a bárd célpontnak szemelt ki. A varázslat megidézéséhez szükséges idő sokszor megegyezik az Időtartammal - ennek oka, hogy a mágia csak addig hat, mig a bárd énekel. Előfordulhat az is, hogy a bárd énekének hatása továbbra is fennmarad, ilyen esetben álldozatonként változik, hogy mennyi idő szükséges a dal emlékének elűtéséhez.',
            ],
            spells: [
                {
                    name: 'Nyugalom dala',
                    typ: 'Asztrális',
                    mana: 1,
                    manaText: '1/célpont',
                    strenght: '5',
                    castTime: '1 perc',
                    effectTime: 'k6 kör',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Asztrális',
                    description: [
                        'A bárd énekének hatására minden olyan lény, amely 10 láb sugarú körön belül tartózkodik, hallja a dalt, Mágiaellenállása pedig sikertelen, elveszti harci kedvét, megnyukszik. Ha ebben az állapotában megtámadják, újra a fegyveréhez kap, s harcolni kezd. Ekkor már nem nyugtatható meg a dallal, sőt az énekesre fog támadni, ha teheti. A bárdok ezzel a varázslattal igen óvatosan bánnak, hiszen a hatás könnyen ellenük forditható. A varázslat erőssége 4E-nként 1 Mana-pont felhasználásával növelhető, Időtartalma a bárd dalának ideje, illetve utánna még 1k6 kör.',
                    ],
                },
                {
                    name: 'Álom dala',
                    typ: 'Mentális',
                    mana: 12,
                    manaText: '12/célpont',
                    strenght: '6',
                    castTime: '3 kör',
                    effectTime: '15 kör utánna természetes alvás',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Mentális',
                    description: [
                        'Ennek az éneknek a hatására a bárd körül 10 lábnyi körzetben tartózkodó lények, ha Mágiaellenálásuk sikertelen, mély állomba merülnek. Az igazi alváshoz a bárd énekét legalább három körig kell hallaniuk, a hatás csak utánna jelentkezik. Ekkor a dalt halló lények elalszanak, s 15 körön át fel sem ébreszthetők, csak mágia segitségével. Utánna az alvás természetessé, az álldozatcsoport közönséges módon felrázhatóvá, fellocsolhatóvá válik. A varázslat erősitése 1E-nként 1 Mp-t igényel.',
                    ],
                },
                {
                    name: 'Zavarodottság dala',
                    typ: 'Asztrális',
                    mana: 35,
                    manaText: '35',
                    strenght: '25',
                    castTime: '1 perc',
                    effectTime: 'végleges',
                    effectRange: '10 láb',
                    resistance: 'Asztrális',
                    description: [
                        'Az egyik legerősebb érzelmekre ható dal, melyel a bárd rendelkezik. Minden érzelmet a visszájára fordithat az álldozatban, ha annak Mágiaellenállása sikertelen volt. Az eddigi szeretetből gyűlölet lesz, a félelemből bátorság, a barátságból ellenszenv és megforditva. Az álldozat 25%-ban beleőrül a hirtelen változásba, s ha nem, akkor is nehéz lesz uj önmagán kiigazodnia. Minden érzelme az ellentétére változott, de a semlegesek, vagy a közel semlegesek nem alakultak át. Egy társat tehát, akihez különösen erős indulatok, érzelmek nem fűzték, most sem fog szeretni vagy gyűlölni. A varázslat a leghétköznapibb érzelmekre is hat, ennek következménye a legkevésbé megfoghatók. Például az a Keleti Barbár harcos, aki eddig egy vagyont fizetett volna a vaddisznópörcért, most, most viszolyogva fogja a kocsmáros ölébe boritani azt. A varázslat 4 Mp-vel erősithető 1 E-nként, csak egy célpontra alkalmazható, a hatása pedig végleges. Megjegyezendő, hogy ha az álldozatra egy másik esetleg ugyanaz a bárd ezt a varázslatot még egyszer ráénekli, a célpont érzelmei eredeti állapotukba rendeződnek vissza.',
                    ],
                },
                {
                    name: 'Bénitás dala',
                    typ: 'Mentális',
                    mana: 8,
                    manaText: '8/célpont',
                    strenght: '7',
                    castTime: '2+k6 kör',
                    effectTime: 'k6 kör',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Mentális',
                    description: [
                        'A bárd dalának hatására minden 10 lábnyi körzetben tartózkodó lény gondolatainak középpontjába a mágikus zene kerül, s ettől teljesen mozdulatlanná válnak. Ehhez a dalt legalább két körig kell hallaniuk, s utánna Mágiaellenállást dobniuk - sikertelenség esetén k6 körig csak a bárd zenéjére figyelnek, s érzéketlenek lesznek minden más jelenség, benyomás iránt. Az igy elbájolt álldozatok, csak a mágia megszűnése után nyerik vissza uralmukat gondolataik felett, vagy abban az esetben, ha egy körben több mint 15 Sp-t sebeznek rajtuk. A dal erősitése 1E-nként 1 Mana-pontot igényel.',
                    ],
                },
                {
                    name: 'Félelem dala',
                    typ: 'Asztrális',
                    mana: 4,
                    manaText: '4/lény',
                    strenght: '6',
                    castTime: '1 perc',
                    effectTime: 'a dal hossza',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Asztrális',
                    description: [
                        'A dal félelmet ébreszt a bárd ellenségeinek szivébe. A bárd szövetségeseire a dal nem hat, igy ők a dal alatt is a bárd közelébe maradhatnak. Az ellenfelek, akik hallják a dalt, Mágiaellenállás dobására jogosultak, s ha elvétik, azonnal menekülni kezdenek az ének forrásától. A varázslat addig tart, mig a bárd énekel, erősiteni pedig 3E-nként 1 Mana-pontért lehet.',
                    ],
                },
                {
                    name: 'Feledés dala',
                    typ: 'Mentális',
                    mana: 20,
                    manaText: '20',
                    strenght: '12',
                    castTime: '3 perc',
                    effectTime: 'egyszeri',
                    effectRange: '10 láb',
                    resistance: 'Mentális',
                    description: [
                        'A dal segitségével egyetlen nap emlékeit törölheti ki álldozatából. Csak a nap dátumára kell koncentrálnia a varázslat alatt, a tartalmát nem szükséges ismernie. Az emlékek, ha a Mágiaellenállás sikertelen, teljesen elvesznek, s a nap üres foltként marad meg az álldozat emlékezetében. Tudni fogja, hogy a nap létezett, de ennél többet nem. Emlékei nem adhatók vissza, de társai elmagyarázhatják neki, mi is történt akkor. Hogy ezt elhiszi, vagy nem az egészen más kérdés. A varázslat Hatótávolsága 10 láb, erősitése 1E-nként 2 Mana-pontot igényel.',
                    ],
                },
                {
                    name: 'Emlékek dala',
                    typ: 'Mentális',
                    mana: 25,
                    manaText: '25',
                    strenght: '12',
                    castTime: '3 perc',
                    effectTime: 'végleges',
                    effectRange: '10 láb',
                    resistance: 'Mentális',
                    description: [
                        'A dal segitségével lehetségessé válik emlékek, élmények elhelyezése az álldozat elméjében. A varázslattal maximálisan egy napi emlék irható be a memóriába, de ehhez üres helyre van szükség. Ez lehet természetes felejtés, de előidézhető a Feledés dalával is. Igy egy nap teljesen átirhatóvá válik valaki emlékezetében. Ha nincs ennyi kiesett emlék, egy-egy napba legfeljebb plusz 15 perc illeszthető be a varázslattal. A varázslat maximális hatótávolsága 10 láb, erősitése pedig 1E-nként 3 Mana-pont segitségével történhet.',
                    ],
                },
                {
                    name: 'Kinok dala',
                    typ: 'Mentális',
                    mana: 4,
                    manaText: '4/kör',
                    strenght: '25',
                    castTime: '1 kör',
                    effectTime: 'a dal hossza',
                    effectRange: 'hallótávolság',
                    resistance: 'Mentális',
                    description: [
                        'A bárd ezen varázslattal fájdalmat okozhat mindazoknak, akik a dalt halják. A fájdalom borzalmas hasogató fejfájásként jelentkezik, majd kinhullámként seper végig az egész testen. A célpont Mágiaellenállásra jogosult a varázslat ellen. Amennyiben az ME dobás sikertelen, az álldozat 1k6 Sp-t veszit körönként. A dal annyi ideig tartható fenn, mig a bárd kivánja, s Mana-pontjai ezt lehetővé teszi. A hatósugár mindég a hallótávolsággal egyezik meg.',
                        'FIGYELEM! A dalt énekelni, nem bömbölni kell, igy a hatósugár - efféle módon - nem növelhető.',
                    ],
                },
                {
                    name: 'Bájolás dala',
                    typ: 'Asztrális',
                    mana: 5,
                    manaText: '5/lény',
                    strenght: '6',
                    castTime: '1 perc',
                    effectTime: '2 óra',
                    effectRange: '10 láb sugarú kör',
                    resistance: 'Asztrális',
                    description: [
                        'A dal segitségével a bárd 10 lábnyi körzeten belül minden hallgatóját barátjává teheti. Ha a hallgatók Mágiaellenállása sikertelen volt, követni, s lehetőségeik szerint segiteni fogják a bárdot. Ha a bárd - fegyverrel vagy mágiával - megtámadja őket, a varázslat hatása semmivé foszlik. Az elbájolt lények mindi igazat fognak válaszolni a bárd kérdéseire, s egy esetleges harmadik féllel vivot harcban is a védelmére kelnek. A varázslat hatóideje 2 óra, erősitése pedig 1E-nként 2 Mana-pont segitségével történhet.',
                    ],
                },
                {
                    name: 'Halál dala',
                    typ: 'Asztrális',
                    mana: 45,
                    manaText: '45/lény',
                    strenght: '15',
                    castTime: '1 kör',
                    effectTime: 'végleges',
                    effectRange: '10 láb sugaró kör',
                    resistance: 'Asztrális',
                    description: [
                        'A bárd legkegyetlenebb fegyvere a lant - szól a mondás Ynev-szerte. A Halál dala valóban pusztulást hozhat minden lényre, aki hallja. Ha a mágiaellenállás sikertelen, az álldozat Asztráltestét megsemmisitő csapás éri, s a lélek szétszakadásának sokkja halált okoz. A célpontnak a bárd 10 lábnyi körzetében kell tartózkodnia, s hallania kell a dalt. A varázslat 1E-nként 4 Mana-pont befektetésével erősithető.',
                    ],
                },
                {
                    name: 'Bátorság dala',
                    typ: 'Asztrális',
                    mana: 7,
                    manaText: '7',
                    strenght: '5',
                    castTime: '1 kör',
                    effectTime: 'a dal hossza',
                    effectRange: '10 láb vagy 100 láb',
                    resistance: '-',
                    description: [
                        'A bárd ezzel a varázslattal társainak harci kedvét növelheti. A varázslat 10 láb körzetben hatásos, s minden a bárdal szövetséges lényre hat. Minden olyan lény KÉ-je 5-tel, TÉ-je 15-tel nő, aki a varázslat pillanatában a dalt hallota, és a Hatótávon belül tartózkodott.',
                        'A varázslat másik alkalmazási módja esetén a Hatótáv 100 lábsugarú kör, melynek területén a dal szinte végigsöpör. Ez a bárddal szövetséges harcosoknak csak a harci kedvét, lelkesedését növeli, s Bátorságukhoz 3-at ad. Ideális varázslat csaták során. A távolság dalával kombinálva különösen ütőképessé válhat.',
                    ],
                },
            ]
        },
        hangMagia: {
            name: 'Hangmágia',
            description: [
                'A megtévesztés ynevi művészei a bárdok, olyannyira, hogy Hang- és Fénymágiájukkal - mely ugyan semmiféle anyagi hatással nem bir - sokszor ütőképesebbek lehetnek, mint más mágiahasználók.',
                'Kevés azon Hangmágiákhoz tartozó varázslatok száma, melyeket önálló alkalmazásra szántak. Ezen varázslatok inkább támogatást bisztositanak a Fénymágia illúzióinak, vagy a Dalmágia hatásait befolyásolják. Összefonódnak a más csoportba tartozó varázslatokkal, tökéletes egységet alkotva velük.',
            ],
            spells: [
                {
                    name: 'Távolság dala',
                    typ: 'Hangmágia',
                    mana: 10,
                    manaText: '10/szorzó',
                    strenght: '5',
                    castTime: '1 szegmens',
                    effectTime: 'a hangositott dal ideje',
                    effectRange: '-',
                    resistance: '-',
                    description: [
                        'Ez a varázslat bármely daltipusú mágiával együtt alkalmazható. A Dalmágia hangerejét többszörösére növeli, igy a hatósugár is nő. A hatósugár 2, 3, 4-szeresére növelhető, méghozzá a kétszeres növelés 10, a háromszoros 20, a négyszeres 30 Mana-pontért stb. A varázslat hatóideje megegyezik a hangositott dal időtartalmával.',
                    ],
                },
                {
                    name: 'Mágia dala',
                    typ: 'Hangmágia',
                    mana: 10,
                    manaText: '10',
                    strenght: '5',
                    castTime: '1 szegmens',
                    effectTime: 'mint az eredeti varázslat',
                    effectRange: '-',
                    resistance: '-',
                    description: [
                        'Ez a dal lehetőséget ad a bárdnak arra, hogy nem daltipusú varázslatokat muzsikálás vagy éneklés leple alatt alkalmazzon. A két varázslat egyszerre lép működésbe, de a Mágia dala csak a másik varázslat megidézéséhez - és annak leplezéséhez - szükséges. Igy észrevétlenül varázsolhat a bárd akár nagy tömegekben is. hiszen a megfigyelők csak annyit tapasztalnak, hogy énekel.',
                    ],
                },
                {
                    name: 'Dalegyesités',
                    typ: 'Hangmágia',
                    mana: 18,
                    manaText: '18',
                    strenght: '5',
                    castTime: '1 szegmens',
                    effectTime: 'mig a varázslatok tartanak',
                    effectRange: '-',
                    resistance: '-',
                    description: [
                        'Ez a varázslat pusztán egy akkord, egy felütés, melynek segitségével két, különböző hatású dalból egy harmadik születik. A zene összetettebé, bonyolultabbá válik, a két varázslat pedig egyszerre alkalmazható. A varázslatok nem idézehtők meg egy azonos körben, először az egyik majd a másik jön létre. A kettő ezek után együtt működik. Ilyen módon konbinálható, például a Nyugtatás dala és az Álom dala- mely utóbbi hatásához e varázslat nélkül önmagában is több körre lenne szükség. A két együtesen ható varázslat minden tekintetben úgy működik, mindha a bárd egyenként használna őket. A Dalegyesitést a Mágia dalával együtt alkalmazva nem daltipusú varázslatok is működhetnek a fenti módon.',
                    ],
                },
                {
                    name: 'Beszélő múlt',
                    typ: 'Hangmágia',
                    mana: 19,
                    manaText: '19',
                    strenght: '1',
                    castTime: '1 perc',
                    effectTime: '15 perc',
                    effectRange: '20 láb sugarú kör',
                    resistance: '-',
                    description: [
                        'A varázslat segitségével a bárd hallhatja egy rég elhunyt személy legfontosabb szavait. Ez egyfajta tudatalatti kapcsolat a lélekkel, de nem kétirányú komunikáció, mivel a bárd nem ért a Nekromanciához. Csak olyan lényeges, a személyhez az idő táblatában is kötődő mondatokat hallhat, melyek az elhunyt legmaradandóbb gondolatai, legfontosabb felfedezései avagy észrevételei voltak. A varázslattal mármilyen egykor élt személy szóra birható, de az mindég saját anyanyelvén fog megszólalni, illetve azon a nyelven, melyen az eredeti szavakat kimondta. A varázslat hatóideje 15 perc, ennél hoszabban senki szavait nem lehet visszaidézni.',
                    ],
                },
                {
                    name: 'Csend',
                    typ: 'Hangmágia',
                    mana: 10,
                    manaText: '10',
                    strenght: '8',
                    castTime: '1 kör',
                    effectTime: '1kör/szint',
                    effectRange: '8 láb sugarú kör',
                    resistance: '-',
                    description: [
                        'A bárd ezzel a varázslattal minden hangot megszüntethet egy adott területen. Ez egy maximum 8 láb sugarú kör, melyen belül semmiféle hang nem lesz észlelhető. Ez a varázslók működését is megneheziti, hiszen a varázslataik hangkomponense mindaddig nem hallható, mig az adott területen belül tartózkodnak, igy minden varázslat megidézése kétszer annyi időbe kerül majd. A varázslat felhasználható lopakodáshoz is, hisz igy a bárd teljesen zaj nélkül közlekedhet. A varázslat hatóideje egy kör szintenkénet.',
                    ],
                },
                {
                    name: 'Zajkeltés',
                    typ: 'Hangmágia',
                    mana: 1,
                    manaText: '1',
                    strenght: '1',
                    castTime: '1 szegmens',
                    effectTime: '1 kör',
                    effectRange: '15 láb',
                    resistance: '-',
                    description: [
                        'Ezzel a rövid ideig tartó varázslattal a bárd tetszőleges zajt idézhet fel egy kiválasztott irányból. A varázslat akkor hasznos, ha a szükséges hang csak egy ajtó nyikorgása, egy tárgy hangos puffanása vagy futó léptek dobogása a távolban. Ez sokkal kevésbé Manaigényes mintha a Hangteremtést használná. A Zajkeltés hossza maximális 1 kör lehet.',
                    ],
                },
                {
                    name: 'Távoli üzenet',
                    typ: 'Hangmágia',
                    mana: 25,
                    manaText: '25',
                    strenght: '25',
                    castTime: '2 perc',
                    effectTime: 'egyszeri',
                    effectRange: 'korlátlan',
                    resistance: '-',
                    description: [
                        'A varázslat segitségével a bárd kommunikálhat egy távoli személyel. A kivánt üzenet nem lehet hoszabb 2 percnél, de a távolság nincs megkötve. A bárdnak csak a személyre kell gondolnia, s elsuttogni az üzenetet. Az adott személy/lény lesz a célpont. és csak ő halja meg az elsuttogot szavakat.',
                    ],
                },
                {
                    name: 'Mágikus hang',
                    typ: 'Hangmágia',
                    mana: 8,
                    manaText: '8',
                    strenght: '1',
                    castTime: '1 kör',
                    effectTime: 'végleges',
                    effectRange: 'érintés',
                    resistance: '-',
                    description: [
                        'A varázslat egy láthatalan hangforrást teremt, mely 25 szó tárolására képes. A szöveget csak akkor mondja ki, ha bárd álltal meghatározott feltételek teljesülnek. Ezek lehetnek időponthoz, személyhez, eseményekhez köthetőek is. Ilzen feltétel lehet például, hogy a hang akkor szólaljon meg, ha valaki elhalad a hangforrás előtt, vagy ha valaki fegyvert ránt a hangforrás álltal őrzött teremben. A rejtett hangforrás legfeljebb kiáltás erősségű hangkibocsájtásra lehet képes, s nem csak beszéd hanem zene is tárolható benne. Ennek hossza 2 perc lehet, s a bárdnak elő kell játszania a később hallani kivánt motivumokat. A varázslat mindaddig várakozik, mig a megszabott feltétel nem teljesül.',
                    ],
                },
                {
                    name: 'Nyelvzavarás',
                    typ: 'Hangmágia',
                    mana: 6,
                    manaText: '6',
                    strenght: '5',
                    castTime: '1 szegmens',
                    effectTime: 'perc/szint',
                    effectRange: '15 láb',
                    resistance: '-',
                    description: [
                        'A bárd ezt a varázslatot bármely lény ellen használhatja. Hatására a személy, vagy kreatúra szavai más nyelven hangzanak el, mint amelyiken az illető kimondta őket. Hogy a jelenség még bizarabb és zavaróbb legyen, a forditás nyelve sem egységes, minden egyes szó más és más nyelven szólal meg. Ez lehetetlenné tehet mindenfajta kommunikációs kisérletet. A mágia ellen nincs ellenállás, mert kizárólag a hangot változtatja meg, ami a lénynek már nem része. A varázslat hatóideje egy perc szintenként, s a célpont legfeljebb 15 láb távolságban tartózkodhat a varázslat megidézésének pillanatában. A varázslat hatása Mágia szétoszlatásával megszüntethető.',
                    ],
                },
                {
                    name: 'Hamis beszéd',
                    typ: 'Hangmágia',
                    mana: 7,
                    manaText: '7',
                    strenght: '2',
                    castTime: '1 szegmens',
                    effectTime: 'perc/szint',
                    effectRange: '15 láb',
                    resistance: '-',
                    description: [
                        'Ezzel a varázslattal a bárd maga beszélhet a kiválasztott célpont helyett. Az álldozat elnémul, a hangok azonban - látszólag legalábbis - változatlanul felőle szólnak. A hihetőség kedvéért a bárdnak figyelnie kell az álldozatát, hiszen ha az beszél, tátog neki is mondani kell valamit, nehogy gyanút keltsen. Ha másik halgat, ajánlatos a bárdnak is hallgatnia. A beszélő, akinek a hangja semmivé enyészet, saját szavait fogja hallani, s a háttérbe nagyon halkan, a bárd beszédét is. A bárd hangja a sajátja marad, igy ha valaki ismeri az álldozat igazi hangját, könnyen rájöhet a csalásra. 8 Manapont befektetésével azonban a bárd ezt is megakadályozhatja: hangja ekkor az álldozatéhoz vállik hasonlatossá. Ennek feltétele az, hogy a bárd legalább egyszer hallja önállóan szólni az illetőt. A varázslat még igy is gyanussá válhat, ha a harmadik fél ismeri az álldozat hanghordozását vagy beszédstilusát, esetleg ért a szájról olvasáshoz. A varázslat hatótávolsága 15 láb, Időtartama 1 perc szintenként.',
                    ],
                },
                {
                    name: 'Rejtett üzenet',
                    typ: 'Hangmágia',
                    mana: 5,
                    manaText: '5',
                    strenght: '1',
                    castTime: '2 perc',
                    effectTime: 'egyszeri',
                    effectRange: 'hallótávolság',
                    resistance: '-',
                    description: [
                        'A varázslat segitségével a bárd hangosan üzenhet akár tömegben is, szavait csak az álltala kiválasztottak fogják megérteni. A mágia megidézése után a bárd 2 percen keresztül beszélhet, mondanivalója érthetetlen marad. Jóllehet hangosan szól, ám a betűk sorrendje teljesen felcserélődik. A bárd szintenként egy lényt kiválaszthat, aki a betűket hibátlan sorrendben hallja, az zavartalanul kapja meg az üzenetet. A varázslat hatósugara a hallótáv, ideje pedig a már emlitett 2 perc.',
                    ],
                },
                {
                    name: 'Hangtanulmány',
                    typ: 'Hangmágia',
                    mana: 2,
                    manaText: '2',
                    strenght: '1',
                    castTime: '3 perc',
                    effectTime: 'végleges',
                    effectRange: '5 láb',
                    resistance: '-',
                    description: [
                        'Szinte mindenben hasonlit a tanulmány nevű varázslathoz. Általa a tanulmányozott lény hangja lesz újra meg újra felhasználható. Ha a varázslatot a bárd konkrét személy hangjának elraktározására használja, kétszer kell megidéznie a varázslatot, ugyanúgy mint a Tanulmány esetén. A varázslat segitségével utánozható lesz a hangerősség, magasság és hanghordozás is, a stilus azonban nem. Ezt a bárdnak kell megtanulnia, el kell lesnie, minden misztikum nélkül. A varázslat folyamatos koncentrációt igényel, ideje 3 perc.',
                    ],
                },
                {
                    name: 'Hangutánzás',
                    typ: 'Hangmágia',
                    mana: 4,
                    manaText: '4',
                    strenght: '1',
                    castTime: '3 szegmens',
                    effectTime: '15 perc/szint',
                    effectRange: '35 láb',
                    resistance: '-',
                    description: [
                        'A varázslat hasonlit a lényteremtéshez, csak éppen hangal hajtja végre a bárd. A kiválasztott lény hangmintája tetszőleges pontból szólaltatható meg, s ez nemcsak hangszálak álltal keltett rezgések, de a lény álltal csapott egyébb zajokat is magába foglalja. A felfedezési esélyek megegyeznek a Lényteremtésben leirtakkal, s a Hangtanulmány varázslat is ugy hat rá, mint a Tanulmány a Lényteremtére. A varázslat bármilyen lény hangját létrehozhatja, s a bárdnak csak akkor kell rá koncentrálnia, ha a teremtett hang beszél. A bárd csak álltala ismert nyelveket használhat a varázslatban, s ennek szavait is meg kell formálnia elméjében, csak akkor kerülhetnek kimondásra. A varázslat 15 percig tartható fenn szintenként, hatótávolsága 35 láb, s a lényteremtéssel együtt alkalmazva mindég követi a megalkotott képet, ha a bárd úgy kivánja.',
                    ],
                },
                {
                    name: 'Hangorkán',
                    typ: 'Hangmágia',
                    mana: 22,
                    manaText: '22',
                    strenght: '4',
                    castTime: '4 szegmens',
                    effectTime: '1 szegmens',
                    effectRange: '12 láb sugarú kör',
                    resistance: 'Állóképesség-próba',
                    description: [
                        'A bárd ezzel a varázslattal hatalmas erejű hangot hoz létre, mely orkánként söpör végig a környéken, s még mérföldekkel távolabb is hallható. A varázslattal szemben minden hallószervel rendelkező élőlénynek Akaraterő-próbát kell tennie. Ha ez sikertelen 2k6 Sp-t veszitenek és örökre megsüketülnek. A sikeresen ellenállók csak k6 Sp-t veszitenek, s mindössze k10 percre válik hallásuk használhatatlanná. A 12-nél kevesebb maximális Fp-jű lények, ha talpon maradtak egyáltalán, menekülni kezdenek a borzalmas hang forrása elől, s 5 körig legjobb tudásuk szerint távolodnak a bárdtól. A varázslat hatóköre 12 láb, minden azon belül tartózkodó lényre hat - kivéve természetesen a bárdot.',
                    ],
                },
                {
                    name: 'Hangcsapás',
                    typ: 'Hangmágia',
                    mana: 3,
                    manaText: '3',
                    strenght: '1',
                    castTime: '1 szegmens',
                    effectTime: '1 szegmens',
                    effectRange: '50 láb',
                    resistance: '-',
                    description: [
                        'A varázslattal a bárd szörnyű, metsző hangot hallat, mely bántja a közelében tartózkodók fülét, s több száz lábra is elhallatszik. A hangforrás szomszédságában, minden nem mágikus üvegtárgy és tükör szilánkokra törik. A varázslat 50 lábnyi körön belül bármilyen távolságban megidézhető, az üvegtörés hatósugara 10 láb + 1/2 láb szintenként. A hang egy szegmensen keresztül hallható.',
                    ],
                },
                {
                    name: 'Hangidézés',
                    typ: 'Hangmágia',
                    mana: 8,
                    manaText: '8',
                    strenght: '1',
                    castTime: '5 kör',
                    effectTime: '2 perc/szint',
                    effectRange: '10 láb',
                    resistance: '-',
                    description: [
                        'A bárd ezzel a varázslattal valamely rég történt esemény hangjait idézheti fel. Csak olyan események jöhetnek szóba, melyeknek a bárd fültanúja volt: a hangok az emlékezetéből származnak. A varázslat folyamatos koncentrálást igényel, tartalma alatt szokványos tevékenység nem végezhető - kivételt csak az éneklés és muzsikálás jelent, melyekre a bárd ilyen állapotban is képes. A varázslat segitségével a bárd, miközben hősi éneket dalol, megidézheti annak valódi hangjait is, ezzel szinesitve előadását. A varázslat hatóideje 2 perc szintenként.',
                    ],
                },
                {
                    name: 'Bűvhangszer',
                    typ: 'Hangmágia',
                    mana: 4,
                    manaText: '4',
                    strenght: '1',
                    castTime: '1 szegmens',
                    effectTime: '10 perc/szint',
                    effectRange: 'a bárd hangszere',
                    resistance: '-',
                    description: [
                        'A bárd hangszerének hangját változtathatja e varázslat segitségével. A hangszer bármilyen, a bárd álltal ismert hangszer hangján megszólalhat, s tökéletesen utánozza azt. A bárd új hangokat, hangzást is létrehozhat, ha talál egy viszonyitási hangot, amiből a dallamskála létrejöhet. Lehet ez madárhang, vagy akár távoli, ismeretlen hangszer egy-egy dallamfoszlánya is. További Mana-pontok felhasználásával a hangzás megsokszorozható, avagy más hangszerek is szólhatnak a mű alatt. A megsokszorozás több zenész hatását idézi, s plusz szólamonként 2 Mana-pontba kerül. Ha a szólamot a bárd szeretné eltolni, azaz kánont létrehozni, erre is van módja, de ennek ára további két Mana-pont. Ha más hangszer is kapcsolódik a zenedarabba, ennek létrehozása 3 Mp, szólamhoz csatolása 2 Mp, ami összesen 5 Mp-t jelent. Ha az új hangszer szólama kánonban kerül felhasználásra, ez további 2 Mp, de az új eszköz szólamai is sokszorozhatóak 2 Mp-ért. Igy egy igazi, magas Tapasztalati Szintű bárd 10-15 ember helyett is játszhat több, egymástól különböző hangszeren, kánonhatást keltve. A varázslat hatóideje 10 perc szintenként.',
                    ],
                },
                {
                    name: 'Hangteremtés',
                    typ: 'Hangmágia',
                    mana: 2,
                    manaText: '2',
                    strenght: '1',
                    castTime: '1 szegmens',
                    effectTime: '5 perc/szint',
                    effectRange: '12 láb sugarú kör',
                    resistance: '-',
                    description: [
                        'A varázslattal a bárd egy tetszőleges pontból hangot bocsájthat ki. Ez lehet a saját hangja, de bármilyen természetes, vagy mesterséges zaj is, esetleg más nyelvű beszéd, vagy állathang is. A kijelőlt hangforrásnak 12 láb sugarú körön belül kell lennie. Hangja nem lehet harsányabb a kiáltásnál, de ezt a megkötést leszámitva, a bárd azt tesz, amit akar. A varázslatra végig koncentrálnia kell, az Időtartam maximum 5 perc szintenként.',
                    ],
                },
                {
                    name: 'Hangkivetités',
                    typ: 'Hangmágia',
                    mana: 6,
                    manaText: '6',
                    strenght: '1',
                    castTime: '1 szegmens',
                    effectTime: '1 óra',
                    effectRange: '50 láb',
                    resistance: '-',
                    description: [
                        'Hatása a Hangteremtés varázslatáéra emlékeztett, jellegében azonban különbözik attól. A bárd ebben az esetben nem teremt hangot, hanem saját és közvetlen környezetének hangjait vetiti ki más helyre. A varázslat önnmagában is használható, de különös előszeretettel alkalmazzák a bárdok a Fantom varázslattal együtt. Ekkor ugyanis a képhez a hang is megteremtődik, s az illúzió majdnem tökéletessé válik. Adódhatnak persze apróbb hibák, például az illuzió száraz úton halad, mialatt a bárd mély pocsolyába lép- ilyenkor ugyanis a locsanás hangjának is az illuzió lezs a forrása, s ez bizony gyanus lehet. A varázslat hatósugara 50 láb, Időtartama pedig 1 óra.',
                    ],
                },
            ]
        },
        fenyMagia: {
            name: 'Fénymágia',
            description: [
                'A bárd varázslatainak többsége ebbe a csoportba tartozik. A varázslók álltal lenézett illuziók ezek, melynél veszedelmesebb fegyver kevés akad a mágiát nem ismerők ellen.',
                'A Fénymágia az Elemi Mágia sajátos változata, mely a megidézett fényt nem elemi formájában idézi meg, hanem a bárd kivánta minta szerint alakitja át. Az erősitésnek nem kell negynak lennie, igy az illuziók viszonylag kevés Mana-pont befektetésével is kápráztatók lehetnek. A Fénymágia varázslatai sohasem hatnak másra, csak a fénysugarakra, igy minden álltaluk létrehozott kép valódi természete könnyen felismerhető, ha valaki megkiséri megérinteni őket. Keze ugyanis átsiklik a fényjátékon. Ám az illuzió felismerése nem jelenti azt, hogy a kép eltűnik. Az illuzió továbbra is ott marad, s a mögötte található tárgyakat eltakarja.',
                'Az illúziók ellen leginkább a varázslók védettek, mert tapasztalatuk oly nagy a létező anyaggal kapcsolatos mágiában, hogy a Fénymágia álltal létrehozott képek nem tévesztik meg őket egykönnyen. Minden efféle varázslat felfedezésének esélye számukra 30%. Ha a varázsló megdobja ezt a százalékot, első pillantásra felismeri az apró pontatlanságokat a fény alkotta képben, s rájön illúzió voltára. Azoknál a varázslatoknál, ahol felfedezési esély szerepel, a varázslók 30%-a ehhez hozzáadódik.',
            ],
            spells: [
                {
                    name: 'Láthatatlanság',
                    typ: 'Fénymágia',
                    mana: 4,
                    manaText: '4',
                    strenght: '1',
                    castTime: '1 szegmens',
                    effectTime: '1 óra',
                    effectRange: '-',
                    resistance: '-',
                    description: [
                        'Ez a varázslat kétélű fegyver. Alkalmazásakor a bárd fizikális látással ( normál, infra, ultra ) nem felfedezhető. A fény egyszerűen átsiklik rajta, ebből adódik azonban kellemetlen következménye, hogy a bárd számára is láthatatlan lesz : nem képes érzékelni azt. Röviden szólva a varázslat idejére megvekul. A varázslat ideállis lehet rövid rejtőzködésre vagy olyan alkalommal, mikor a mozdulatlanság, a világtalanság nem okoz gondot az alkalmazónak. A varázslat maximum egy órán át tart, addig a bárdot csak hang, asztrális illetve mentális jelenlét alapján lehet felfedezni.',
                    ],
                },
                {
                    name: 'Aura',
                    typ: 'Fénymágia',
                    mana: 3,
                    manaText: '3',
                    strenght: '1',
                    castTime: '1 szegmens',
                    effectTime: '10 kör',
                    effectRange: '10 láb',
                    resistance: '-',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
            ]
        },
        egyebbMagia: {
            name: '',
            description: [
                '',
            ],
            spells: [
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
                {
                    name: '',
                    typ: '',
                    mana: 0,
                    manaText: '',
                    strenght: '',
                    castTime: '',
                    effectTime: '',
                    effectRange: '',
                    resistance: '',
                    description: [
                        '',
                    ],
                },
            ]
        },
    },
};
const getters = {
    bardSpellDescription: () => {
        return state.bardSpellDescription;
    },
    bardSpells: () => {
        return state.bardSpells;
    },
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}