/**-------------------------------------------
 * 
 * STORE FOR MAGUS PAP SPELLS
 * 
 * -------------------------------------------
 */
 const state = {
    kisArkanum: [
        {
            name: 'A hatalom szava',
            sfera: ['L', 'H', 'E', 'T'],
            sferaText: 'Lélek, Halál, Élet, Természet',
            mana: 15,
            manaText: '15',
            strenght: '35',
            castTime: '1 szegmens',
            effectTime: 'Speciális',
            effectRange: '30 láb sugarú kör',
            resistans: 'Asztrális',
            description: [
                '-A látszat csal, az univerzum a hazugságok sokaságára épül- tartja egy ősi kyr bölcsesség. Az igazi hatalommal bírók nem ritkán titkolják, mire képesek valójában. Egyszerű, szerény megjelenésük nem árulkodik erejükről, s ez megtévesztő lehet. Persze a valódi hatalom kisugárzása szinte tapinthatóan árad birtokosából, s ezt látja minden nyitott szemmel, tiszta elmével járó lény. Ám a sok nagyhangú, felületes, csupán a látszatra adó szerencsétlen gyakorta már csak akkor veszi észre, kivel került szembe, kit sértett vérig, mikor már késő, visszakozni lehetetlen. Az efféle fickók megtorpantására szolgál a Hatalom szava.',
                'A varázslat egyetlen szó kimondásából áll, mely tisztán és érthetően hallatszik 30 láb körzetben. A papnak közben fel kell mutatni szent jellképét. Mindenki, aki ezen területen belül tartózkodik, szembesül a pap valódi hatalmával ( Nevezetesen: megismeri a Tapasztalati szintjét, főbb harcértékeinek nagyságrendjét-de nem pontos értékeket ), és dudatára ébred annak, hogy mi mire képes az. A varázslat sohasem hazudik és nincs kényszerítő ereje. Ha a támadók nem riadnak meg, a papnak más eszközöket kell keresni megfékezésükre. ( NJK esetében a Bátorság annyival csökken amennyi a pap tapasztalati szintjének kétszerese, ha nullára csökken a Bátorság, az NJK rettegni fog a paptól ) A varázslat nem evilági lényekre, vagy élőholtakra nem fejti ki hatását.',
                'A felhasznált MP-k megduplázásával megkétszerezhető a mágia erőssége, vagy hatótávolsága. Háromszor annyi Mp rááldozásával megháromszorozható, stb.'
            ],
        },
        {
            name: 'Áldás',
            sfera: ['L', 'H', 'E', 'T'],
            sferaText: 'Lélek, Halál, Élet, Természet',
            mana: 3,
            manaText: '3',
            strenght: '5',
            castTime: '5 szegmens',
            effectTime: '2 kör/szint vagy 1 hónap/szint',
            effectRange: 'Érintés',
            resistans: '-',
            description: [
                'Az egyik legalapvetőbb papi mágia. Alkalmazásokor a pap istene jóindulátát, segítségét kéri és kapja. Mindazok, akikre a pap kiterjeszti az áldás hatását ( 1 személy / szint ) - hacsak jellemük nem gyökeressen ellentéte a pap vallásának jellemével - megerősödnek eltökéltségükben, a varázslat időtartalma alatt optimisták, jókedvűek és bátrak lesznek. Ez idő alatt minden Harci Értékükhöz +5 járul, akárcsak az Asztrális és Mentális mágiaellenállásukhoz, míg a rájuk irányzott Átkok ellen +50-nel dobnak ME-t. A varázslat nem evilági vagy élőholt lényekre nem fejti ki hatását.',
                'Az Áldás segítségével felszentelt étel és víz tiszta és fogysztható lesz - amennyiben mérgezett volt, úgy látványossan megposhad, undorítóvá válik. Azok a tárgyak amelyeket a pap megáldott, 1 hónap/szint időtartam alatt nem porosodnak, nem fog rajtuk a rozsda és színüket sem veszítik.',
                'A megáldott tárgyból a fent említett időtartam alatt sugárzó mágia - azonos varázslaterősség mellett - semlegesíti az Átok hatását, ám ezzel szertefoszlik, s a tárgy továbbiakban közönséges, mágiától mentes dolognak minősül.',
            ],
        },
        {
            name: 'Mágia kifürkészése',
            sfera: ['L', 'H', 'E', 'T'],
            sferaText: 'Lélek, Halál, Élet, Természet',
            mana: 5,
            manaText: '5',
            strenght: '10',
            castTime: '5 szegmens',
            effectTime: 'Azonnali',
            effectRange: 'Kijelölt varázslat',
            resistans: '-',
            description: [
                'Rendkívül hasznos varázslat, pompás kiegészítője a Mágia szétoszlatásának. Segítségével a pap megtudja, hogy az elpusztításra szánt varázslat milyen erősítésű. Ily módon nem kell találomra varázsolnia, nem vesznek ell a Mp-k, ha rosszul méri fel a lehetőségeket a pap.',
                'A varázslók által létrehozott varázslatokkal szemben haszontalan.',
            ],
        },
        {
            name: 'Mágia szétoszlatása',
            sfera: ['L', 'H', 'E', 'T'],
            sferaText: 'Lélek, Halál, Élet, Természet',
            mana: 7,
            manaText: '7',
            strenght: '5',
            castTime: '1 kör',
            effectTime: 'Azonnali',
            effectRange: 'Kijelölt varázslat',
            resistans: '-',
            description: [
                'Ezt a mágiaformát alkalmazva a pap képessé válik - a varázslói varázslatok kivételéve - más mágiák hatásainak megszüntetésére. Természetesen csakis abban az esetben, ha a varázslatra felhasznált mana-pontok száma meghaladja a szétoszlatásra szánt varázslatba fektetett mana-pontok számát. Varásztárgyak mágikus hatása ily módon nem semlegesíthetők. A varázslatot csak az adott varázslat időtartalma alatt lehet szétoszlatni, annak következményei nem befolyásolhatók. Amennyiben nem nyilvánvaló, hogy mágikus hatásról van szó, a szétoszlatáshoz feltétlenül szükséges a ?ágiaismeret képzettség alapfokú ismerete.',
                'A varázslat hátulütője , hogy elképesztő megterhelést ró végrehajtójára. A pap ugyanis annyi körön keresztül képtelen lesz a varázslásra, amekkora erősítésű a szétoszlatott mágia volt.',
            ],
        },
        {
            name: 'Szent fény',
            sfera: ['L', 'H', 'E', 'T'],
            sferaText: 'Lélek, Halál, Élet, Természet',
            mana: 3,
            manaText: '3',
            strenght: '15',
            castTime: '1 szegmens',
            effectTime: '3 kör/szint',
            effectRange: 'Speciális',
            resistans: '-',
            description: [
                'Nevezik az Istenek Vezérlő Tüzének is. A pap a varázslat végrehajtásával fényt gyújt valamely tárgyon vagy helyen. E fény 15 cm sugarú gömbként, kékesen ragyogva világít. A szent fény csak olyan tárgyon vagy helyen - személyen nem!- jelenik meg, melyet szertartás varázslat segítségével felszenteltek. A mágia 3 fáklyányi világosságot ad a legnagyobb sötétségben is, s időlegesen eloszlatja a Sötétség-varázs hatását. A Szent fény csak erősebb Mágia szétoszlatásával szüntethető meg, egyébb módon eloltani lehetetlen.',
                'A Fény által bevilágított területen sem ultra-, sem infralátás nem működik.',
                'A varázslat ideje alatt figyelmezteti a papot, ha olyan helyre téved, amelynek vallásával ellentétes jellemű kisugárzása van, illetve ha veszély leselkedik rá. Ilyenkor színe egyre mélyül, majd vörös árnyalatba csap át. A Szent Fény a varázslat időtartalma alatt - további MP-ok felhasználása nélkül - a pap akaratának megfelelően bármikor kioltható és újraéleszthető.',
                'A Mana-pontok többszörözésével a mágia erőssége, valamint időtartama növelhető meg.',
            ],
        },
        {
            name: 'Szertartás',
            sfera: ['L', 'H', 'E', 'T'],
            sferaText: 'Lélek, Halál, Élet, Természet',
            mana: 3,
            manaText: '3',
            strenght: '500',
            castTime: 'Speciális',
            effectTime: 'Végleges',
            effectRange: 'Speciális',
            resistans: '-',
            description: [
                'A papi mágia legalapvetőbb kelléke.A legelső varázslat amit egy papnak megtanítanak, s az átlagemberek leggyakrabban csupán a mágia ezen formájával találkoznak az életük folyamán. Habár vallásonként változnak formái, s egyes hitek többfélét ismernek, mint mások, az alább következő hét szertartást mind alkalmazzák. ( A leírás pusztán egyszerű vázlatai az eseményeknek ).',
                '1. Templomszentelés:',
                'Új oltár, szentély vagy templom felavatásakor celebrálják. A felépített helyet a papnak körbe kell járnia, s fenhangon idéznie a szertartás szövegét. A templom vagy szentély ezek után már alkalmas fohászkodásra, áldozat bemutatására, s otthont, támogatást nyújt az azonos hívőknek.',
                '2. Névadás:',
                'Ezen szertartás alatt adatik az újszülötnek a név, melyet élete során viselnie kell.',
                '3. Felszentelés:',
                'A szertartással szenteltvíz és más szentelt tárgy készíthető.',
                '4. Áldozat:',
                'Az istentől függő áldozati formula és rituális szöveg, melyet az Áldozat bemutatása közben mormolnak.',
                '5. Áldás - étel, ital:',
                'A pap megszenteli az elé tett ételt és italt. Hosszú szertartások alatt, illetve több napos mágia használatakor kizárólag efféle étket fogyaszthat, ilyen itallal olthatja szomját. Az eljárás nem fedi fel, hogy az étel vagy ital mérgezett-e.',
                '6. Áldás - föld, termés:',
                'Leginkább földművesek megsegítésére használatos eljárás. Segítségével a következő év termése bisztosíttatik, s nem kell nagyobb természeti katasztrófától sem tartani a megszentelt területen. Legalábbis olyantól nem, amit a pap istene idézne elő.',
                '7. Összeesketés: ',
                'A szertartással házasság köttetik.',
                'A szertartások lefolyása vallásonként nagyon eltérő lehet, így ezek ismertetésére itt nem térünk ki. A papok a legtöbb fenti szertartásokhoz különleges, felszentelt füstölőket, istenüknek szentelt tárgyakat és egyébb kultikus segédeszközöket használnak.',
            ],
        },
        {
            name: 'Aszkézis',
            sfera: ['L', 'H', 'E', 'T'],
            sferaText: 'Lélek, Halál, Élet, Természet',
            mana: 12,
            manaText: '12',
            strenght: '-',
            castTime: '1 óra',
            effectTime: '1 nap',
            effectRange: 'Önmaga',
            resistans: '-',
            description: [
                'A varázslat a papok bűntől és földi kisértéstől való megtisztulását segíti elő. Új gondolatokat ébreszt, közelebb hozza a papot istenéhez, segíti elszakadni a világi örömök gyarlóságától.',
                'Első lépésben a papnak tökéletesen el kell szakadnia a mindennapi valóságtól, egyedül kell maradnia gondolataival.A papnak a nap elején, lehetőleg napkeltekor kell használnia a varázslatot, mely egy órás aktív fohászkodást és rituális szövegek kántálását jelenti. Ezek után a napot imátkozásra és meditációra kell szentelnie.',
                'At Aszkézist addig kell folytatnia, míg istene jónak tartja. Ha véget vethet önnön sanyargatásának, jelet kap istenétől. A varázslatot minden nap elején használni kell.',
            ],
        },
        {
            name: 'Asztrálpillantás',
            sfera: ['E', 'L'],
            sferaText: 'Élet, Lélek',
            mana: 7,
            manaText: '7',
            strenght: '5',
            castTime: '5 szegmens',
            effectTime: '5 kör',
            effectRange: 'Érintés',
            resistans: 'Asztrális',
            description: [
                'A litánia segítségével a pap pebillantást nyer az Asztrálsíkra, s megfigyelheti, hogy a vizsgált személy asztrálteste miként viselkedik. Megállapíthatja, hogy fenyegeti-e valamiféle veszély, esetleg valamely, csupán az asztrálsíikon létező teremtmény fenyegeti, esetleg annak befolyása alatt áll. A varázslat ideje alatt lehetőség nyílik annak megállapítására, hogy milyen erős e teremtmény, s hogy elűzéséhez, esetleg kibékítéséhez mely erőkhöz kell fordulnia. Amennyiben az áldozat beleegyezik abba, hogy rajta ezt a fürkészést végrehajtsák, nem kell mágiaellenállást tennie, ellenkező esetben a papnak le kell küzdenie az illetőt óvó erőket. A varázslat 2 Mp-ért 1-gyel erősíthető. A varázslat érdekessége, hogy a pap saját magán nem tudja végrehajtani.',
            ],
        },
        {
            name: 'Bénítás',
            sfera: ['L'],
            sferaText: 'Lélek',
            mana: 12,
            manaText: '12',
            strenght: '15',
            castTime: '3 szegmens',
            effectTime: '1 kör/szint',
            effectRange: '5 láb',
            resistans: 'Mentális',
            description: [
                'A pap ezzel a varázslattal részlegesen béníthatja az ellenfél mozgásirányító központját. Rá kell mutatni a kiszemelt álldozatra, majd - szent jelképével a kezében - ki kell mondani a varázslat megidézéséhez szükséges szavakat. A mágia hatására, ha az ME sikertelen volt, görcsös állapotba kerül, a következő módosítókkal: Erő: -8, Gyorsaság: -8, Ügyesség: -8, KÉ: -30, TÉ: -40, VÉ: -35, CÉ: -15, varázsolni pedig nem lehetséges. A varázslat erőssége 2 Mp-ért 1E-vel növelhető, ám az időtartam meghosszabítására nincs lehetőség.',
            ],
        },
        {
            name: 'Csapás',
            sfera: ['T', 'L', 'H'],
            sferaText: 'Természet, Lélek, Halál',
            mana: 8,
            manaText: '8',
            strenght: '1',
            castTime: '1 szegmens',
            effectTime: 'egyszeri',
            effectRange: '15 láb',
            resistans: '-',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
    ],
    kisArkanumEgyedi: [
        {
            name: '',
            istenId: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
    ],
    nagyArkanum: [
        {
            name: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
    ],
    nagyArkanumEgyedi: [
        {
            name: '',
            istenId: '',
            sfera: [],
            sferaText: '',
            mana: 0,
            manaText: '',
            strenght: '',
            castTime: '',
            effectTime: '',
            effectRange: '',
            resistans: '',
            description: [
                '',
            ],
        },
    ],
};
const getters = {
    kisArkanum: () => {
        return state.kisArkanum;
    },
    kisArkanumCurrentAll: (state) => (data) => {
        return state.kisArkanum.filter(s => s.sfera.some(s => data.sfera.includes(s)));
    },
    availableKisArkanum: (state) => (data) => {
        return state.kisArkanum.filter(s => s.mana <= data.mana && s.sfera.some(s => data.sfera.includes(s)));
    },
    nagyArkanum: () => {
        return state.nagyArkanum;
    },
    nagyArkanumCurrentAll: (state) => (data) => {
        return state.nagyArkanum.filter(s => s.sfera.some(s => data.sfera.includes(s)));
    },
    availableNagyArkanum: (state) => (data) => {
        return state.nagyArkanum.filter(s => s.mana <= data.mana && s.sfera.some(s => data.sfera.includes(s)));
    },
    egyediKisArkanum: (state) => (vallasId) => {
        return state.kisArkanumEgyedi.filter(s => s.istenId == vallasId);
    },
    egyediNagyArkanum: (state) => (vallasId) => {
        return state.nagyArkanumEgyedi.filter(s => s.istenId == vallasId);
    },
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}