/**-------------------------------------------
 * 
 * STORE FOR MAGUS CLASSES
 * 
 * -------------------------------------------
 */
 const state = {
    //kasztok
    classes: [
        {
            id: 'HARCOS',
            name: 'Harcos',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                'A harcosok kasztjába azokat az elsődleges fegyverforgatásra kitanitott karaktereket soroljuk, akik jóval többek, mint egyszerű katonák, de nem részesültek lovagi nevelésben, sem gladiátori kiképzésben, és nem is valamilyen fejvadászklán berkeiben nőttek fel.A harcos messze a legnépesebb karakterkaszt: tagjai között találunk kalandorokat, kalandozókat, testőröket, magányos zsoldosokat, sőt uralkodókat is.',
                'A harcosok azok, akik a fegyverforgatáson túl a legkülönfélébb dolgokhoz értenek. Akad közöttük olyan, aki jártas a mágiában, aki tolvajként is megállná a helyét, mint ahogy olyan is, aki ostoba, de erős, akár egy Keleti Barbár.',
                'Ahány tája Ynevnek, annyifélék a harcosok.',
                'A keleti barbárok testi erejükről, súlyos fegyvereikről ismertek.Nem hordanak páncélt, olykor ruhát sem, csak egyetlen ágyékkötőt. Eszük kevés, de birnak egyfajta józan, természetes erkölcsiséggel - és hihetetlen szakértelemmel forgatják kétkezes kardjukat, bárdjukat',
                'Gorvik hegyvidékének lakói örökös viszálykodásban, családi háborúságban állnak egymással.Súlyos prémekkel védekeznek a hideg ellen, és bőrvértekkel társaik keskeny, tűhegyes kardjaival szemben. Nem idegen tőlük a hátulról, lesből támadás, a méreg használata, s a ravaszkodás sem.',
                'Yllinorban, Mogorva Chei országában mérhetetlenül magas a harcos kasztúak száma. Úgy tartják sehol másutt nem élnek annyian mint itt. Könnyű láncinget viselnek, hosszú kardot, egykezes csatabárdot, csatacsákányt forgatnak. Kiváló lovasok - azt beszélik az utca túloldalára is lóval járnak - és ugyanilyen remek céllövészek. Hosszú, szarulemezekből ragasztott, visszacsapó ijakat használnak. Lelkes odaadással éltetik királyukat és istennőjüket.',
                'A Pyarron környéki várakban, általában egy-egy lovagrend árnyékában léteznek harcos rendek, mely nem kizárólag a fegyverforgatásban jeleskednek, hanem a különféle tudományokban is. Ők álltalában a lovagokéhoz hasonló életet élnek, nehézvértezetet és nehézfegyvereket viselnek, mégsem lovagok, inkább azok kisérői, tanácsnokai, testőrei.'
            ],
            kulonleges: '-',
            harcertek: 'A harcosok harcértékei az egyik legkedvezőbb a magus kasztjai közül. Egyedül a gladiátorok különb fegyverforgatók náluk, és a Harcművészek olyankor, amikor Pszi-képességükhöz folyamodnak. Egy harcos kasztú karakter KÉ alapja 9, TÉ alapja 20, VÉ alapja 75, CÉ alapja 0, továbbá minden tapasztalati szinten ( már az elsőn is ) 11 Harcérték Módositót kap. Ezt tetszése szerint szétoszthatja KÉ-je, TÉ-je, VÉ-je és CÉ-je között, azonban TÉ-jére és VÉ-jére köteles minden szinten 3-3 pontot álldozni ( a rendszer autómatikusan levonja ). Az zllinori származású harcos karakter CÉ-jét is köteles minden Tapasztalati Szinten 3-mal növelni.',
            eletero: 'A harcosok életerő és fájdalomtűrés tekintetében is a legjobbak közé tartoznak. Gyermekkoruktól kezdve egészséges életet élnek, ezer megpróbáltatást küzdenek le, ami megedzi őket. Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'A harcos, mint az eddigiekből is kiviláglott, a lehtőségek kasztja. A harcon túl semmit sem köteles megtanulni, igy bőven jut ideje és energiája arra, hogy bármilyen képzettséget elsajátitson. Ez mutatkozik meg abban, hogy az összes kasztok közül a harcos bir a legtöbb Képzetségi Pontal ( Kp ): Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: 'A harcosok annyiféle fegyverrel verekszenek, ahány félék. Egyes tájegységekre és szervezetre persze jellemző lehet egy adott fegyver és vértezett. A harcosok ahogy egyre tapasztaltabbak lesznek, egy legfeljebb két fegyver használatát sajátitják el mesterfokon. Ezek természetesen azok, melyeket leggyakrabban forgatnak. A harcos már alacsony szinten is erős karakter, és ha a játékos ügyesen gazdálkodik a magas Harcérték Módositóval valamint a Képzetségi Pontokkal, ez később sem változik meg. Mindenkinek melegen ajánljuk a kasztot, annak pedig, aki először játszik egyenesen forrón.',
        },
        {
            id: 'GLADIATOR',
            name: 'Gladiátor',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+12+kf', sp: [9, 20, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '2k6+6', sp: [8, 18, 0]},
            INT: { name: '3k6', sp: [3, 18, 0]},
            AK: {name: '3k6', sp: [8, 18, 0]},
            ASZT: { name: '3k6', sp: [3, 18, 0]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 4,
            VESzintKotelezo: 4,
            CESzintKotelezo: 0,
            HmSzint: 4,
            Epalap: 8,
            Fpalap: 7,
            FpSzint: {
                name: 'k6+5',
                sp: [5, 11]
            },
            Kpalap: 3,
            KpSzint: 6,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 4,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['BIRKOZAS', 'OKOLHARC', 'KETKEZES_HARC', 'PANCEL_VISELET', 'PAJZS_HASZNALAT', 'FEGYVERTORES'],
                mf: [],
                precent: {
                    maszas: 0,
                     eses: 30,
                     ugras: 20,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                2 : {
                    FegyverhasznalatAlap: 1,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: [],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
                4 : {
                    FegyverhasznalatAlap: 1,
                    FegyverhasznalatMester: 1,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: [],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
                5 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: [],
                    mf: ['KETKEZES_HARC'],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['VAKHARC'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
                7 : {
                    FegyverhasznalatAlap: 2,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: [],
                    mf: ['PAJZS_HASZNALAT'],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
                9 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: [],
                    mf: ['FEGYVERTORES'],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 188],
                [189, 376],
                [377, 825],
                [826, 1650],
                [1651, 3300],
                [3301, 7250],
                [7251, 12050],
                [12051, 24000],
                [24001, 48000],
                [48001, 68000],
                [68001, 93000],
                [93001, 130000],
                40000
            ],
            description: [
                'A gladiátorok azon harcosok, akik elsősorban egy az egy elleni, netán páros küzdelemre képeztek ki. Kiemelt figyelmet forditanak erejük, állóképességük növelésére, fájdalomtűrésük, és életerejük fokozására. A különleges képzés egyetlen célja, hogy az arénákban, a közönség épülésére felülkerekedjenek társaikon.',
                'A gladiátorviadal elterjedt és közkedvelt szórakozás egész Yneven. Számtalan formáját ismerik, ám négy fő irányzat különböztethető meg.',
                'Az abasziszi rendszerű viadal során a küzdelem szigorú szabályok alapján folyik. Ezek meghatározzák a résztvevő felek fegyverzetét, vértezetét, de még azt is, hogy milyen fegyverzetű gladiátor ellen milyen másik állitható ki. Egyedül ebben a rendszerben ismerik a súlycsoport fogalmát. Abasziszi rendszerű viadalt egy az egy ellen, ritkán párosan vivnak.',
                'A dzsad rendszerű viadal során emberek állnak ki állatok, szörnyek ellen. Inyenccsemegének számitanak a messzi tájakról hozott, különleges teremtmények - természetesen, csak a közönség szemében. Olykor, ha nem emberi ellenfelet a szervezők túlzottan veszedelmesnek itélik, egyszerre kettő, három, vagy még több gladiátort állitanak ki ellene.',
                'A tiadlani rendszerű viadal álltalában pusztakezes küzdelmet jelent. Alapvető törvény, hogy mindég csak egy harcol egy ellen. Olykor azonban fegyveresek is feltűnnek közöttük - nem számitanak külön kategóriának. Szabály nemigen akad, és a viadalokon legtöbbször harcművészek vesznek részt.',
                'A toroni rendszerű viadalt sokan a gladiátorjátékok kirájának tekintik, és ebben bizony lehet némi igazság. Egyetlen másik küzdelmi forma sem bir ilyen összetett szabályrendszerrel, és nyújt ehhez fogható szórakozást közönségének. A viadalon az arénában egy-egy nehézvértezetű gladiátor jelenik meg, ám vannak segitőik. Ezek egyike boszorkánymester, a másik számszerijász, a harmadik és negyedik tőrvető, az ötödik pedig egyfajta hadvezér, aki a csapat munkáját összehangolja, utasitásokat ad a résztvevőknek. A küzdelem folyamán hihetetlenül aljas trükköket vetnek be a versengő felek, ám, hogy mikor miként cselekedhetnek arról bonyolult szabályrendszer rendelkezik. A viadalt az a csapat nyeri, amely huzamosabb időre harcképtelenné teszi az ellenfél gladiátorát.',
            ],
            kulonleges: 'A gladiátorok különleges képessége, hogy ha egy az egy ellen kerülnek szembe ellenfelükkel, még kitünőbb harcosoknak számitanak. Ilyenkor a harcértékük a következőképp módosul: LÉ: +5, TÉ: +5, VÉ: +10, CÉ:- . Ha pedig mindez arénában történik, avagy népesebb nézősereg szeme előtt, ők még felajzottabban küzdenek, igy harcértékük tovább nő: KÉ: +5, TÉ: +5, VÉ: +5, CÉ: -.',
            harcertek: 'A Karakter Kasztok közül a gladiátor bir a legmagasabb harcértékekkel. KÉ alapja 9, TÉ alapja 20, VÉ alapja 75, CÉ alapja 0, valamint minden Tapasztalati Szinten 12 Harcérték Módositót kap, amit tetszés szerint oszthat el KÉ-je, TÉ-je, VÉ-je, CÉ-je között. Egyetlen megkötést kell figyelembe vennie: mind TÉ-jét, mind VÉ-jét TSZ-enként 4-el növelnie kell ( a program elvégzi ).',
            eletero: 'A gladiátorok a legéleterősebb karakterek, és a fájdalmat is jól tűrik. Ép alapjuk 8, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. Az Fp alapja 7, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 5 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'A gladiátor - mint láttuk - sok szempontból különfélék ugyan, mégis nagyon hasonlóak egymáshoz. Kiképzésük meglehetősen célirányatos, sok képzetséget kötelesek elsajátitani ahhoz, hogy valóban gladiátornak számitsanak.Kp alapja 3, és minden Tapasztalati Szinten ( már 1. szinten is ) további 6-ot kap.',
            tapasztalat: 'A kaszt tagjai számára az alacsony TSZ-ek közepesen könnyen elérhetők, azután egyre nehezebb, végül 10. szint betöltésével immár újból könnyebben.',
            fegyvertar: 'A gladiátorok sokféle fegyvert és páncélt viselnek az arénábanRitka esetben húznak magukra merev fémvértet. Fegyvereik között akad jó pár különleges jószág. Például a szigony és háló, élezett peremű pajzsok.',
        },
        {
            id: 'FEJVADASZ',
            name: 'Fejvadász',
            ERO: { name:'2k6+6', sp: [8, 18, 0]},
            GYORS: { name: 'k6+12+kf', sp: [13, 18, 1]},
            UGY: { name: 'k10+8', sp: [9, 18, 0]},
            ALLO: { name: 'k6+12+kf', sp: [13, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6', sp: [3, 18, 0]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: 'k10+8', sp: [9, 18, 0]},
            ASZT: { name: '2k6+6', sp: [8, 18, 0]},
            KEalap: 10,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 4,
            VESzintKotelezo: 4,
            CESzintKotelezo: 0,
            HmSzint: 3,
            Epalap: 6,
            Fpalap: 7,
            FpSzint: {
                name: 'k6+5',
                sp: [6, 11]
            },
            Kpalap: 3,
            KpSzint: 5,
            KpPrecent: 20,
            Pszi: {
                learned: true,
                atlevel: 1,
                level: 'Af',
                maxPszi: 4,
                psziPointLevel: 3,
                currentPszi: 4,
                school: 'Pyarroni',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 9,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 3,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['OKOLHARC', 'USZAS', 'FUTAS', 'PSZI', 'CSAPDAALLITAS', 'ALCAZAS', 'HATBASZURAS'],
                mf: [],
                precent: {
                    maszas: 30,
                     eses: 15,
                     ugras: 15,
                     lopakodas: 20,
                     rejtozes: 25,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 10,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        {
            id: '',
            name: '',
            ERO: { name:'k6+12+kf', sp: [13, 18, 1]},
            GYORS: { name: '2k6+6+kf', sp: [8, 18, 1]},
            UGY: { name: '2k6+6+kf', sp: [8, 18, 1]},
            ALLO: { name: 'k10+8+kf', sp: [9, 18, 1]},
            EG: { name: 'k10+10', sp: [11, 20, 0]},
            SZEP: { name: '3k6x2', sp: [3, 18, 2]},
            INT: { name: '3k6x2', sp: [3, 18, 2]},
            AK: {name: '2k6+6', sp: [8, 18, 0]},
            ASZT: { name: '3k6x2', sp: [3, 18, 2]},
            KEalap: 9,
            TEalap: 20,
            VEalap: 75,
            CEalap: 0,
            KESzintKotelezo: 0,
            TESzintKotelezo: 3,
            VESzintKotelezo: 3,
            CESzintKotelezo: 0,
            HmSzint: 5,
            Epalap: 7,
            Fpalap: 6,
            FpSzint: {
                name: 'k6+4',
                sp: [5, 10]
            },
            Kpalap: 10,
            KpSzint: 14,
            KpPrecent: 0,
            Pszi: {
                learned: false,
                atlevel: 0,
                level: '',
                maxPszi: 0,
                psziPointLevel: 0,
                currentPszi: 0,
                school: '',
                staticAsztral: 0,
                staticMental: 0,
                dinamicAsztarl: 0,
                dinamicMental: 0,
            },
            mpLevel: {
                text: '0',
                range: [0, 0],
            },
            skillsFirstLevel: {
                FegyverhasznalatAlap: 3,
                FegyverhasznalatMester: 0,
                FegyverdobasAlap: 0,
                FegyverdobasMester: 0,
                NyelvismeretAf: 0,
                NyelvismeretMf: 0,
                SzakmaAf: 0,
                SzakmaMf: 0,
                af: ['LOVAGLAS', 'USZAS', 'FUTAS'],
                mf: [],
                precent: {
                    maszas: 15,
                     eses: 20,
                     ugras: 10,
                     lopakodas: 0,
                     rejtozes: 0,
                     koteltanc: 0,
                     zsebmetszes: 0,
                     csabdafelfedezes: 0,
                     zarnyitas: 0,
                     titkosajto: 0,
                },
            },
            skillsOtherLevel: {
                6 : {
                    FegyverhasznalatAlap: 0,
                    FegyverhasznalatMester: 0,
                    FegyverdobasAlap: 0,
                    FegyverdobasMester: 0,
                    NyelvismeretAf: 0,
                    NyelvismeretMf: 0,
                    SzakmaAf: 0,
                    SzakmaMf: 0,
                    af: ['HADVEZETES'],
                    mf: [],
                    precent: {
                        maszas: 0,
                        eses: 0,
                        ugras: 0,
                        lopakodas: 0,
                        rejtozes: 0,
                        koteltanc: 0,
                        zsebmetszes: 0,
                        csabdafelfedezes: 0,
                        zarnyitas: 0,
                        titkosajto: 0,
                    },
                },
            },
            TpSzint:[
                [0, 160],
                [161, 320],
                [321, 640],
                [641, 1440],
                [1441, 2800],
                [2801, 5600],
                [5601, 10000],
                [10001, 20000],
                [20001, 40000],
                [40001, 60000],
                [60001, 80000],
                [80001, 112000],
                31200
            ],
            description: [
                '',
                '',
            ],
            kulonleges: '',
            harcertek: '',
            eletero: 'Ép alapjuk 7, amihez a karakternek még egészség tiz feletti részét kell hozzáadnia, hogy megkapja Életerő Pontjainak számát. A harcos Fp alapja 6, amihez még Akaratereje és Állóképessége tiz feletti hányada, Tapasztalati Szintenként pedig további k6 + 4 Fp ( már 1. szinten is ) járul.',
            kepzetsegek: 'Kp alapja 10, és minden Tapasztalati Szinten ( már 1. szinten is ) további 14-et kap.',
            tapasztalat: 'A harcos kasztú karakter számára a TSZ-lépés annál nehezebb, minnél magasabb a szint, amelyre fellépni igyekszik.',
            fegyvertar: '',
        },
        
        
    ]
};
const getters = {
    classes: (state) => {
        return state.races;
    },
    magusClass: (state) => (id) => {
        return state.classes.find(r => r.id === id) ?? state.classes[0];
    }
};
const mutations = {};
const actions = {};
export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}