/**-------------------------------------------
 * 
 * STORE FOR MAGUS BESTIARIUM
 * 
 * -------------------------------------------
 */
 const state = {
    //need at least 15 for begining
    monsters: [
        {
            name: 'Goblin',
            race: 'Goblin',
            level: '1',
            exp: '10',
            ERO: '10',
            GYORS: '12',
            UGY: '12',
            ALLO: '10',
            EG: '9',
            SZEP: '8',
            INT: '8',
            AK: '10',
            ASZT: '7',
            KE: '16',
            TE: '27',
            VE: '78',
            CE: '5',
            SP: 'k6',
            SFE: '0',
            EP: '4',
            FP: '7',
            description: 'A nagyobb törzsektől elszökött kis goblin csapat gyakori jelenség szinte minden erdőben, völgyben. Álltalában 3-10 fős csapatocska, akik szinte mindenkit megtámadnak, ha azok nem szemmel láthatólag erősebbek náluk. Fegyverzetük álltalában furkósbot, de néha szert tesznek más fegyverekre is.',
            role: 'A goblin csapatok rendszeressen megtámadják a falvakat és utazókat, igy elsődleges célpontjai a ki kell írtani őket küldetéseknek.',
            sablon: 'Megtámadnak mindenkit akit meglátnak, kivéve, ha az illetők szemmelláthatóan erősebbek, ilyenkor szöknek és csak akkor harcolnak, ha nincs más lehetőség. Ha valakit megtámadtak és a megtámadotak kezdenek felülkerekesni ( a goblinok egyharmada halott, vagy harcképtelen ), menekülőre fogják a dolgot.',
        },
    ],
    animals: [
        {
            name: 'Barrakuda, a tengeri farkas',
            race: 'hal',
            level: '1',
            exp: '15',
            ERO: '10',
            GYORS: '13',
            UGY: '12',
            ALLO: '14',
            EG: '10',
            SZEP: '3',
            INT: '5',
            AK: '15',
            ASZT: '3',
            KE: '40',
            TE: '100',
            VE: '150',
            CE: '0',
            SP: 'k10',
            SFE: '0',
            EP: '5',
            FP: '20',
            description: 'E tengeri csukafajtától egyes helyeken jobban félnek mint a cápától. Gyorsan úszik, nagyra tátható szájában tűhegyes fogak sorakoznak. Hossza elérheti a 2 - 2,5 métert.',
            role: 'A vízbe esett ficánkoló lényeket támadja partközelben.',
            sablon: '2 - 20 fős csoportokban támadnak.',
        },
        {
            name: 'Denevér',
            race: 'Állat',
            level: '1',
            exp: '2',
            ERO: '3',
            GYORS: '10',
            UGY: '10',
            ALLO: '6',
            EG: '10',
            SZEP: '3',
            INT: '3',
            AK: '8',
            ASZT: '3',
            KE: '20',
            TE: '20',
            VE: '92',
            CE: '0',
            SP: '1',
            SFE: '0',
            EP: '2',
            FP: '5',
            description: 'Szinte mindenhol előfordulnak, nappal barlangok mélyén, padlásokon, faodvakban tanyáznak. Este álltalában alvó állatok vérével táplálkoznak. Méretük ritkán haladja meg a 30 centit.',
            role: 'Sötét helyeken tanyáznak, álltalában nem jelentenek veszélyt az emberre, ha nem zavarják meg őket. Legegyszerűbb kifüstölni őket.',
            sablon: 'Ha felzavarják őket, csapatban a karakterekre vetik magukat és vérüket szívják. Körönként 1 sp sebzést mindenképp okoznak, hacsak a karakter teljesen le van fedve legalább 1 SFÉ értékű páncéllal. Elzavarni őket könnyebb, mint egyenként levadázsni. Álltalában 2 - 20 fős rajban gyülekeznek, de akár 100 fős raj sem ritka.',
        },
        {
            name: 'Farkas',
            race: 'Állat',
            level: '1',
            exp: '5',
            ERO: '10',
            GYORS: '12',
            UGY: '13',
            ALLO: '14',
            EG: '12',
            SZEP: '10',
            INT: '5',
            AK: '14',
            ASZT: '6',
            KE: '10',
            TE: '35',
            VE: '60',
            CE: '0',
            SP: 'k6',
            SFE: '0',
            EP: '18',
            FP: '38',
            description: 'Szinte minden mérsékelt égövi erdőben, hegyekben megtalálható. 2 -20 fős falkában vadásznak, a falkavezér mindég a legerősebb ( +5 TÉ, +5 VÉ, +2 Ép, +4 Fp ).',
            role: 'Ha éhesek megtámadnak minden nagyobb testű állatot, embert. Folyamatos veszályt jelentenek a környéken élőkre,',
            sablon: 'Harc közben körülveszik álldozatukat, mindég hátulról vagy félhátulról támadnak ( ha tehetik ). Ha a falkavezér meghal, a többi farkas elmenekül.',
        },
        {
            name: 'Fehér tigris',
            race: 'Állat',
            level: '1',
            exp: '25',
            ERO: '12',
            GYORS: '16',
            UGY: '16',
            ALLO: '14',
            EG: '16',
            SZEP: '12',
            INT: '5',
            AK: '14',
            ASZT: '6',
            KE: '30',
            TE: '50',
            VE: '70',
            CE: '0',
            SP: 'k3 / k3 / k10 + 2',
            SFE: '0',
            EP: '25',
            FP: '40',
            description: 'Havas területek magányos vadásza. Kissebb méretű az áttlagos tigriseknél, testét fehér prém fedi, melyet fakó szürke csíkok díszítenek. Remek vadászok.',
            role: 'Egyes helyeken az élő példányokért akár 3 - 4 aranyat is fizetnek, de agyara és bundája is kelendő. Ám elfogni, vagy akárcsak megtalálni nem egyszerű.',
            sablon: 'Álltalában lesből támad, mancsaival karmol és megpróbálja átharapni az álldozata nyakát. Ha erősebb ellenféllel kerül szemben, megpróbál elszökni, ha a sarokba szorul a végsőkig harcol.',
        },
        {
            name: 'Krokodil',
            race: 'Hüllő',
            level: '1',
            exp: '300',
            ERO: '18',
            GYORS: '16',
            UGY: '10',
            ALLO: '14',
            EG: '12',
            SZEP: '8',
            INT: '3',
            AK: '16',
            ASZT: '3',
            KE: '70',
            TE: '130',
            VE: '160',
            CE: '0',
            SP: '3k6',
            SFE: '7',
            EP: '45',
            FP: '90',
            description: 'Majd minden forró égövi folyamában fellelhető. A helybeliek ismerik e hüllő területeit és messze elkerülik azt. Hosszuk 6 - 8 méter, testüket kemény pikkely borítja.',
            role: 'A krokodilok az inni járó állatok közül szedik álldozataikat, de az embert is megtámadják.',
            sablon: 'Az álldozatra hirtelen csap le és megróbálja lehúzni a folyó mélyére.',
        },
        {
            name: 'Medve',
            race: 'Állat',
            level: '1',
            exp: '30',
            ERO: '18',
            GYORS: '10',
            UGY: '10',
            ALLO: '15',
            EG: '14',
            SZEP: '10',
            INT: '3',
            AK: '12',
            ASZT: '5',
            KE: '5',
            TE: '50',
            VE: '60',
            CE: '0',
            SP: 'k6+2 / k6+2 / k6',
            SFE: '1',
            EP: '38',
            FP: '50',
            description: 'A medvék hatalmas testű, mindenevő állatok, melyek szinte bármelyik erdőben, hegyekben megtalálhatóak.',
            role: 'Mivel elsősorban nem ragadozók, álltalában nem támadnak meg senkit, csakha bocsaikat veszély fenyegeti, vagyha éhesek.',
            sablon: 'Hátsó mancsaira emelkedik, majd az első két mancsával támad és harap. Ha mindkét mancsával túlütötte álldozatát magához szorítja.',
        },
        {
            name: 'Mérgeskígyók',
            race: 'Hüllő',
            level: '1',
            exp: '1',
            ERO: '6',
            GYORS: '15',
            UGY: '10',
            ALLO: '8',
            EG: '12',
            SZEP: '3',
            INT: '3',
            AK: '8',
            ASZT: '3',
            KE: '35',
            TE: '30',
            VE: '50',
            CE: '0',
            SP: 'k2',
            SFE: '0',
            EP: '3',
            FP: '6',
            description: 'A különböző mérgeskígyók a legváltozatosabb színeket és mintázatokat mutatják, melyek egyes fajaikra jellemzők.',
            role: 'Álltalában lomhán napoznak, ha valaki megközelíti őket felemelkednek és fenyegetik a közeledőtt.',
            sablon: 'A támadás álltalában egy villámgyors harapás, ha a harapott területen a karakter páncélt visel nincs sebzés és a méreg sem jut a szervezetébe. A méreg ereje és hatása különböző lehet fajtól függően ( a KM határozza meg ).',
        },
        {
            name: 'Nganga',
            race: 'Majom',
            level: '1',
            exp: '60',
            ERO: '16',
            GYORS: '14',
            UGY: '16',
            ALLO: '14',
            EG: '12',
            SZEP: '8',
            INT: '6',
            AK: '13',
            ASZT: '9',
            KE: '15',
            TE: '95',
            VE: '120',
            CE: '0',
            SP: 'k10+4 / k10+4 / k6',
            SFE: '0',
            EP: '35',
            FP: '70',
            description: 'A nganga az erdők óriási majma. Sárgás fogsora, emberderéknyi karja nem sok jót ígér az útjába tévedőknek. Álltalában 3 - 30 majomból álló csoport él együtt, de előfordulnak magányos példányok is.',
            role: 'Ha magukat veszélyben érzik, vagy a párzási időben igen agresszívá válnak, egyébbként csak a területüket védik.',
            sablon: 'Mikor harcra kerül a sor, elősször minden kezükbe akadó dolgot az ellenfélhez vágnak, majd öklöznek és harapnak. A végsőkig harcolnak, nem futamodnak meg.',
        },
        {
            name: 'Óriás pók',
            race: 'Rovar',
            level: '1',
            exp: '3',
            ERO: '8',
            GYORS: '10',
            UGY: '10',
            ALLO: '8',
            EG: '12',
            SZEP: '3',
            INT: '3',
            AK: '10',
            ASZT: '3',
            KE: '25',
            TE: '30',
            VE: '60',
            CE: '0',
            SP: 'k3 + méreg',
            SFE: '2',
            EP: '6',
            FP: '13',
            description: 'Nem ritkán kutyaméretűre megnőnek, meleg éghajlatú erdőségekben tanyáznak. Hálóikat talajszinten a fák közé feszítik. Mérgük akár egy lóval is végezhet. Ez a méreg 6. szintű, azonnal ható, közepes ideig tartó halált vagy görcsöt okozó méreg.',
            role: 'Ritkán harcol, álltalában csak elrejtőzve várja álldozatát, hogy a hálójába akadjon.',
            sablon: 'Ha a karakter a hálóba gabalyodik az első körben -2 vel tehet Erőbróbát, majd minden körben -1 járul a próbához, addig harc helyhez kötve módosítóval harcol. Egy óriáspókból maximum 6 adag méreg nyerhető ki.',
        },
        {
            name: 'Öreg medve ( Őrült medve )',
            race: 'Állat',
            level: '1',
            exp: '100',
            ERO: '20',
            GYORS: '13',
            UGY: '13',
            ALLO: '18',
            EG: '14',
            SZEP: '6',
            INT: '3',
            AK: '16',
            ASZT: '3',
            KE: '25',
            TE: '80',
            VE: '90',
            CE: '0',
            SP: '2k6+2 / 2k6+2 / k10',
            SFE: '1',
            EP: '45',
            FP: '110',
            description: 'Lakott települések közelébe tanyázik, és rettegésben tartja azt. Elragadja a magányos utazókat, esténként betör a házakba, mondják gonosz szellem szállta meg.',
            role: 'Rettegésben tartja a települést, nem hátrál vagy szökik, haláláig harcol.',
            sablon: 'Mancsaival üt és harap nagyon aggresszív.',
        },
    ],
    aquirs: [
        {
            name: 'Gho-ragg',
            race: 'Kráni aquir',
            level: '1',
            exp: '650',
            ERO: '18',
            GYORS: '14',
            UGY: '14',
            ALLO: '16',
            EG: '14',
            SZEP: '12',
            INT: '11',
            AK: '16',
            ASZT: '9',
            KE: '40',
            TE: '90',
            VE: '150',
            CE: '0',
            SP: 'k10+4 / k10+4',
            SFE: '0',
            EP: '20',
            FP: '80',
            description: 'A legismertebb kis aquir faj Krán-szerte. Álltalában 200-300 fős törzsekbe tömörülve élnek valamely nemes aquir szolgálatában. Csak férfi tagjaik vannak, ezért nőket rabolnak, hogy szaporodhassanak. Az álldozat szinte mindég belehal a szülésbe, ha nem megölik. Csak a harchoz értenek. Fegyverük a kétélű csatabárd és a pajzs. Hatalomszavakat korcsnyelven 1 - 3 Od-ig tudnak használni.',
            role: 'Kránon kívül ritkán találkozni velük, ha mégis akkor nőt mennek rabolni, vagy uruk parancsát követik. Ilyenkor 5 - 50 fős csapatba haladnak.',
            sablon: 'Mikor harcra kerül sor rohamozás közben hatalomszavaikat üvöltik, majd közelharcot fojtatnak.',
        },
        {
            name: 'Kir-siss',
            race: 'Kráni aquir',
            level: '1',
            exp: '600',
            ERO: '5',
            GYORS: '6',
            UGY: '6',
            ALLO: '8',
            EG: '10',
            SZEP: '4',
            INT: '14',
            AK: '12',
            ASZT: '9',
            KE: '5',
            TE: '25',
            VE: '60',
            CE: '0',
            SP: '- ( mentális 55E )',
            SFE: '0',
            EP: '5',
            FP: '20',
            description: 'A nemes aquirok álltal lakott barlangok őrei. Testük lárvaszerű, rajta uruk bélyegével. Csak asztrális látással rendelkeznek és igen védtelennek tűnnek, de daluk megőrjíti az azt halló egyént.',
            role: 'A barlangok bejáratánál énekelnek, álltalában 1 - 5 fős csoportban.',
            sablon: 'Csak énekelnek, akik halják az éneket 55E Asztrális mágiaellenállást kényszerülnek dobni minden körbe, ha elvétik őrület lesz rajtuk urrá ( a süketség, fül befogása ilyenkor segít ). Ha megtámadják őket, dalukat a támadóra irányítsák, ilyenkor 5 kör alatt megőrül, mégha siket vagy megdobta mágiapróbáját ( kivéve ha van Od védelme, vagy előbb öli meg )',
        },
        {
            name: 'Shi-kris',
            race: 'Kráni aquir',
            level: '1',
            exp: '1300',
            ERO: '14',
            GYORS: '14',
            UGY: '12',
            ALLO: '13',
            EG: '12',
            SZEP: '6',
            INT: '14',
            AK: '12',
            ASZT: '9',
            KE: '25',
            TE: '35',
            VE: '80',
            CE: '0',
            SP: 'Fegyvertől függ',
            SFE: '0',
            EP: '10',
            FP: '40',
            description: 'Alakváltó kis aquir faj. Képes lemásolni egy humanoidot és felvenni annak alakját, még gondolkodásmódját is. Ha az álldozat elvéti ME jét 15 E vel szemben elméleti tudását is lemásolja. Egyszerre csak egy lényt tud lemásolni. Gyűlöli urát, és ha teheti elárulja azt. Előszeretettel öli az embereket.',
            role: 'Álltalában kémként küldik emberek közé. Velejéig romlott megbízhatatlan szolga, ha nem fogják rövid pórázon elárulja gazdáját.',
            sablon: 'Alakváltás közben szeret bajt keverni, nem túl jó harcos, ugyhogy a nyílt harcot kerüli, képes hatalomszavakat használni korcs nyelven 1-10 Od-ig',
        },
        {
            name: 'Korcs ( Ochak Va Maadad )',
            race: 'Ediomadi aquir',
            level: '1',
            exp: '400',
            ERO: '12',
            GYORS: '10',
            UGY: '12',
            ALLO: '10',
            EG: '10',
            SZEP: '10',
            INT: '12',
            AK: '11',
            ASZT: '9',
            KE: '35',
            TE: '70',
            VE: '90',
            CE: '50',
            SP: 'fegyvertől függ',
            SFE: '0 - 6',
            EP: '12',
            FP: '30',
            description: 'A Valóvérűek leszármazottai, de némák és nem képesek hatalomszavakat használni, viszont képesek használni az aquir fegyvereket és vérteket. Kiválló céllövők.',
            role: 'Ediomad határvidékén tanyáznak 1 -6 fős csoportokban. Megtámadnak minden nem odavalót.',
            sablon: 'Szeretnek csapdákat állítani, lesből támadni.',
        },
        {
            name: 'Szolga ( Idan Va Dreeteh )',
            race: 'Ediomadi aquir',
            level: '1',
            exp: '100',
            ERO: '14',
            GYORS: '12',
            UGY: '12',
            ALLO: '14',
            EG: '14',
            SZEP: '10',
            INT: '10',
            AK: '14',
            ASZT: '9',
            KE: '28',
            TE: '60',
            VE: '100',
            CE: '30',
            SP: 'fegyvertől függ',
            SFE: '0-4',
            EP: '15',
            FP: '30',
            description: 'Az aquirok különböző csatlós fajai. A barlangok bejáratait őrzik és Zászlósháborúk idején ők képezik Ediomad derékhadát. Legkülönb fajokból állnak össze, mágiát pszit vagy Odot nem használnak. Közös jellemzőik az aquir felszerelés, melyeket képesek használni.',
            role: 'A határ mentén tanyáznak 1 -10 fős csoportokban és elsődlegesen határőrök.',
            sablon: 'Fegyvertől és felszereléstől függően ugy harcolnak mind bármely katonai hadtest ( portyázó csapat ).',
        },
    ],
    demons: [
        {
            name: '',
            race: '',
            level: '1',
            exp: '10',
            ERO: '20',
            GYORS: '3',
            UGY: '3',
            ALLO: '20',
            EG: '10',
            SZEP: '3',
            INT: '0',
            AK: '0',
            ASZT: '0',
            KE: '0',
            TE: '10',
            VE: '55',
            CE: '0',
            SP: 'k6+5',
            SFE: '0',
            EP: '4',
            FP: '-',
            description: '',
            role: '',
            sablon: '',
        },
    ],
    jins: [
        {
            name: '',
            race: '',
            level: '1',
            exp: '10',
            ERO: '20',
            GYORS: '3',
            UGY: '3',
            ALLO: '20',
            EG: '10',
            SZEP: '3',
            INT: '0',
            AK: '0',
            ASZT: '0',
            KE: '0',
            TE: '10',
            VE: '55',
            CE: '0',
            SP: 'k6+5',
            SFE: '0',
            EP: '4',
            FP: '-',
            description: '',
            role: '',
            sablon: '',
        },
    ],
    elementals: [
        {
            name: '',
            race: '',
            level: '1',
            exp: '10',
            ERO: '20',
            GYORS: '3',
            UGY: '3',
            ALLO: '20',
            EG: '10',
            SZEP: '3',
            INT: '0',
            AK: '0',
            ASZT: '0',
            KE: '0',
            TE: '10',
            VE: '55',
            CE: '0',
            SP: 'k6+5',
            SFE: '0',
            EP: '4',
            FP: '-',
            description: '',
            role: '',
            sablon: '',
        },
    ],
    undeads: [
        {
            name: '',
            race: '',
            level: '1',
            exp: '10',
            ERO: '20',
            GYORS: '3',
            UGY: '3',
            ALLO: '20',
            EG: '10',
            SZEP: '3',
            INT: '0',
            AK: '0',
            ASZT: '0',
            KE: '0',
            TE: '10',
            VE: '55',
            CE: '0',
            SP: 'k6+5',
            SFE: '0',
            EP: '4',
            FP: '-',
            description: '',
            role: '',
            sablon: '',
        },
    ],
    plants: [
        {
            name: '',
            race: '',
            level: '1',
            exp: '10',
            ERO: '20',
            GYORS: '3',
            UGY: '3',
            ALLO: '20',
            EG: '10',
            SZEP: '3',
            INT: '0',
            AK: '0',
            ASZT: '0',
            KE: '0',
            TE: '10',
            VE: '55',
            CE: '0',
            SP: 'k6+5',
            SFE: '0',
            EP: '4',
            FP: '-',
            description: '',
            role: '',
            sablon: '',
        },
    ],
};
const getters = {
    monsters: () => {
        return state.monsters;
    },
    animals: () => {
        return state.animals;
    },
    aquirs: () => {
        return state.aquirs;
    },
    demons: () => {
        return state.demons;
    },
    jins: () => {
        return state.jins;
    },
    elementals: () => {
        return state.elementals;
    },
    undeads: () => {
        return state.undeads;
    },
    plants: () => {
        return state.plants;
    },
};
const mutations = {};
const actions = {};

export default {
    namespaced: true,
    state,
    getters,
    mutations,
    actions,
}